---
title: "엔트로피와 열역학적 포텐셜"
number-sections: true
number-depth: 2
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

## 순환에서의 특성 {#sec-TD_entropy}

$n$ 개의 온도가 $T_i$ ($i=1,\ldots,\,n$) 인 열원을 생각하자. 그리고 $T_i$ 열원에서 주고받는 열을 각각 $Q_i$ 라고 하자. $Q_i>0$ 이면 열원으로 부터 열을 받으며, $Q_i<0$ 이면 열을 방출한고 하자. 그리고 전체 과정이 순환이라고 하자. 우리는 다음을 보일 것이다.

$$
\sum_{i=1}^n \dfrac{Q_i}{T_i} \le 0.
$$ {#eq-TD_primitive_form_of_entropy}

이 때 등호는 전체 과정, 즉 순환이 가역일 때 성립한다. 이 계를 $\Sigma$ 라고 하자.

$\Sigma$ 의 $n$ 개의 열원 이외에 임의의 정해진 $T_0$ 의 온도를 갖는 $T_0$ 열원을 추가한다. 그리고 $T_i$ 의 온도와 $T_0$ 의 온도에서 작동하는 카르노 기관 $C_i$ 를 생각하자. $C_i$ 는 $T_i$ 열원으로부터 $Q_i$ 만큼의 열을 배출한다고 하자. $T_0$ 열원으로부터 흡수하는 열 $Q_{i,\,0}$ 는  @eq-TD_relation_of_heat_and_temperature_of_carnot_engine_using_ideal_gas 로 부터 

$$
Q_{i,\,0}= \dfrac{T_0}{T_i} Q_i
$${#eq-TD_eq_for_entropy_1}

임을 안다. 이렇게 $\Sigma$ 와 $n$ 개의 카르노 기관으로 이루어진 계를 $\Sigma'$ 라고 하자.

이제 $\Sigma$ 의 한 순환과 각각의 카르노 기관의 한 사이클씩으로 이루어진 복잡한 사이클을 생각하자. $T_i$ 의 열원에서 $\Sigma$ 로 주는 열과 $C_i$ 로부터 받는 열이 $Q_i$ 로 같기 때문에 $T_i$ 에서의 순 열교환은 $0$ 이다. $T_0$ 열원이 잃는 열을 $Q_0$ 라고 하면

$$
Q_0 = \sum_{i=0}^n Q_{i,0} = T_0 \sum_{i=1}^n \dfrac{Q_i}{T_i}.
$$ {#eq-TD_eq_for_entropy_2}

$\Sigma'$ 의 한 순환에서 $T_0$ 열원으로 부터 받는 열은 $Q_{0}$ 이다. 그런데 우리는 순환에서 수행된 일은 계로부터 받는 열과 같다는 것을 안다. $\Sigma'$ 의 한 사이클에서 $S,\,C_1,\ldots,\,C_n$ 은 초기상태로 돌아 왔다. 만약 $Q_0\ge 0$ 이라면 켈밴의 열역학 제 2 법칙을 위배하므로 $Q_0\le 0$ 이다. $T_0\ge 0$ 이므로 우리는 @eq-TD_primitive_form_of_entropy 를 얻게 된다. $S$ 가 가역이라면 우리는 이 과정을 모두 역으로 돌릴 수 있고 $\sum_{i=1}Q_i /T_i \ge 0$ 이어야 한다. 따라서 $S$ 가 가역이라면

$$
\sum_{i=1}^n \dfrac{Q_i}{T_i} = 0,\qquad (\text{for reversivble system})
$$ {#eq-TD_eq_for_entropy_3}

이다. 이 식을 적분 형태로 표현하면 [$^1$ 여기서 $T$ 는 열원의 온도로 $dQ$ 만큼의 열을 시스템으로 보내며 $dQ$ 만큼의 열을 받는 시스템의 온도 $T'$ 과 같을 필요는 없다. 비가역 순환에서 $T'\le T$ 이면 $dQ \ge 0$ 이며 $T' \ge T$ 이면 $dQ \le 0$ 이다. 가역 순환에서는 항상 $T'=T$ 이다.]{.aside}


$$
\oint \dfrac{dQ}{T}\le 0,
$$ {#eq-TD_eq_for_entropy_4}

이며 가역과졍일 때는

$$
\oint\dfrac{dQ}{T}=0
$$ {#eq-TD_eq_for_entropy_5}

이다$^1$.

## 엔트로피 {#sec-TD_entropy}

### 엔트로피 

가역과정에 대한 @eq-TD_eq_for_entropy_5 로부터 우리는 시스템 $\Sigma$ 의 두 평형상태 $A,\,B$ 에 대해 $A$ 에서 $B$ 로의 모든 가역과정에 대해

$$
\int_A^B \dfrac{dQ}{T}=\text{constant}
$$ {#eq-TD_eq_for_entropy_6}

임을 알 수 있다. 우리가 임의로 어떤 기준이 되는 평형 상태 $\mathcal{O}$ 를 정한다면 $\mathcal{O}$ 에서 다른 평형상태 $A$ 까지의 가역 과정에 대해 함수 $S(A)$ 를 아래와 같이 정의 할 수 있다.

$$
\boxed{S(A) := \int_\mathcal{O}^A \dfrac{dQ}{T}.}
$${#eq-TD_eq_for_entropy_7}

은 $A$ 에 대한 함수가 된다. 우리는 이로부터 다음의 성질을 보일 수 있다.

**1.** 임의의 평형 상태 $B$ 에 대해

$$
S(B)-S(A) = \int_A^B \dfrac{dQ}{T}.
$$ {#eq-TD_eq_for_entropy_8}


**2.** 반대 경로에 대해

$$
\int_A^{\mathcal{O}}\dfrac{dQ}{T} = - \int_\mathcal{O}^A \dfrac{dQ}{T}.
$${#eq-TD_eq_for_entropy_9}

**3.** 기준 상태를 $\mathcal{O}$ 에서 $\mathcal{O}'$ 으로 변경하고 $S'(A) := \int_{\mathcal{O}'}^A dQ/T$ 로 정하면,

$$
S'(A) = S(A)-S(\mathcal{O}').
$${#eq-TD_eq_for_entropy_10}

@eq-TD_eq_for_entropy_7 와 같이 정의된 $S(A)$ 를 기준 상태 $\mathcal{O}$ 에 대한 **엔트로피(entropy)** 라고 한다.
엔트로피는 정해진 기준점에 의한 상수를 제외하면 잘 정의된다. 보통은 엔트로피의 차이가 중요하므로 상수가 중요하지는 않지만 몇몇 문제에서는 이 상수가 중요해진다. 뒤에 열역학 제 3 법칙을 다룰 때 이 상수를 고정시킬 수 있음을 보일 것이다.

### 엔트로피의 미소변화

@eq-TD_eq_for_entropy_7 과 @eq-TD_eq_for_entropy_8 로부터 미소 엔트로피 변환 $dS$ 를 다음과 같이 정의할 수 있다는 것을 알 수 있다.

$$
dS = \dfrac{dQ}{T}.
$$ {#eq-TD_eq_for_entropy_11}

이것은 열원 $T$ 로부터 $dQ$ 만큼의 미소 열을 받는 미소 가역변환에 의한 시스템의 엔트로피 변화이다. 

### 엔트로피의 부분합

복수의 부분으로 이루어진 계의 엔트로피가 각 부분의 엔트로피의 합이려면 다음 두 조건을 만족해야 한다.

&emsp;($1$) 계의 에너지가 부분의 에너지의 합이며, 

&emsp;($2$) 계가 하는 일이 각 부분의 하는 일의 합이다.

예를 들어 각각 균질의 물질로 이루어진 두 시스템 $\Sigma_1,\,\Sigma_2$ 을 생각하자. 그리고 $\Sigma$ 는 이 두 시스템의 합이라고 하자. $\Sigma$ 의 에너지가 $\Sigma_1$ 과 $\Sigma_2$ 의 에너지의 합이려면 둘 사이의 접촉면에서의 표면 에너지를 무시할 수 있어야 만 한다. 그런데 이 에너지가 무시할 수 있을만큼 작으려면 두 물질이 매우 잘 분리되지 않는 경우여야만 한다. 그렇지 않으면 표면 에너지의 크기가 무시할 만큼 작을 수 없다.

$\Sigma,\,\Sigma_1,\,\Sigma_2$ 의 에너지를 각각 $U,\,U_1,\,U_2$ 라고 하고 계가 한 일을 $W,\,W_1,\,W_2$ 라고 하며 받는 열을 $Q,\,Q_1,\,Q_2$ 라고 하자. 앞의 두 조건을 만족한다면

$$
U=U_1+U_2,\qquad W=W_1+W_2
$$

이다. 이로부터

$$
Q=U+L = (U_1+W_1) + (U_2+W_2) = Q_1+Q_2
$$

이므로 $dQ = dQ_1 + dQ_2$ 이다. 따라서 $\Sigma$ 의 기준상태 $\mathcal{O}$ 와 평형상태 $A$ 가 $\Sigma_1$ 과 $\Sigma_2$ 각각의 $\mathcal{O}_1,\,A_1$, $\mathcal{O}_2,\,A_2$ 에 상응한다면

$$
S(A)=\int_\mathcal{O}^A \dfrac{dQ}{T} = \int_{\mathcal{O}_1}^{A_1} \dfrac{dQ_1}{T} + \int_{\mathcal{O}_2}^{A_2}\dfrac{dQ_2}{T} = S_1(A_1) + S_2(A_2)
$$

이다. 

이를 이용하면 전체적으로는 비평형상태이지만 부분으로 나누었을 때 각각의 부분이 모두 평형상태 일 경우에 전체 시스템의 엔트로피를 계산 할 수 있다. 

## 엔트로피의 특성 {#sec-TD_some_further_properties_of_the_entropy}

### 비가역 과정에서의 엔트로피 변화

평형상태 $A$ 에서 $B$ 로의 가역변환에 대한 엔트로피 변화가

$$
S(B)-S(A) = \int_A^B\dfrac{dQ}{T}
$$

임을 안다. 

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-TD_entropy_difference_for_irreversible_process}

평형상태 $A$ 에서 $B$ 로의 비가역 변환에 대한 엔트로피 변화는 다음을 만족한다.

$$
S(B)-S(A) \ge \int_A^B \dfrac{dQ}{T}.
$$ {#eq-TD_entropy_difference_for_irreversible_process}

:::

</div>

::: {.proof}

$A$ 에서 $B$ 로의 가역 과정 $\Gamma_R$ 와 비가역 과졍 $\Gamma_I$ 를 생각하자. 비가역 과정을 통해 $A\to B$ 변환을 수행한 후 가역 과정을 통해 $B\to A$ 로 변환한 경로를 $\Gamma_I-\Gamma_R$ 로 표기하면 이 경로는 순환이므로 @eq-TD_eq_for_entropy_4 로부터

$$
0 \ge \int_{\Gamma_I - \Gamma_R} \dfrac{dQ}{dT} = \int_{\Gamma_I}\dfrac{dQ}{T} - \int_{\Gamma_R} \dfrac{dQ}{T} =  \int_{\Gamma_I}\dfrac{dQ}{T} - (S(B)-S(A)).\quad \square
$$

:::

### 고립계에서의 엔트로피 변화

시스템이 고립계라고 하자. 그렇다면 $dQ=0$ 이며 @eq-TD_entropy_difference_for_irreversible_process 로 부터

$$
S(B) \ge S(A)
$$ {#eq-TD_entropy_for_isolated_system}

이다. 즉 **고립계에서 일어나는 상태 변화에서 최종 상태의 엔트로피는 초기 상태의 엔트로피보다 항상 크거나 같다.** 또한 상태 변화가 가역이면 엔트로피는 동일하다. 또한 이로부터 **고립계에서 가장 안정된 상태는 최대 엔트로피 상태** 라는 결론을 내릴 수 있다. 여기에 대한 몇가지 예를 들어 보자.


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-TD_entropy_change_in_isolated_system_1}

#### 열교환과 엔트로피

각각 온도가 $T_1,\,T_2$ 인 계 $\Sigma_1,\,\Sigma_2$ 가 열 접촉을 하고 있다고 하자. $T_2>T_1$ 이며 $\Sigma_2$ 으로 부터 $\Sigma_1$ 로 $Q$ 만큼의 열이 전달되었다면 엔트로피 변화는

$$
\dfrac{Q}{T_1}-\dfrac{Q}{T_2} >0
$$

이다.

:::

</div></br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-TD_entropy_change_in_isolated_system_2}

#### 마찰과 엔트로피

마찰에 의해 열이 발생할 경우 이는 비가역 과정이다. 마찰에 의해 열을 받는 쪽에서는 엔트로피가 증가한다. 열은 계의 다른 부분이 아닌 일로부터 왔으므로 증가한 다른 엔트로피는 계의 다른 부분의 엔트로피 감소로 보상되지 않는다. 즉 계의 엔트로피는 증가했다.

:::

</div>

### 동력학적 엔트로피

우리는 이미 계의 동역학적 상태와 열역학적 상태를 구분하여 이야기했었다. 동역학적 상태를 정의하기 위해서는 계를 이루는 모든 분자들의 위치와 운동에 대해 알아야 한다. 그러나 열역학적 상태는 소수의 변수-온도, 압력 등등-만으로 정의 할 수 있다. 따라서 하나의 열역학적 상태에 상응하는 다수의 동역학적 상태가 존재 할 수 있다. 통계역학에서는 정해진 열역학적 상태에 상응하는 동역학적 상태의 개수 $\Omega$ 를 부여하는 기준이 존재한다. 그렇다면 주어진 열역학적 상태에 존재할 확률은 $\Omega$ 를 모든 가능한 동역학적 상태의 개수로 나눈 값이 될 것이다.

우리는 이제부터 고립계에서 자발적 변환(spontaenous transformation) 은 확률이 더 높은 상태로 일어난다고 가정한다. 그렇다면 계의 가장 안정된 상태는 계에 주어진 에너지에 맞는 상태 가운데 가장 확률이 높은 상태가 된다. 볼츠만은 이로부터 계의 엔트로피가 다음과 같이 정의될 수 있다는 것을 증명했다. 

$$
\boxed{S := k_B \ln \Omega.}
$$ {#eq-TD_definition_of_dynamical_entropy}

여기서 $k_B$ 는 기체 상수 $R$ 을 아보가드로 수 $N_A$ 로 나눈 수로 **볼츠만 상수 (Boltznamn constant)** 라고 한다.

@eq-TD_definition_of_dynamical_entropy 를 증명하지 않아도 $\Omega$ 와 $S$ 사이의 관계로부터 엔트로피가 $\ln \Omega$ 에 비례한다는 것을 증명 할 수 있다.

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-TD_dynamical_entropy_and_number_of_states}

#### 동역학적 엔트로피

동역학적 엔트로피가 동역학적 상태의 개수의 함수라고 하자. 즉 $S=f(\Omega)$ 인 관계가 성립한다고 하자. 두 시스템 $\Sigma_1,\,\Sigma_2$ 의 엔트로피 $S_1,\,S_2$ 와 상태의 개수 $\Omega_1,\,\Omega_2$ 를 생각하자. 그렇다면

$$
S_1 = f(\Omega_1),\qquad S_2 = f(\Omega_2)
$$

이다. 두 시스템의 엔트로피의 합 $S=S_1+S_2$ 이며 상태의 개수는 $\Omega = \Omega_1\Omega_2$ 이다. 따라서

$$
f(\Omega_1 \Omega_2) = f(\Omega_1) + f(\Omega_2)
$$

을 만족한다. 우리는 이것을 만족하는 미분가능한 함수가 상수 $k,\,C$ 에 대해 $f(x) = k\cdot \ln +C$ 임을 보일 수 있다. 엔트로피에 더해지는 상수에 대해 우리가 임의로 선택 할 수 있으므로 $C=0$ 으로 놓으면 우리는 $S=k\ln \Omega$ 를 얻는다.
 

:::

</div>

## 상태가 $(V,p)$ 도상에 표현될 수 있는 시스템의 엔트로피 {#sec-TD_the-entropy_of_systems_whose_states_can_be_represented_on_a_Vp_diagram}

상태가 $p,\,V,\,T$ 가운데 두개로 정의 될 수 있는 시스템을 생각하자. 우선 $T,\,V$ 가 독립변수라면

$$
dQ = dU + dW = \left(\dfrac{\partial U}{\partial T}\right)_V dT + \left[\left(\dfrac{\partial U}{\partial V}\right)_T + p\right] dV
$$ {#eq-TD_fermi_79}

이며 이로부터

$$
dS = \dfrac{dQ}{T} =  \dfrac{1}{T}\left(\dfrac{\partial U}{\partial T}\right)_V dT + \dfrac{1}{T} \left[\left(\dfrac{\partial U}{\partial V}\right)_T + p\right] dV
$$

이다. 위의 $dQ$ 와 $dS$ 는 큰 차이가 있는데 $dQ$ 는 경로 의존적이며 $dS$ 는 경로 독립적이라는 것이다. $dS$ 는 전미분이며 즉 $S$ 는 $T,\,P$ 의 함수이다. 

$$
S=S(T,\,V).
$$ {#eq-TD_fermi_81}

반면 @eq-TD_fermi_79 의 $dQ$ 는 전미분이 아닌데 이는 열역학 제 1 법칙으로 부터 쉽게 보일 수 있다. 