project:
  type: book
  output-dir : docs

book:
  title: "고전 역학과 전자기학"
  author: "Norah Jones"
  date: "2/11/2024"
  page-navigation: true

  
  chapters:
    - index.qmd
    - part: src/ClassicalMechanics/00_index.qmd
      chapters:
      - src/ClassicalMechanics/01_basic_principles.qmd
      - src/ClassicalMechanics/02_variational_principle.qmd
      - src/ClassicalMechanics/03_hamilton_dynamics.qmd
      - src/ClassicalMechanics/04_canonical_transform.qmd
      - src/ClassicalMechanics/11_one_body_problems.qmd
      - src/ClassicalMechanics/12_two_or_three_bodies_problems.qmd

      - src/ClassicalMechanics/A_proofs.qmd

      - src/ClassicalMechanics/P1_problems01.qmd    
    - part: src/Mechanics_and_Symmetry/00_index.qmd
      chapters:
      - src/Mechanics_and_Symmetry/01_experimental_facts.qmd
      - src/Mechanics_and_Symmetry/02_equations_of_motion.qmd

    - part: src/Electromagnetism/00_index.qmd
      chapters:
      - src/Electromagnetism/01_mathematics.qmd
      - src/Electromagnetism/electrostatics_1.qmd
      - src/Electromagnetism/electrostatics_2.qmd
      - src/Electromagnetism/electrostatics_3.qmd
    
    - part: src/Electrodynamics/00_index.qmd
      chapters:
      - src/Electrodynamics/01_introduction.qmd
      - src/Electrodynamics/02_electrostatics.qmd
      
    - part: src/Relativity/00_index.qmd
      chapters:
      - src/Relativity/01_introduction_to_special_relativity.qmd
      - src/Relativity/02_introduction_to_classical_field.qmd
    
    # - part: src/ClassicalFieldTheory/00_index.qmd
    #   chapters:
    #   - src/ClassicalFieldTheory/01_principle_of_relativity.qmd

    # - part: src/Lanczos/Lanczos.qmd
    #   chapters:
    #   - src/Lanczos/00_01.qmd
    #   - src/Lanczos/01_01.qmd
    #   - src/Lanczos/02_01.qmd
    - part: src/topics/Topics.qmd
      chapters:
        - src/topics/mathematical.qmd
    # - part: src/images/images.qmd
    #   chapters:
    #   - src/images/images_classical_mechanics_01.qmd
    #   - src/images/images_classical_mechanics_02.qmd
    #   - src/images/images_relativity_01.qmd
    #   - src/images/images_test.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    title-block-banner: true
    # include-in-header: 
    #   - html-hacks/load-font-awesome.html
    #   - html-hacks/load-xkcd-font.html
    # resources: web-resources/**
    # https://quarto.org/src/output-formats/html-themes.html#overview
    # theme: darkly
    theme: cosmo
    fontsize: 0.9em
    toc: true
    collapse: true
    # css: styles.css
    number-sections: true

    code-fold: true
    code-summary: "Show the code"
  
    html-math-method: mathjax




