---
title: "그림 : 고전역학 #2"
number-sections: true
number-depth: 2
crossref:
  chapters: true
---

```{r, engine = 'tikz'}
#| label: fig-refrence_frame_in_relativity
#| code-fold: true
#| echo: fenced
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "두 좌표계"

\usetikzlibrary {3d} 
\begin{tikzpicture}[z={(10:10mm)},x={(-45:5mm)}]
  \def\wave{
    \draw[fill,thick,fill opacity=.2]
     (0,0) sin (1,1) cos (2,0) sin (3,-1) cos (4,0)
           sin (5,1) cos (6,0) sin (7,-1) cos (8,0)
           sin (9,1) cos (10,0)sin (11,-1)cos (12,0);
    \foreach \shift in {0,4,8}
    {
      \begin{scope}[xshift=\shift cm,thin]
        \draw (.5,0)  -- (0.5,0 |- 45:1cm);
        \draw (1,0)   -- (1,1);
        \draw (1.5,0) -- (1.5,0 |- 45:1cm);
        \draw (2.5,0) -- (2.5,0 |- -45:1cm);
        \draw (3,0)   -- (3,-1);
        \draw (3.5,0) -- (3.5,0 |- -45:1cm);
      \end{scope}
    }
  }
  \begin{scope}[canvas is zy plane at x=0,fill=blue]
    \wave
    \node at (6,-1.5) [transform shape] {magnetic field};
  \end{scope}
  \begin{scope}[canvas is zx plane at y=0,fill=red]
    \draw[help lines] (0,-2) grid (12,2);
    \wave
    \node at (6,1.5) [rotate=180,xscale=-1,transform shape] {electric field};
  \end{scope}
\end{tikzpicture}
```

</br>





```{r, engine = 'tikz'}
#| label: fig-cross_section_2
#| code-fold: true
#| echo: fenced
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "두 관성계에서의 자발적 붕괘"
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}
\begin{tikzpicture}[line cap=round, scale = 2]
%\begin{scope}
%  \clip (0,0) circle (1);
%  \fill[gray!20] (-0.625,0) circle (1.5);
%  \fill[gray!0] (-0.945,0) circle (1.7);
%\end{scope}

\draw (0,0) circle (1cm);

\draw[white, fill=gray!20] (0.5300, 0) ellipse (0.2 and 0.848); 
\draw[white, fill=gray!0] (0.7001, 0) ellipse (0.2 and 0.7133); 

\draw (0,0) circle (1cm);
\end{tikzpicture}
```


```{r, engine = 'tikz'}
#| label: fig-cross_section_3
#| code-fold: true
#| echo: fenced
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "두 관성계에서의 자발적 붕괘"
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}
\begin{tikzpicture}[line cap=round, scale = 2]

\draw[thick,  -{Stealth[length=2mm]}] (-2, 0) -- (3, 0);
\draw[thick,  -{Stealth[length=2mm]}] (0, -2) -- (0, 2);


\def\e{2.406};
\def\a{0.1};
\def\s{sqrt(\e*\e-1)};

\begin{scope}[rotate=0]
\coordinate (A) at (-1, 0);
\draw[teal, thick] plot[variable=\t,domain=-2:2, samples=100, smooth,thick] ({\a * (cosh(\t) + \e)}, {\a * sqrt(\e*\e-1)*sinh(\t)});


\draw (0,0) circle (1);
\draw (\a * \e, -2) -- (\a * \e , 2);

\draw[red, dashed] (\a * \e, 0) -- ({\a * \e + 0.4},  { 0.4 * sqrt(\e*\e-1) });
\draw[red, dashed] (\a * \e, 0) -- ({\a * \e + 0.4},  { -0.4 * sqrt(\e*\e-1) });
\end{scope}

\begin{scope}[rotate=114.55]
\coordinate (A) at (-1, 0);
\draw[teal, thick] plot[variable=\t,domain=-2:2, samples=100, smooth,thick] ({\a * (cosh(\t) + \e)}, {\a * sqrt(\e*\e-1)*sinh(\t)});

\draw[red, dashed] (\a * \e, 0) -- ({\a * \e + 0.4},  { 0.4 * sqrt(\e*\e-1) });
\draw[red, dashed] (\a * \e, 0) -- ({\a * \e + 0.4},  { -0.4 * sqrt(\e*\e-1) });
\end{scope}
\end{tikzpicture}
```




