---
title: "그림들-테스트"
number-sections: true
number-depth: 2
crossref:
  chapters: true
---



```{r, engine = 'tikz'}
#| label: fig-relativity_compton_scattering_1
#| code-fold: true
#| echo: fenced
#| fig-width: 4
#| output: asis
#| fig-align: center
#| fig-cap: "컴프톤 산란"
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}
\begin{tikzpicture}[line cap=round]

\filldraw[] (-4, 0) circle (0.05) node [above] {$\textrm{photon}$};
\draw[thick, -{Stealth[length=2mm]}] (-4, 0) -- (-2, 0);
\node[below] at (-3, 0) {$h\nu/c$};
\draw[dashed] (-2, 0) -- (3, 0);

\shade[ball color=gray!40]   (0,0) circle (0.2) node [yshift=3ex] {$e^-$};

\draw[dashed] (0, 0) -- (1.2, 1);
\filldraw[] (1.2, 1) circle (0.05) ;
\draw[thick, -{Stealth[length=2mm]}] (1.2, 1) -- (2.4, 2) node [xshift=-5ex] {$h\nu'/c$}; %'
\draw[-{Stealth[length=2mm]}] (1, 0) arc (0:39.8:1);
\node at (1.2, 0.4) {$\theta$};
\draw[dashed] (0, 0) -- (1.2, -1.3);
\draw[thick, -{Stealth[length=2mm]}] (1.2, -1.3) -- (1.8, -1.95) node[xshift=-5ex] {$p_e$};
\shade[ball color=gray!80]   (1.2, -1.3)   circle (0.2);

\end{tikzpicture}
```

</br>

```{r, engine = 'tikz'}
#| label: fig-relativity_uniform_acceleration_1
#| code-fold: true
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "상대론적 등가속도 운동"
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}
\begin{tikzpicture}[line cap=round, scale = 2]

\draw [thick, -{Stealth[length=2mm]}] (-0.1, 0) -- (2, 0) node [right, scale=0.7] {$t$};
\draw [thick, -{Stealth[length=2mm]}] (0, -0.1) -- (0, 1.5) node [left, scale=0.7] {$v(t)$};


\def\a{2.0};
\def\b{1.0};
\draw[dashed] (0, 1) -- (2, 1);
\draw[very thick, teal] plot[variable=\t,domain=0:2, samples=100, smooth,thick] ({\t}, {\a*\t/sqrt(1+(\a*\t)^2)}) node[below left, scale=0.7, black] {rel.};
\draw[very thick, dashed, red] (0, 0) -- (0.6, 1.2) node[above, scale=0.7, black] {non-rel.};
\node [left, scale=0.7] at (0, 1) {$c$}; 


\begin{scope}[shift={(2.5,0)}]
\draw [thick, -{Stealth[length=2mm]}] (-0.1, 0) -- (1.5, 0) node [right, scale=0.7] {$x$};
\draw [thick, -{Stealth[length=2mm]}] (0, -0.1) -- (0, 1.5) node [left, scale=0.7] {$ct$};

\draw [dashed] (0, 0) -- (1.5, 1.5) node[right, scale=0.7] {$x=ct$};

\draw[very thick, teal] plot[variable=\t,domain=0:1.0, samples=100, smooth,thick] ({\t}, {sqrt((\t+1/\a)^2 -1/(\a^2))}) node [above, scale=0.7, black] {rel.};
\draw[very thick, dashed, red] plot[variable=\t,domain=0.0:1.5, samples=100, smooth,thick] ({\t}, {sqrt(2*\t/\a)}) node [right, scale=0.7, black] {non-rel.};

\end{scope}
\end{tikzpicture}
```

</br>

```{r, engine = 'tikz'}
#| label: fig-relativity_doppler_effect_1
#| code-fold: true
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "도플러 효과"

\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}
\begin{tikzpicture}[line cap=round, scale = 2]


% 관찰자가 움직일때의 도플러 효과
\draw[fill=none, blue](0,0) circle (0.4);
\draw[fill=none, blue](0,0) circle (0.60);
\draw[fill=none, blue](0,0) circle (0.80);
\draw[fill=none, blue](0,0) circle (1);

\filldraw[] (0, 0) circle (0.03) node[below, scale=0.7] {$S$};
\filldraw[] (1, 0) circle (0.03) node[right, scale=0.7] {$O$};
\draw[thick, -{Stealth[length=2mm]}] (1, 0) -- (0.7, 0);

\node [below, scale = 0.7] at (0, -1.1) {$(a)$}; 

\begin{scope}[shift={(3,0)}]
\draw[fill=none, blue](0,0) circle (1);
\draw[fill=none, blue](0.1,0) circle (0.8);
\draw[fill=none, blue](0.2,0) circle (0.60);
\draw[fill=none, blue](0.3,0) circle (0.4);

\filldraw[] (0, 0) circle (0.03) node[below, scale=0.7] {$S$};
\filldraw[] (1, 0) circle (0.03) node[right, scale=0.7] {$O$};
\draw[thick, -{Stealth[length=2mm]}] (0, 0) -- (0.3, 0);
\node [below, scale = 0.7] at (0, -1.1) {$(b)$}; 

\end{scope}


\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-relativity_galactic_jet
#| code-fold: true
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "도플러 효과"

\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}
\begin{tikzpicture}[line cap=round, scale = 2]


\draw [gray!20, fill=gray!20] (0,0) ellipse (2 and 1);
\node[right, scale=0.8] at (0, 0) {$O$};
\node [black, scale=1] at (0, 0.5) {Galaxy};
\draw [very thick, blue, -{Stealth[length=2mm]}] (0, 0) -- (-3, -0.5) node[above, scale=1] {Jet};
\draw [] (0, -3) -- (0, -2.05);
\draw [] (0, -2) -- (0, -0);

\draw (-0.1,-1.5) .. controls + (0,-0.1) and + (0,0.1) ..  ++ (0.2, 0)    ++ (0,-0.2);
\draw (-0.1,-1.55) .. controls + (0,-0.1) and + (0,0.1) ..  ++ (0.2, 0)    ++ (0,-0.2);

\draw[-{Stealth[length=2mm]}] (0, -0.3) arc (270:190:0.3);
\node [] at (-0.3, -0.3) {$\theta$}; 

\begin{scope}[shift={(4,0)}]



\end{scope}

\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-yebin_1
#| code-fold: true
#| fig-width: 4
#| output: asis
#| fig-align: center
#| fig-cap: "도플러 효과"

\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}
\begin{tikzpicture}[line cap=round, scale = 2]


\draw [thick] (0, 0) -- (0, 1) -- (-3, 0) --cycle;
\draw [] (-0.2, 0) -- (-0.2, 0.2) -- (0, 0.2);
\node [right] at (0, 0) {$C$};
\node [right] at (0, 1) {$A$};
\node [left] at (-3, 0) {$B$};

\end{tikzpicture}
```







