---
title: "상대성 원리"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

## 상호작용의 전파 속도

### 배경 지식 {#sec-CFT_background_knowledge}

- **기준틀** (*system of reference*) 
  - 좌표계 (system of coordinate) : 공간상의 입자의 위치 
  - 좌표계의 고유한 시계


- **관성좌표계** (*inertial frame of reference*) : 외부로부터 힘을 받지 않는 물체는 등속으로 운동을 하는 기준틀.

- 두 기준틀이 서로 등속 운동을 할 때 한 기준틀이 관성좌표계이면 다른 좌표계 역시 관성좌표계이다.

- 상대성 원리 (*principle of relativity*): 자연법칙은 모든 관성좌표계에서 동일하다. 즉 운동방정식은 모든 관성좌표계에서 동일하다.
 
</br>

### 빛의 속도 {#sec-CFT_speed_of_light}

- 고전역학에서 물질의 입자간 상호작용은 입자의 위치의 함수인 포텐셜 에너지로 기술된다. 이것은 상호작용의 전달 속도가 무한대임을 의미한다. 즉 상호작용하는 입자의 위치가 변경될 경우 그 영향은 즉각 반영된다. 그러나 실험은 이런 즉각적인 상호작용은 자연에서 존재하지 않음을 보였다.
- 어느 정도 떨어진 두 입자에서 한 입자에 변화가 있을 때 다른 입자가 그 영향을 느끼는 시간차와 두 입자 사이의 거리를 통해 상호작용의 전달 속도(*velocity of propagation of the interaction*)를 측정 할 수 있다.
- 엄밀하게 말하면 앞의 속도는 상호작용의 최대전달속도(*maximum velocity of propagation of interaction*) 이다. 
- 물체의 속도가 이 속도보다 크다면 상호작용이 전달되지 않는다. 따라서 물체의 속도가 이 상호작용의 최대전달속도보다 클 수 없다.
- 한 입자에서 다른 입자로의 상호작용의 전달을 **신호** (*signal*) 라고 한다. 상호작용의 전달속도를 신호 속도(*signal velocity*) 라고 한다.
- 상대성 원리는 모든 상호작용의 전달속도는 관성좌표계에서 일정함을 가정한다. 즉 이 신호 전달속도는 우주상수이다. 상호작용의 전달속도는 빛의 속도 $c$ 이다.

$$
c=2.99792458 \times 10^8 \text{ m}/\text{sec}
$$


</br>

### 상대성 이론 {#sec-CFT_einstein_principle_of_relativity}

- 아인슈타인의 상대성 원리는 두 원리의 결합이다.
  1. 상대성 원리.
  2. 상호작용의 전달속도의 보편성.

- 뉴턴 역학, 즉 고전역학은 상대성 원리의 $c\to \infty$ 극한이다.

</br>

#### **고전역학에서의 시간과 공간 그리고 동시성**

공간상의 거리는 고전역학에서도 상대적이다. 한 관성좌표계에서 정지해 있는 물체는 다른 관성좌표계에서는 일정한 속도로 이동한다. 그러나 시간은 고전역학에서 절대적이다. 모든 관성좌표계가 동일한 시계를 공유한다. 즉 한 기준틀에서 같은 시간에 일어난 두 사건은 다른 기준틀에서도 동시에 일어난다. 또한 동시에 일어나지 않은 두 사건의 시간간격은 모든 기준틀에서 동일하다.


그러나 이것은 상대성 이론에 어긋나는데 한 좌표계에서의 빛의 속도는 이 좌표계에 대해 $v$ 의 속도로 움직이는 좌표계에서 $c+v >c$ 가 될 수 있기 때문이다. 

마이켈슨의 실험에서 빛의 속도는 방향과 무관하게 동일하다는 것을 보였다. 그러나 고전역학에 따르면 빛의 속도는 지구의 진행방향에서 가장 작아야 한다.

두 관성좌표계 $\Sigma,\,\Sigma'$ 을 생각하자. $\Sigma$ 의 좌표축 $X,\,Y,\,Z$ 와 $\Sigma'$ 의 좌표축 $X',\,Y',\,Z'$ 을 생각하자. $\Sigma'$ 은 $\Sigma$ 에 대해 $X(X')$ 방향으로 움직인다고 하자. $X'$ 축상의 점 $A$ 에 대해 같은 거리, 반대 방향으로 역시 $X'$ 축 상에 $B,\,C$ 를 놓자. $A$ 에서 동시에 $B,\,C$ 방향으로 빛을 쏜다면 $\Sigma'$ 에서는 동시에 $B,\,C$ 에 도달한다. 그러나 밫의 속도가 일정하다는 것을 가정하면 $\Sigma$ 기준틀에서는 서로 다른 시간에 도착한다. 


</br>

## 4차원 시공간과 시간 간격 {#sec-CFT_interval}

### 4차원 시공간, 사건, 세계선 {#sec-CFT_spacetime_event_worldline}

3차원 공간과 1차원의 시간을 합쳐 4차원 시공간을 생각 할 수 있다. 물리적으로 어떤 **사건**(*event*) 가 벌여졌을 때 이 사건의 공간과 시간상의 좌표는 이 4차원 시공간상의 한 점이다. 이 점을 **세계점**(*world point*) 라고 한다. 입자의 운동은 이 4차원 시공간상에서 궤적을 갖는데 이 궤적을 **세계선**(*world line*) 이라고 한다. 기준틀에서 등속 운동을 하는 입자의 세계선은 직선이다.


</br>




