<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; I-3 : 양자역학과 열역학 입문 – 고전물리학</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../src/Feynman/vol2/vol2_1.html" rel="next">
<link href="../../../src/Feynman/vol1/vol1_2.html" rel="prev">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-3e2728906df7980cb53b491a61d13d7e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../src/Feynman/00_index.html">파인만의 물리학 강의</a></li><li class="breadcrumb-item"><a href="../../../src/Feynman/vol1/vol1_3.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><span class="math inline">\(I\)</span>-3 : 양자역학과 열역학 입문</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../src/Feynman/00_index.html">파인만의 물리학 강의</a></li><li class="breadcrumb-item"><a href="../../../src/Feynman/vol1/vol1_3.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><span class="math inline">\(I\)</span>-3 : 양자역학과 열역학 입문</span></a></li></ol></nav>
      <h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><span class="math inline">\(I\)</span>-3 : 양자역학과 열역학 입문</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">고전물리학</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../src/Feynman/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">파인만의 물리학 강의</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Feynman/vol1/vol1_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title"><span class="math inline">\(I\)</span>-1 : 고전역학</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Feynman/vol1/vol1_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><span class="math inline">\(I\)</span>-2: 특수상대성이론과 광학</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Feynman/vol1/vol1_3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><span class="math inline">\(I\)</span>-3 : 양자역학과 열역학 입문</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Feynman/vol2/vol2_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><span class="math inline">\(II\)</span>-1 : 정전기와 정자기</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../src/ClassicalMechanics/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">고전역학</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ClassicalMechanics/01_basic_principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">뉴튼역학의 기본 원리와 달랑베르 원리</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ClassicalMechanics/02_variational_principle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">변분 원리와 라그랑쥬 방정식</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ClassicalMechanics/03_hamilton_dynamics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">해밀턴 동역학</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ClassicalMechanics/04_canonical_transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">정준 변환</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ClassicalMechanics/11_one_body_problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">고전역학의 1체 문제</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ClassicalMechanics/12_two_or_three_bodies_problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">고전역학의 다체 문제 - 충돌과 산란</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ClassicalMechanics/13_small_oscillations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">작은 진동</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ClassicalMechanics/A_proofs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">증명들</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ClassicalMechanics/P1_problems01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">문제 모음</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../src/Mechanics_and_Symmetry/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">고전역학과 대칭</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Mechanics_and_Symmetry/01_experimental_facts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">실험적 사실</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Mechanics_and_Symmetry/02_equations_of_motion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">운동방정식</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../src/Electrodynamics/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">전기자기학</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Electrodynamics/01_introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">들어가며</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Electrodynamics/02_1_electrostatics1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">정전기 I</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Electrodynamics/02_2_electrostatics2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">정전기 II</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Electrodynamics/03_magnetostatics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">정자기</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Electrodynamics/04_electrodynamics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">전기동력학</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Electrodynamics/A1_mathematics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">부록 A. 수학</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Electrodynamics/A2_waves.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">부록 B. 파동</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../src/Relativity/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">상대론</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Relativity/01_introduction_to_special_relativity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">특수 상대론의 기초</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/Relativity/02_introduction_to_classical_field.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">고전 장론 입문</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../src/ThermalPhysics/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">열역학</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ThermalPhysics/01_thermodynamic_systems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">열역학 계 와 열역학 법칙</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ThermalPhysics/02_entropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">엔트로피와 열역학적 포텐셜</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/ThermalPhysics/0A_mathematics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Appendix</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../src/topics/Topics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">별도의 주제들</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../src/topics/mathematical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">수학적 자료</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#sec-FLP_1_37" id="toc-sec-FLP_1_37" class="nav-link active" data-scroll-target="#sec-FLP_1_37">I.37 Quantum Behavior</a>
  <ul class="collapse">
  <li><a href="#sec-FLP_1_37_1" id="toc-sec-FLP_1_37_1" class="nav-link" data-scroll-target="#sec-FLP_1_37_1">I.37-1 Atomic mechanics</a></li>
  <li><a href="#sec-FLP_1_37_2" id="toc-sec-FLP_1_37_2" class="nav-link" data-scroll-target="#sec-FLP_1_37_2">I.37-2 총알 실험</a></li>
  <li><a href="#sec-FLP_1_37_3" id="toc-sec-FLP_1_37_3" class="nav-link" data-scroll-target="#sec-FLP_1_37_3">I.37-2 파동 실험</a></li>
  <li><a href="#sec-FLP_1_37_4" id="toc-sec-FLP_1_37_4" class="nav-link" data-scroll-target="#sec-FLP_1_37_4">I.37-4 전자 실험</a></li>
  <li><a href="#sec-FLP_1_37_5" id="toc-sec-FLP_1_37_5" class="nav-link" data-scroll-target="#sec-FLP_1_37_5">I.37-5 전자 파동의 간섭</a></li>
  <li><a href="#sec-FLP_1_37_6" id="toc-sec-FLP_1_37_6" class="nav-link" data-scroll-target="#sec-FLP_1_37_6">I.37-6 전자 관찰</a></li>
  <li><a href="#sec-FLP_1_37_7" id="toc-sec-FLP_1_37_7" class="nav-link" data-scroll-target="#sec-FLP_1_37_7">I.39-7 양자역학의 첫번째 원리</a></li>
  <li><a href="#sec-FLP_1_37_8" id="toc-sec-FLP_1_37_8" class="nav-link" data-scroll-target="#sec-FLP_1_37_8">I.37-8 불확정성의 원리</a></li>
  </ul></li>
  <li><a href="#sec-FLP_1_38" id="toc-sec-FLP_1_38" class="nav-link" data-scroll-target="#sec-FLP_1_38">I.38 입자 관점과 파동 관점의 관계</a>
  <ul class="collapse">
  <li><a href="#sec-FLP_1_38_1" id="toc-sec-FLP_1_38_1" class="nav-link" data-scroll-target="#sec-FLP_1_38_1">I.38-1 확률파의 진폭</a></li>
  <li><a href="#sec-FLP_1_38_2" id="toc-sec-FLP_1_38_2" class="nav-link" data-scroll-target="#sec-FLP_1_38_2">I.38-2 위치와 운동량의 측정</a></li>
  <li><a href="#sec-FLP_1_28_3" id="toc-sec-FLP_1_28_3" class="nav-link" data-scroll-target="#sec-FLP_1_28_3">I.28-3 결정 회절</a></li>
  <li><a href="#sec-FLP_1_38_4" id="toc-sec-FLP_1_38_4" class="nav-link" data-scroll-target="#sec-FLP_1_38_4">I.38-4 원자의 크기</a></li>
  <li><a href="#sec-FLP_1_38_5" id="toc-sec-FLP_1_38_5" class="nav-link" data-scroll-target="#sec-FLP_1_38_5">I.38-5 에너지 준위</a></li>
  <li><a href="#sec-FLP_1_38_6" id="toc-sec-FLP_1_38_6" class="nav-link" data-scroll-target="#sec-FLP_1_38_6">I.38-6 철학적 함의</a></li>
  </ul></li>
  <li><a href="#sec-FLP_1_39" id="toc-sec-FLP_1_39" class="nav-link" data-scroll-target="#sec-FLP_1_39">I.39. 기체의 동역학</a>
  <ul class="collapse">
  <li><a href="#sec-FLP_1_39_1" id="toc-sec-FLP_1_39_1" class="nav-link" data-scroll-target="#sec-FLP_1_39_1">I.39-1 물질의 성질</a></li>
  <li><a href="#sec-FLP_1_39_2" id="toc-sec-FLP_1_39_2" class="nav-link" data-scroll-target="#sec-FLP_1_39_2">I.39-2 기체의 압력</a></li>
  <li><a href="#sec-FLP_1_39_3" id="toc-sec-FLP_1_39_3" class="nav-link" data-scroll-target="#sec-FLP_1_39_3">I.39-3 복사의 압축</a></li>
  <li><a href="#sec-FLP_1_39_4" id="toc-sec-FLP_1_39_4" class="nav-link" data-scroll-target="#sec-FLP_1_39_4">I.39-4 온도와 운동에너지</a></li>
  <li><a href="#sec-FLP_1_39_5" id="toc-sec-FLP_1_39_5" class="nav-link" data-scroll-target="#sec-FLP_1_39_5">I.39-5 이상기체법칙</a></li>
  </ul></li>
  <li><a href="#i.40.-통계역학의-원리" id="toc-i.40.-통계역학의-원리" class="nav-link" data-scroll-target="#i.40.-통계역학의-원리">I.40. 통계역학의 원리</a>
  <ul class="collapse">
  <li><a href="#sec-FLP_1_40_1" id="toc-sec-FLP_1_40_1" class="nav-link" data-scroll-target="#sec-FLP_1_40_1">I.40.1 지수적 대기</a></li>
  <li><a href="#sec-FLP_1_40_2" id="toc-sec-FLP_1_40_2" class="nav-link" data-scroll-target="#sec-FLP_1_40_2">I.40-2 볼츠만 법칙</a></li>
  <li><a href="#sec-FLP_1_40_3" id="toc-sec-FLP_1_40_3" class="nav-link" data-scroll-target="#sec-FLP_1_40_3">I.40-3 액체의 증발</a></li>
  <li><a href="#sec-FLP_1_40_4" id="toc-sec-FLP_1_40_4" class="nav-link" data-scroll-target="#sec-FLP_1_40_4">I.40-4 분자 속력의 분포</a></li>
  <li><a href="#sec-FLP_1_40_5" id="toc-sec-FLP_1_40_5" class="nav-link" data-scroll-target="#sec-FLP_1_40_5">I.40-5 기체의 비열</a></li>
  <li><a href="#xec-FLP_1_40_6" id="toc-xec-FLP_1_40_6" class="nav-link" data-scroll-target="#xec-FLP_1_40_6">I.40-6 고전역학의 실패</a></li>
  </ul></li>
  <li><a href="#sec-FLP_1_41" id="toc-sec-FLP_1_41" class="nav-link" data-scroll-target="#sec-FLP_1_41">I.41. 브라운 운동</a>
  <ul class="collapse">
  <li><a href="#sec-FLP_1_41-1" id="toc-sec-FLP_1_41-1" class="nav-link" data-scroll-target="#sec-FLP_1_41-1">I.41-1 에너지의 등분배</a></li>
  <li><a href="#eq-FLP_1_41_2" id="toc-eq-FLP_1_41_2" class="nav-link" data-scroll-target="#eq-FLP_1_41_2">I.41-2 복사의 열평형</a></li>
  <li><a href="#eq-FLP_1_41_3" id="toc-eq-FLP_1_41_3" class="nav-link" data-scroll-target="#eq-FLP_1_41_3">I.41-3 양자 진동자의 등분배</a></li>
  <li><a href="#sec-FLP_1_41_4" id="toc-sec-FLP_1_41_4" class="nav-link" data-scroll-target="#sec-FLP_1_41_4">I.41-4 마구 걷기</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">





<div class="hidden">
<p>% %</p>
%
<p><span class="math display">\[
\DeclarePairedDelimiters{\set}{\{}{\}}
\DeclareMathOperator*{\argmax}{argmax}
\]</span></p>
</div>
<section id="sec-FLP_1_37" class="level2">
<h2 class="anchored" data-anchor-id="sec-FLP_1_37">I.37 Quantum Behavior</h2>
<section id="sec-FLP_1_37_1" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_37_1">I.37-1 Atomic mechanics</h3>
<p><br></p>
</section>
<section id="sec-FLP_1_37_2" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_37_2">I.37-2 총알 실험</h3>
<div id="fig-FLP_1_37_1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_37_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_37/fig_1_37_1.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_37_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.1: 파인만 물리학 강의 I. 그림 37-1. 총알 간섭 실험
</figcaption>
</figure>
</div>
<p>위의 그림과 같이 설정된 기관총 실험을 생각하자. 기관총은 성능이 훌륭하지 못해 고정된 각으로 발사하지 못하고 임의로 퍼져서 발사한다고 생각하자. 우리가 관심있는 것은 총알이 1번 혹은 2번 구멍을 거쳐 backstop 의 중심으로부터 거리 <span class="math inline">\(x\)</span> 에 박힐 확률이다. 이를 <span class="math inline">\(P_{12}(x)\)</span> 로 표기하자.</p>
<ul>
<li><p>확률을 도입했다. 기관총에서 각각의 총알이 정확히 어떤 방향으로 가는지 모르기 때문이다. 이 확률은 특정 시간 범위 안에 <span class="math inline">\(x\)</span> 와 <span class="math inline">\(x+dx\)</span> 사이에 박힌 총알의 개수를 이 시간 범위 안에 backstop 에 박힌 모든 총알의 개수 <span class="math inline">\(N\)</span> 으로 나누는 것으로 측정 할 수 있다.</p></li>
<li><p>여러가지 자잘한 가정이 들어간다. 총알이 구멍에 부딛쳐 여러개로 쪼개지지 않고 온전한 총알로 backstop 에서 검출된다, 총알을 발사하는 속도가 일정하다.. 등등</p></li>
</ul>
<p>이제 2번 구멍을 막고 같은 시간동안 같은 실험을 반복하면 모든 총알은 1번 구멍을 통과할 것이며 <span class="math inline">\(x\)</span> 와 <span class="math inline">\(x+dx\)</span> 에 총알이 박힌 개수를 <span class="math inline">\(N\)</span> 으로 나누면 분포 <span class="math inline">\(P_1(x)\)</span> 를 계산 할 수 있다. 또한 1번 구멍을 막고 2번 구멍을 통과하는 실험을 통해 <span class="math inline">\(P_2(x)\)</span> 를 계산 할 수 있다. 당연히 아래의 결과가 나온다.</p>
<p><span id="eq-FLP_1_37_1"><span class="math display">\[
P_{12}(x) = P_1 (x) + P_2(x).
\tag{3.1}\]</span></span></p>
<p><br></p>
</section>
<section id="sec-FLP_1_37_3" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_37_3">I.37-2 파동 실험</h3>
<div id="fig-FLP_1_37_2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_37_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_37/fig_1_37_2.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_37_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.2: 파인만 물리학 강의 I. 그림 37-2. 파동 간섭 실험
</figcaption>
</figure>
</div>
<p>위의 그림과 같이 설정된 파동 실험을 생각하자. 검출기가 움직이는 벽으로부터 파동이 반사되는 것을 막기 위해 벽은 파동을 흡수하는 흡수벽(absorber)이어야 한다. 검출기에서 파동의 높이를 측정한다면 파동의 강도는 진폭의 제곱이다. 파동의 강도 <span class="math inline">\(I_\text{12}\)</span> 를 흡수벽 의 중심으로부터의 변위 <span class="math inline">\(x\)</span> 에 대한 함수로 측정한다. 또한 총알 실험과 같이 <span class="math inline">\(2\)</span> 번 홀을 막은 상태에서 <span class="math inline">\(I_1\)</span> 을 측정하고 <span class="math inline">\(1\)</span> 번 홀을 막은 상태에서 <span class="math inline">\(I_2\)</span> 를 측정한다. <span class="math inline">\(I_1\)</span> 측정시 검출기에서 검출되는 파동은 <span class="math inline">\(\hat{h}_1e^{i\omega t}\)</span> 로 기술된다. 여기서 <span class="math inline">\(\hat{h}_1\)</span> 은 복소수이다. 마찬가지로 <span class="math inline">\(I_2\)</span> 측정시 검출기에서 검출되는 파동은 <span class="math inline">\(\hat{h}_2 e^{i\omega t}\)</span> 로 기술된다. 그렇다면 <span class="math inline">\(I_{12}\)</span> 에 대한 파동은 <span class="math inline">\(\hat{h}_1 e^{i\omega t}+ \hat{h}_2 e^{i\omega t}\)</span> 로 기술되며</p>
<p><span id="eq-FLP_1_37_2"><span class="math display">\[
I_1 = |\hat{h}_1|^2,\quad I_2=|\hat{h}_2|^2,\quad I_{12} = |\hat{h}_1 + \hat{h}_2|^2
\tag{3.2}\]</span></span></p>
<p>이다. 즉 <span class="math inline">\(\hat{h}_1,\,\hat{h}_2\)</span> 의 위상차 <span class="math inline">\(\delta\)</span> 에 대해 다음이 성립한다.</p>
<p><span id="eq-FLP_1_37_4"><span class="math display">\[
I_{12} = I_1 + I_2 + 2\sqrt{I_1I_2} \cos \delta
\tag{3.3}\]</span></span></p>
<p>여기서 마지막 항 <span class="math inline">\(2\sqrt{I_1I_2}\cos \delta\)</span> 를 간섭항(interference term) 이라고 한다.</p>
<p><br></p>
</section>
<section id="sec-FLP_1_37_4" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_37_4">I.37-4 전자 실험</h3>
<div id="fig-FLP_1_37_3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_37_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_37/fig_1_37_3.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_37_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.3: 파인만 물리학 강의 I. 그림 37-3. 전자 간섭 실험
</figcaption>
</figure>
</div>
<p>이제 전자로 동일한 실험을 해 보자. <a href="#fig-FLP_1_37_1" class="quarto-xref">그림&nbsp;<span>3.1</span></a> 에서 기관총을 전자총으로 바꾸고 다른 실험 장비의 스케일을 아주 작게 맞추는 것이라고 생각하자. 실제로 이런 장비를 갖추는 것은 불가능하지만. 이 실험 과정에서 우리는 아래와 같은 사실을 알게 된다.</p>
<ul>
<li><p><strong>결과 1</strong> : 검출되는 전자는 개수이다. 즉 전자가 두개 이상으로 쪼개져서 검출되지 않는다.</p></li>
<li><p><strong>결과 2</strong> : 전자 하나가 발사되었을 때, 그리고 두개 이상의 검출기를 동시에 설치했을 때 두 검출기에서 동시에 검출되지 않는다.</p></li>
</ul>
<p>자 이제 <a href="#sec-FLP_1_37_2">총알 시험</a> 에서와 같이 확률 <span class="math inline">\(P_{12},\, P_1,\, P_2\)</span> 를 구할 수 있다. 그리고 그 결과(<a href="#fig-FLP_1_37_3" class="quarto-xref">그림&nbsp;<span>3.3</span></a>) 는 놀랍게도 <a href="#fig-FLP_1_37_1" class="quarto-xref">그림&nbsp;<span>3.1</span></a> 이 아닌 <a href="#fig-FLP_1_37_2" class="quarto-xref">그림&nbsp;<span>3.2</span></a> 과 같다.</p>
<p><br></p>
</section>
<section id="sec-FLP_1_37_5" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_37_5">I.37-5 전자 파동의 간섭</h3>
<p>결과 2 로부터 우리는 다음과 같은 가설을 새울 수 있다.</p>
<p><strong>가설 A</strong>: 각각의 전자는 1 번 구멍을 통과하거나 2번 구멍을 통과한다.</p>
<p>이로부터 우리는 <span class="math inline">\(P_{12} = P_1+P_2\)</span> 라는 결론을 내릴 수 있지만 실험 결과와는 모순되다. 그렇다면 우리는 간섭이 있다고 볼 수 밖에 없다. 그렇다면 어떻게 간섭이 발생할 수 있을까? 둘 (혹은 그 이상으로) 분리되어 간섭한다는 논리는 결과 1과 상충된다. 혹시 구멍 하나를 닫으면 열린 구멍으로 더 많은 전자가 통과할까? 그러나 결과는 <span class="math inline">\(P_{12}(0)  = 2(P_1(0)+P_2(0))\)</span> 라는 것을 보여준다. 전자가 매우 복잡한 경로로 진행한다는 가정은 별로 설득력이 없어 보인다.</p>
<p>이것을 해결하기 위해 많은 아이디어가 제시되었지만 <span class="math inline">\(P_1,\,P_2\)</span> 로 <span class="math inline">\(P_{12}\)</span> 를 표현하는데 성공하지 못했다. 수학은 간단하다 <span class="math inline">\(P_1,\, P_2,\, P_{12}\)</span> 이 파동식험에서의 <span class="math inline">\(I_1,\, I_2,\, I_{12}\)</span> 와 같은 관계를 가지면 된다. Backstop 에서 벌어지는 일은 어떤 복소함수 <span class="math inline">\(\hat{\phi}_1(x),\, \hat{\phi}_2(x)\)</span> 에 대해</p>
<p><span class="math display">\[
P_1(x) = |\hat{\phi}_1(x)|^2,\quad P_2(x) = |\hat{\phi}_2(x)|^2,\quad P_{12}=|\hat{\phi}_1(x)+\hat{\phi}_2(x)|^2
\]</span></p>
<p>이면 된다. 이제 우리는 다음과 같은 결론을 내릴 수 밖에 없다.</p>
<blockquote class="blockquote">
<p>전자는 총알에서처럼 같이 온전한 입자 형태로 도착하며, 이러한 온전한 입자가 도착할 확률의 분포는 파동의 강도 분포와 같다. 이러한 의미에서 전자는 때때로 입자처럼, 때때로 파동처럼 행동한다.</p>
</blockquote>
<p>우리가 파동을 다룰 때 복소수를 사용하는 것은 일종의 수학적 트릭이었다. 그러나 양자역학에서의 이 진폭은 실제 복소수여야 한다는 것이 밝혀졌다. 실수만으로는 작동하지 않는다. 그리고 그렇게 되면 가설 A 는 폐기되어야 한다. 즉 전자는 1번 혹은 2번 구멍중에 하나만을 통과하지 않는다.</p>
<p><br></p>
</section>
<section id="sec-FLP_1_37_6" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_37_6">I.37-6 전자 관찰</h3>
<div id="fig-FLP_1_37_4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_37_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_37/fig_1_37_4.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_37_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.4: 파인만 물리학 강의 I. 그림 37-4. 다른 전자 실험
</figcaption>
</figure>
</div>
<p>이제 이전의 실험장비에 위의 그림과 같이 강한 광원을 놓자. 빛은 전자에 의해 산란되므로 전자가 1번 구멍 혹은 2번 구멍을 통과하는지 알 수 있다. 2번 구멍을 통과하면 아래쪽에서, 1번 구멍을 통과한다면 위쪽에서 신호가 올 것이다. 둘을 동시에 통과한다면? 어쨌든 해 보자. 그리고 그 결과는 다음과 같다.</p>
<ul>
<li>전자가 검출될 때 마다 위쪽 혹은 아래쪽으로 신호가 온다. 그러나 이 신호는 동시에 오지 않는다. 검출기를 어디에 두더라도 마찬지다.</li>
</ul>
<p>즉 전자는 1번 혹은 2번 구멍 가운데 하나만을 통과한다. 가설 A 는 정확했다. 그런데 놀라운 결과가 나왔다. 1번 구멍을 통과할 때만의 결과를 모아 <span class="math inline">\(P'_1\)</span> 이라고 하고 2번 구멍을 통과할 때만의 결과를 모아 <span class="math inline">\(P'_2\)</span> 를 구성 할 수 있다. 그리고 그 합인 <span class="math inline">\(P'_{12}=P'_1+P'_2\)</span> 도 구할 수 있으며 그 결과는 <a href="#fig-FLP_1_37_4" class="quarto-xref">그림&nbsp;<span>3.4</span></a> 와 같다. 놀라운 결과가 나왔다.</p>
<ul>
<li><p><a href="#sec-FLP_1_37_5">전자 파동의 간섭</a> 의 <span class="math inline">\(P_1,\, P_2\)</span> 와 비교해 보면 <span class="math inline">\(P'_1=P_1,\, P'_2=P_2\)</span> 이다. 그러나 <span class="math inline">\(P'_1,\, P'_2\)</span> 는 구멍을 막지 않았다. 구멍을 막든 막지 않든 1번 구멍을 통과하는 전자는 동일한 확률 분포를 보인다. 2번 구멍도 마찬가지.</p></li>
<li><p><span class="math inline">\(P'_{12}= P'_1+P'_2 \ne P_{12}\)</span> 이다. 우리가 광원을 끈다면 <span class="math inline">\(P'_{12}(\text{off})=P_{12}\)</span> 이다. 즉 우리가 광원을 켬으로서 전자의 경로가 뒤틀렸다. 우리가 전자의 경로를 본다면 간섭 효과는 사라진다.</p></li>
<li><p>혹시 밝기가 너무 강하여 전자의 경로를 변경시켰을까? 이제 밝기를 낮춰 보자. 밝기를 낮추는 것은 광자의 에너지를 바꾸지 않고 단위 시간당 방출되는 광자의 개수를 줄인다는 것이다. 이제 일부 전자는 빛에 산란되지 않고 검출기에 계측된다. 이 경우 전자가 통과했을 때 주변에 광자가 없었다.</p></li>
<li><p>이제 검출기에서 클릭 소리가 들릴 때마다 우리는 세가지로 분류한다: (1) 1번 구멍을 통과하는 신호를 낸 전자들의 분포 <span class="math inline">\(P''_1\)</span> , (2) 2번 구멍을 통과하는 신호를 낸 전자들의 분포 <span class="math inline">\(P''_2\)</span>, (3) 구멍 통과 신호를 내지 않고 계측된 전자들의 분포 <span class="math inline">\(P''_{12}\)</span>. 결과는 다음과 같다.</p>
<p><span class="math display">\[
P''_1 = P'_1=P_1,\qquad P''_2 = P'_2 = P_2,\qquad P''_{12} = P_{12} \ne P'_{12}.
\]</span></p>
<p>즉 전자가 관찰되지 않으면 간섭이 발생한다. 우리가 전자의 경로를 관하지 못하면 어떤 광자도 전자를 교란시키지 않으며, 전자의 경로를 관찰한다면 광자가 전자를 교란한다. 광자는 모두 동일한 크기의 효과를 발생시키고, 광자가 산란되는 효과는 간섭의 효과를 뭉게기에 충분하기 때문에 항상 동일한 양의 교란이 발생한다.</p></li>
</ul>
<p>우리는 광자의 운동량이 파장에 반비례한다는 것을 안다(<span class="math inline">\(p=h/\lambda\)</span>). 광자가 전자에 주는 충격은 광자의 운동량에 의존할 것이다. 따라서 이 충격을 줄이기 위해서는 빛의 강도를 약하게 할 것이 아니라 운동량을 줄여야 한다. 장파장의 빛을 사용한다면 전자를 교란하는 것을 피할 수 있을것이다. 그러나 여기에 한계가 있다. 우리는 앞서 광학 기구의 분해능에 대해 공부했었다. 만약 빛의 파장이 두 구멍 사이의 거리보다 길다면 전자가 어떤 구멍을 통과하는지 알 수 없게 된다. 그리고 이 부근부터 <span class="math inline">\(P'_{12}\)</span> 는 <span class="math inline">\(P_{12}\)</span> 와 비슷해진다. 즉 간섭의 효과가 발생한다. 그리고 파장이 두 구멍 사이의 거리보다 충분히 크다면 <span class="math inline">\(P'_{12}=P_{12}\)</span> 가 된다. 간섭의 효과가 완전히 살아난다.</p>
<p>이 사고실험을 통해 전자가 어떤 구멍을 통과하는지 아는 것과 간섭 효과를 유지시키는 것을 동시에 하는것이 불가능하다는 것을 알게되었다. 이것이 하이젠베르크가 제안한 “불확정성의 원리” 이다.</p>
<p>그렇다면 첫 번째 총알 시험에서는 왜 간섭이 발생하지 않을까? 총알의 경우 파장이 너무 작아 간섭 패턴이 매우 미세해졌다. 사실, 매우 미세하여 유한한 크기의 어떤 검출기라도 최대값과 최소값을 구분할 수 없으며 우리가 본 것은 관측 가능한 범위에서의 일종의 평균일 뿐이다.</p>
<p><br></p>
</section>
<section id="sec-FLP_1_37_7" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_37_7">I.39-7 양자역학의 첫번째 원리</h3>
<p>이제 실험의 주요 결론에 대한 요약하자. 이런 종류의 실험의 일반적인 범주에 대해서도 요약의 결과가 사실이 되도록 하겠다. 여기서 두가지 용어를 명확하게 하자.</p>
<ul>
<li><strong>이상적인 실험</strong> : 불확실한 외부 영향이 없는, 즉 흔들림이나 우리가 고려할 수 없는 다른 일들이 없는 실험. “실험의 초기 및 최종 조건이 모두 완전히 명시된 경우” 라고 한다면 상당히 정확하다.</li>
<li><strong>사건</strong> : 일반적으로 초기와 최종 조건의 특정한 집합. (예: 전자가 총을 떠나 검출기에 도착하고, 그 외에는 아무 일도 일어나지 는 경우)</li>
</ul>
<p>요약은 아래와 같다.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">중요</span><strong>요약</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>이상적인 실험에서 사건의 확률 <span class="math inline">\(P\)</span> 는 복소수 <span class="math inline">\(\phi\)</span> 의 절대값의 제곱으로 주어지며, 이를 <strong>확률진폭(probability amplitude)</strong> 라고 한다. 즉 <span class="math inline">\(P = |\phi|^2\)</span> 이다.</p></li>
<li><p>사건이 여러 가능한 대안들(<span class="math inline">\(f_1,\dots,\,f_N\)</span>) 가운데 하나로 발생할 수 있는 경우, 그 사건의 확률 진폭(<span class="math inline">\(\phi\)</span>) 은 각 대안들에 대한 확률진폭(<span class="math inline">\(\phi_1,\ldots,\,\phi_N\)</span>) 의 합이다. 즉 <span class="math inline">\(\phi = \sum_i \phi_i\)</span>, <span class="math inline">\(P=|\phi|^2\)</span> 이다. 즉 간섭이 발생한다.</p></li>
<li><p>실제로 하나의 대안이 취해졌는지 여부를 판단할 수 있는 실험이 수행된다면, 그 사건의 확률 <span class="math inline">\(P\)</span> 은 각 대안에 대한 확률 (<span class="math inline">\(P_1,\ldots,\,P_N\)</span>) 의 합이다. 즉 <span class="math inline">\(P_i=|\phi_i|^2\)</span> 에 대해 <span class="math inline">\(P = \sum_i P_i\)</span> 이다. 간섭은 발생하지 않는다.</p></li>
</ol>
</div>
</div>
<p>이 요약보다 더 근본적인 수준에서의 설명은 존재하지 않는다.</p>
<blockquote class="blockquote">
<p>이제 고전 역학과 양자역학의 중요한 차이에 대해 강조하고자 한다. 앞서 주어진 상황에서 전자가 도착할 확률에 대해 이야기 했으며 정확히 어떤 일이 일어날지 예측하는 것이 불가능함을 암시했다. 우리는 확률만 예측할 수 있다! 이는 물리학이 특정 상황에서 정확히 어떤 일이 일어날지 예측하는 것을 포기했다는 의이이다. 우리는 주어진 상황에서 일어날 일을 예측하는 방법을 알지 못하며, 이제는 그것이 불가능하다고 믿으며, 예측할 수 있는 유일한 것은 다양한 사건의 확률이라고 생각한다. 이는 이전의 우리가 자연을 이해한다는 이상에 대한 재제한(retrenchment) 임을 인식해야 한다. 그것은 뒤로 물러나는 단계일 수도 있지만, 이를 피할 방법은 아직 없다.</p>
<p>혹은 “아마도 전자는 아직 알지 못하는 일종의 내부 작용—어떤 내부 변수—를 가지고 있는 것일지도 모른다. 아마도 그것이 우리가 일어날 일을 예측할 수 없는 이유일 것이다. 우리가 전자를 더 자세히 관찰할 수 있다면, 종래는 어디에 위치하게 될지 알 수 있을 것이다.” 라고 생각할수도 있다. 그러나 우리가 알기로는 그것은 불가능하다. 우리는 여전히 관란에 처하게 될 것이다. 예를 들어, 전자 내부에 어떤 종류의 machinary 가 있어 그것이 어디에 도착할지 결정한다고 가정해 보자. 그 기계는 또한 진행 중에 어느 구멍을 통과할지 결정해야 한다. 하지만 우리는 전자 내부에 있는 것이 우리가 하는 일에 의존해서는 안 되며, 특히 우리가 구멍 가운데 하나를 열거나 닫는지에 의존해서는 안된다. 따라서 전자가 출발하기 전에 이미 (a) 어떤 구멍을 통과할지, (b) 어디에 도착할지를 결정했다면, 1번 구멍을 선택한 전자는 <span class="math inline">\(P_1\)</span> 을, 2 번 구멍을 선택한 전자는 <span class="math inline">\(P_2\)</span> 를 구하고, 두 개의 홀을 통과하는 전자는 반드시 <span class="math inline">\(P_1+P_2\)</span> 의 합을 구해야 한다. 이것을 고를 방법이 없는 것 같습니다. 하지만 우리는 실험적으로 그것이 그렇지 않다는 것을 확인했다. 그리고 아무도 이 퍼즐에서 탈출할 방법을 찾지 못했다. 따라서 현재는 우리는 확률을 계산하는 데만 국한해야 합니다. 우리는 “현재는” 라고 말하지만, 그것이 영원히 우리와 함께할 것이라고-그 퍼즐을 이기는것이 불가능하다고-매우 강하게 의심합니다. 즉 이것이 자연이 실제로 존재하는 방식이라는 것이다.</p>
</blockquote>
<p><br></p>
</section>
<section id="sec-FLP_1_37_8" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_37_8">I.37-8 불확정성의 원리</h3>
<p>하이젠베르그가 최초로 제안한 형태는 아래와 같다.</p>
<blockquote class="blockquote">
<p>운동량의 <span class="math inline">\(x\)</span> 성분 <span class="math inline">\(p_x\)</span> 를 <span class="math inline">\(\Delta p_x\)</span> 의 불확도로 측정했을 때, 동시에 <span class="math inline">\(x\)</span> 방향 위치를 측정한다면 그 불확도 <span class="math inline">\(\Delta x\)</span> 는 <span class="math inline">\(\hbar/2\Delta p_x\)</span> 보다 크다.</p>
</blockquote>
<p>더 일반적인 진술은 아래와 같다. &gt; 두 대안 중 어느 것이 취해지는지를 판단하면서 동시에 간섭 패턴을 파괴하지 않는 실험장비를 고안할 수 없다.</p>
<p>하이젠베르크가 제시한 관계가 반드시 참이어야 문제가 발생하지 않는 특정한 예를 들어보자.</p>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">
<div id="exm-FLP_uncertainty_original" class="theorem example">
<p><span class="theorem-title"><strong>예제 3.1 (이중슬릿실험의 개선과 불확정성의 원리)</strong></span> &nbsp;</p>
<div id="fig-FLP_1_37_6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_37_6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_37/fig_1_37_6.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_37_6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.5: 파인만 물리학 강의 I. 그림 37-6. 벽의 반동이 측정되는 실험
</figcaption>
</figure>
</div>
<p><a href="#fig-FLP_1_37_3" class="quarto-xref">그림&nbsp;<span>3.3</span></a> 의 실험을 위와 같이 개선해 보자. 여기서는 벽(wall)은 롤러로 지탱하는 판으로 구성되었고 판은 위나 아래로 (<span class="math inline">\(x\)</span>-방향으로) 자유롭게 움직일 수 있다. 그리고 검출기는 <span class="math inline">\(x=0\)</span> 에 고정되어 있다.</p>
<p>검출기에 계측된 전자가 벽이 1번 구멍을 지난다면 회절에 의해 운동량이 아래로 꺽이며, 운동량 보존에 의해 벽의 판은 위로 반동된다. 계측된 전자가 2번 구멍을 지난다면 벽의 판은 아래로 반동된다. 우리는 전자를 교란시키지 않고 판의 움직임만 보고서도 전자가 어느 구멍을 통과했는지 알 수 있게된다.</p>
<p>우리는 전자가 통과하고 난 뒤 판의 운동량의 변화를 측정해야 한다. 그러나 불확정성의 원리에 의해 판의 위치와 운동량을 동시에 정확하게 측정 할 수 없다. 우리가 판의 위치를 정확하게 알 수 없다면 두 구멍의 위치도 정확하게 알 수 없다. 각각의 전자가 통과할 때 마다 서로 다른 위치에 있게 되며 따라서 간섭무늬의 중심도 움직이며 간섭 무늬 자체가 뭉개진다.</p>
</div>
</div>
<p>다음 장에서 우리는 판의 운동량을 충분히 정확하게 결정하여 반동 측정으로부터 어떤 구멍을 통과했는지 판단할 수 있다면, 불확정성 원리에 따라 판의 <span class="math inline">\(x\)</span> 위치에 대한 불확정성이 검출기에서 관찰되는 패턴을 최대값에서 가장 가까운 최소값까지의 거리만큼 위아래로 이동시키기에 충분하다는 것을 정량적으로 보여줄 것이다. 즉 간섭이 관찰되지 않을 정도로 충분하다.</p>
<p>하이젠베르크는 운동량과 위치를 동시에 더 높은 정확도로 측정할 수 있다면 양자역학이 붕괴될 것임을 인식으며 따라서 그것이 불가능해야 한다고 제안했다. 그 당시 사람들은 자리에 앉아 방법을 찾으려 했지만 위치와 운동량을 더 정확하게 측정할 방법을 아무도 찾지 못했다.</p>
<p><br></p>
</section>
</section>
<section id="sec-FLP_1_38" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-FLP_1_38">I.38 입자 관점과 파동 관점의 관계</h2>
<section id="sec-FLP_1_38_1" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="sec-FLP_1_38_1">I.38-1 확률파의 진폭</h3>
<blockquote class="blockquote">
<p>In this chapter we shall discuss the relationship of the wave and particle viewpoints. We already know, from the last chapter, that neither the wave viewpoint nor the particle viewpoint is correct. Usually we have tried to present things accurately, or at least precisely enough that they will not have to be changed when we learn more—it may be extended, but it will not be changed! But when we try to talk about the wave picture or the particle picture, both are approximate, and both will change. Therefore what we learn in this chapter will not be accurate in a certain sense; it is a kind of half-intuitive argument that will be made more precise later, but certain things will be changed a little bit when we interpret them correctly in quantum mechanics. The reason for doing such a thing, of course, is that we are not going to go directly into quantum mechanics, but we want to have at least some idea of the kinds of effects that we will find. Furthermore, all our experiences are with waves and with particles, and so it is rather handy to use the wave and particle ideas to get some understanding of what happens in given circumstances before we know the complete mathematics of the quantum-mechanical amplitudes. We shall try to illustrate the weakest places as we go along, but most of it is very nearly correct—it is just a matter of interpretation.</p>
</blockquote>
<p>양자역학에서는 발생할 수 있는 모든 사건에 진폭을 부여한다. 그리고 사건이 한 입자의 reception 과 관련된다면 우리는 이 입자가 다른 시간 다른 장소에서 발견될 진폭을 부여할 수 있다. 그리고 입자를 발견할 확률은 진폭의 절대값 제곱이다. 한 입자를 다른 장소와 다른 시간에 발결할 확률은 위치와 시간에 따라 변한다.</p>
<p>특별한 경우 진폭은 정해진 진동수 <span class="math inline">\(\omega\)</span> 와 파수 벡터(wave vector) <span class="math inline">\(\boldsymbol{k}\)</span> 에 대해 <span class="math inline">\(e^{i(\omega t - \boldsymbol{k\cdot r})}\)</span> 와 유사한 형태이다. 이것은 입자의 에너지 <span class="math inline">\(E\)</span> 가 알려져 있으며 진동수와</p>
<p><span id="eq-FLP_1_38_1"><span class="math display">\[
E= \hbar \omega
\tag{3.4}\]</span></span></p>
<p>의 관계가 있으며 운동량 <span class="math inline">\(\boldsymbol{p}\)</span> 역시 알려져 있고 파수 벡터 <span class="math inline">\(\boldsymbol{k}\)</span> 와 <span id="eq-FLP_1_38_2"><span class="math display">\[
\boldsymbol{p}=\hbar \boldsymbol{k}
\tag{3.5}\]</span></span></p>
<p>의 관계가 있는 고전적인 극한에 해당한다. 이것은 입자 관점의 한계이다. 입자 관점, 즉 위치와 운동량으로 기술하는 관점인데 진폭 <span class="math inline">\(e^{i(\omega t -\boldsymbol{k\cdot r})}\)</span> 의 절대값의 제곱은 상수이며 이는 모든 지점에서 발견될 확률이 동일하다는 의미이기 때문이다.</p>
<div class="page-columns page-full"><p>반대로 입자의 위치가 어느 정도 잘 알려져 있고 향후의 위치도 잘 예측 할 수 있다면 입자를 다른 장소에서 발견할 확률은 특정 영역에 제한적이다. 이 영역을 <span class="math inline">\(\Delta x\)</span> 라고 하며 이 영역 밖에서 발견할 확률은 <span class="math inline">\(0\)</span> 이다. 확률은 진폭의 절대값 제곱 이며 따라서 진푝 역시 <span class="math inline">\(\Delta x\)</span> 영역 밖에서는 <span class="math inline">\(0\)</span> 이다. 즉 우리는 길이가 <span class="math inline">\(\Delta x\)</span> 인 <strong>파동 패킷(wave packet)</strong><span class="math inline">\(^1\)</span> 을 얻으며 이 파동 패킷의 파장은 입자의 운동량에 대응한다.  그러나 이런 파동 패킷에 고유한 파장을 정할수 없다는 것이 잘 알려져 있다. 이 파동 패킷이 특정한 파장을 가지지 않는다면 파수에도 이 패킷의 폭과 관련된 불확실성이 존재하며 이것은 운동량의 불확실성이다.</p><div class="no-row-height column-margin column-container"><span class="margin-aside"><span class="math inline">\(^1\)</span> 파인만은 wave train 이란 용어를 사용한다.</span></div></div>
<p><br></p>
</section>
<section id="sec-FLP_1_38_2" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_38_2">I.38-2 위치와 운동량의 측정</h3>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">
<div id="exm-FLP_1_28_2_1" class="theorem example">
<p><span class="theorem-title"><strong>예제 3.2 (단일 슬릿을 통과하는 입자의 회절)</strong></span> &nbsp;</p>
<div id="fig-FLP_1_38_2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_38_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_38/fig_1_38_2.png" class="img-fluid figure-img" width="270">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_38_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.6: 파인만 물리학 강의 I. 그림 38-2. 단일 슬릿을 지나가는 입자의 회절
</figcaption>
</figure>
</div>
<p>위의 그림과 같은 단일 슬릿 실험을 생각하자. 입자들은 정해진 에너지를 가지고 아주 멀리서부터 수평 방향으로 진입한다. 모든 입자들은 고전적인 의미에서 수평방향의 운동량을 <span class="math inline">\(p_0\)</span> 와 수직방향의 운동량 <span class="math inline">\(p_y\)</span> 를 갖는다. 입자는 멀리 떨어진 곳에서 왔기 때문에 위나 아래로 움직이지 않으며, 따라서 수직 운동량은 당연히 0 이다. 이제 이 입자가 폭이 <span class="math inline">\(B\)</span> 인 슬릿을 통과한다고 하자. 이제 우리는 입자의 수직 위치에 대한 불확실성은 <span class="math inline">\(\pm B/2\)</span> 이다.</p>
<p>이제 우리는 운동량이 절대적으로 수평임을 알고 있기 때문에 <span class="math inline">\(\Delta p_y=0\)</span> 이라고 말하고 싶을 수도 있지만, 그것은 틀렸다. 우리는 한때 그 운동량이 수평방향만 존재한다는 것을 알았을 뿐, 더 이상을 알지 못한다. 입자들이 구멍을 통과하기 전에, 우리는 그들의 수직 위치를 알지 못했다. 이제 입자가 구멍을 통과하도록 하여 수직 위치를 찾았으나 수직 운동량에 대한 정보를 잃어버렸다! 왜? 파동 이론에 따르면, 빛과 마찬가지로 파동이 슬릿을 통과한 후에도 회절이 일어나며 따라서 슬릿에서 나오는 입자들이 정확히 직선으로 나오지 않을 가능성이 있다. 패턴은 회절 효과로 인해 퍼지며 첫 번째 최소값의 각도로 정의할 수 있는 확산각은 최종 각도의 불확실성을 측정한 것이다.</p>
<p>패턴은 어떻게 확산되는가? 그것이 퍼졌다고 말한다는 것은 입자가 위아래로 움직일 가능성이 어느 정도 있다는 의미이며, 즉 운동량의 수직 성분이 <span class="math inline">\(0\)</span> 이 아니라는 의미이다. 우리는 이 회절 패턴을 입자 카운터로 감지할 수 있으며 카운터는 온전한 입자를 세기 때문에 <strong>가능성</strong> 과 <strong>입자</strong> 라고 말한다. 그리고 예를 들어 <a href="#fig-FLP_1_38_2" class="quarto-xref">그림&nbsp;<span>3.6</span></a> 의 <span class="math inline">\(C\)</span> 에서 온전한 입자를 측정하기 때문에, 고전적인 의미에서 입자는 슬릿에서 <span class="math inline">\(C\)</span> 까지 도달하기 위해 수직 운동량을 갖는다.</p>
<p>수직 운동량 <span class="math inline">\(p_y\)</span> 은 대략 <span class="math inline">\(p_0 \Delta \theta\)</span> 와 같은 확산을 가진다. 그렇다면 확산 패턴에서 <span class="math inline">\(\Delta \theta\)</span> 는 어느 정도인가? 우리는 패턴의 첫번째 최소값이 <span class="math inline">\(\Delta \theta\)</span> 각도에서 발생하여 슬릿의 한쪽 가장자리에서 나오는 파동이 반대쪽에서 오는 파동보다 한 파장 더 많이 이동해야 한다는 것을 알고 있다. 따라서 <span class="math inline">\(\Delta \theta\)</span> 는 <span class="math inline">\(\lambda /B\)</span> 이며, 따라서 이 실험에서 <span class="math inline">\(\Delta p_y = p_0 \lambda/B\)</span> 이다. <span class="math inline">\(B\)</span> 를 작게 만들어 입자의 위치를 보다 정확하게 측정하면 회절 패턴이 넓어진다는 것을 기억하라. 이는 입자가 수직방향의 운동량을 가지고 있음을 발견할 가능성이 높아짐을 의미한다. <span class="math inline">\(\Delta y = B/2\)</span> 이며 <span class="math inline">\(p_0 = h/\lambda\)</span> 이므로 우리는 <span class="math inline">\((\Delta y)(\Delta p_y) \approx h\)</span> 라는 규칙을 얻는다. 정확히는 아래와 같다.</p>
<p><span id="eq-FLP_1_38_3"><span class="math display">\[
(\Delta y ) (\Delta p_y) \ge \dfrac{\hbar}{2}, \quad\text{where }\hbar = \dfrac{h}{2\pi}
\tag{3.6}\]</span></span></p>
<p>우리는 입자의 수직 위치를 알고, <a href="#eq-FLP_1_38_3" class="quarto-xref">식&nbsp;<span>3.6</span></a> 에서 제시된 것보다 더 높은 확신을 가지고 입자의 수직 이동을 예측할 수 있는 시스템을 준비할 수 없다. 즉, 수직 운동량의 불확실성은 <span class="math inline">\(\hbar/2\Delta y\)</span> 를 초과해야 한다.</p>
<p>우리가 입자가 슬릿을 통과하기 전의 운동량을 충분히 작은 불확실성 <span class="math inline">\(\Delta p_y^{(i)}\)</span> 으로 안다고 하자. 그리고 입자가 슬릿을 통과하면서 위치에 대한 정보도 충분히 작은 불확실성으로 일 수 있다. <span class="math inline">\(\Delta y = B\)</span>. 이 값의 곱이 <span class="math inline">\(\hbar/2\)</span> 보다 작게 만들 수 있으며 이는 <a href="#eq-FLP_1_38_3" class="quarto-xref">식&nbsp;<span>3.6</span></a> 와 모순된다. 무엇이 어디서부터 잘못됬을까? <a href="#eq-FLP_1_38_3" class="quarto-xref">식&nbsp;<span>3.6</span></a>$ 이 의미하는 바는 상황의 예측 가능성을 의미하며, 과거에는 의미가 없다. 슬릿을 통과하는 순간 과거 운동량에 대한 지식은 무의미하다.</p>
</div>
</div>
<p><br></p>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">
<div id="exm-FLP_1_28_2_2" class="theorem example">
<p><span class="theorem-title"><strong>예제 3.3 (단일 슬릿을 통과하는 입자의 회절)</strong></span> &nbsp;</p>
<div id="fig-FLP_1_38_3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_38_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_38/fig_1_38_3.png" class="img-fluid figure-img" width="220">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_38_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.7: 파인만 물리학 강의 I. 그림 38-3. 회절격자를 이용한 운동량 측정
</figcaption>
</figure>
</div>
<p>많은 수의 선으로 이루어진 회절격자(<a href="vol1_2.html#sec-FLP_1_30">I.30 회절</a> 을 참고하라)에 빛을 입사시키면 간섭으로 인해 특정한 각도에서 강한 빛을 얻는다. 여기서 얼마나 정확하게 빛의 운동량을 측정할 수 있을지 생각해보자. 주어진 회절격자의 분해능은 <a href="vol1_2.html#eq-FLP_1_30_9" class="quarto-xref">식&nbsp;<span>2.57</span></a> 이다. 여기서 <span class="math inline">\(N\)</span> 은 선의 개수이고 <span class="math inline">\(m\)</span> 은 회절격자의 치수이다. 여기서 <span class="math inline">\(L=Nm\lambda\)</span> 라고 하면 회절격자의 양 끝단에서 반사된 빛 혹은 입자의 경로차이다. 회절격자의 분해능과 <span class="math inline">\(L\)</span> 로 부터 다음 식을 얻는다.</p>
<p><span id="eq-FLP_1_38_5"><span class="math display">\[
\dfrac{\Delta \lambda}{\lambda^2} = \dfrac{1}{Nm\lambda} = \dfrac{1}{L}.
\tag{3.7}\]</span></span></p>
<p>즉 회절 패턴을 형상하는 파동등은 격자의 다른 부분으로부터 오는 파동들이다. 위의 식으로 부터 <span class="math inline">\(\Delta \lambda\)</span> 를 최소화 하기 위해서는 최대한의 <span class="math inline">\(L\)</span> 을 사용해야 한다는 것을 알 수 있다. 또한</p>
<p><span id="eq-FLP_1_38_6"><span class="math display">\[
\dfrac{\Delta \lambda}{\lambda^2} = \Delta \left(\dfrac{1}{\lambda}\right) = \dfrac{\Delta k}{2\pi}
\tag{3.8}\]</span></span></p>
<p>이므로</p>
<p><span id="eq-FLP_1_38_7"><span class="math display">\[
\Delta k = \dfrac{2\pi}{L}
\tag{3.9}\]</span></span></p>
<p>이다. <span class="math inline">\(p=hk\)</span> 이므로 <span class="math inline">\(\Delta p = h\Delta k\)</span> 이다. 또한 <span class="math inline">\(L\)</span> 은 관측 지점에 도착하는 파동 패킷의 폭을 결정한다. 즉 <span class="math inline">\(\Delta x= L\)</span> 이다. 실제로 파동 패킷의 길이와 파수의 불확정도를 곱하면 <span class="math inline">\(\pi\)</span> 보다 크다는 것은 양자역학 이전에도 잘 알려져 있는 사실이다.</p>
<p>… to be updated …</p>
</div>
</div>
<p><br></p>
</section>
<section id="sec-FLP_1_28_3" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_28_3">I.28-3 결정 회절</h3>
<p>원자, 이온, 분자 등이 3차원 공간에서 규칙적이고 주기적인 패턴으로 배열된 고체 물질을 <strong>결정(Crystal, 結晶)</strong> 이라고 한다. 강한 반사 신호를 얻기 위해서는 모든 원자로부터의 산란의 위상이 일치해야 한다.</p>
<div id="fig-FLP_1_38_4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_38_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_38/fig_1_38_4.png" class="img-fluid figure-img" width="300">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_38_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.8: 파인만 물리학 강의 I. 그림 38-4. 결정면에서의 파동의 산란
</figcaption>
</figure>
</div>
<p>위의 그림과 같은 두 평면을 생각하자. 이 두 면에서의 파동이 산란될 때 경로차가 파장의 정수배라면 산란된 파동은 동일한 위상을 갖게 된다. 이 결맞는 반사(coherent reflection) 의 조건은 다음과 같다.</p>
<p><span id="eq-FLP_1_38_9"><span class="math display">\[
2d\sin \theta = n \lambda \qquad (n=1,\,2,\ldots).
\tag{3.10}\]</span></span></p>
<p>결정의 원자들이 <a href="#eq-FLP_1_38_9" class="quarto-xref">식&nbsp;<span>3.10</span></a> 에서 <span class="math inline">\(n=1\)</span> 을 만족하는 면 위에 있다면 강한 반사가 생긴다. 반면 같은 성질을 갖는 원자들이 같은 밀도로 중간에 존재한다면 중간의 평면에 의해 소멸간섭이 발생하여 아무 일도 벌어지지 않을 것이다. 따라서 <span class="math inline">\(d\)</span> 는 가장 가까운 평면 사이의 거리가 되어야 한다.</p>
<p><a href="#eq-FLP_1_38_9" class="quarto-xref">식&nbsp;<span>3.10</span></a> 에서 <span class="math inline">\(d&lt; \lambda/2\)</span> 라면, 즉 <span class="math inline">\(\lambda &gt; 2d\)</span> 이면 만족하는 <span class="math inline">\(\theta\)</span> 가 존재하지 않는다. 즉 회절에 의한 신호가 발생하지 않는다. 가시광선의 경우 일반적인 결정의 <span class="math inline">\(d\)</span> 에 비해 매우 크기 때문에 회절 패턴이 검출되지 않는다.</p>
<p><br></p>
</section>
<section id="sec-FLP_1_38_4" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_38_4">I.38-4 원자의 크기</h3>
<section id="수소-원자의-크기와-에너지" class="level4">
<h4 class="anchored" data-anchor-id="수소-원자의-크기와-에너지"><strong>수소 원자의 크기와 에너지</strong></h4>
<p>여기서는 원자의 크기에 대해 불확정성의 원리를 이용하여 근사적 계산을 수행하려 한다. 아이디어는 옳지만 실제 계산은 정확하지 않다.</p>
<p>수소 원자의 전자의 위치를 측정한다고 하자. 전자가 정확히 어디에 위치할지 예측할 수 없으며, 그렇지 않으면 운동량은 무한히 퍼져있게 된다. 전자의 위치를 측정할 수 있지만 다른 위치에서 발견될 가능성이 있다. 이 위치는 핵은 아니며, <span class="math inline">\(a\)</span> 정도로 퍼져있다고 가정하자.즉, 전자와 핵 사이의 거리는 보통 약 <span class="math inline">\(a\)</span> 이다. 이제 원자의 전체 에너지를 최소화함으로써 <span class="math inline">\(a\)</span> 를 결정해 보자.</p>
<p>우선 <span class="math inline">\((\Delta p_x)^2 = \langle p_x^2\rangle - \langle p_x \rangle^2\)</span> 이며 대칭을 고려하면 의해 <span class="math inline">\(\langle p_x\rangle =0\)</span> 이므로 <span class="math inline">\((\Delta p_x)^2 = \langle p_x^2\rangle\)</span> 이다. 따라서</p>
<p><span class="math display">\[
\langle p^2\rangle = (\Delta p_x)^2 + (\Delta p_y)^2 + (\Delta p_z)^2 \approx \dfrac{\hbar^2}{a^2}
\]</span></p>
<p>을 얻는다. 그렇다면 총 에너지 <span class="math inline">\(E\)</span> 는</p>
<p><span class="math display">\[
E = \dfrac{\langle p^2\rangle}{2m^2} - \dfrac{e^2}{a} = \dfrac{\hbar^2}{2ma^2} - \dfrac{e^2}{4\pi\epsilon_0 a}
\]</span></p>
<p>이며 <span class="math inline">\(E\)</span> 를 최소로 하는 <span class="math inline">\(a\)</span> 값을 <span class="math inline">\(dE(a_0)/da=0\)</span> 을 통해 계산하면</p>
<p><span id="eq-FLP_1_38_12"><span class="math display">\[
a_0 = \dfrac{4\pi\epsilon_0\hbar^2}{me^2} = 0.528 \times 10^{-10}\,\text{m}
\tag{3.11}\]</span></span></p>
<p>이다. 이 <span class="math inline">\(a_0\)</span> 를 <strong>보어 반지름 (Bohr radius)</strong> 라고 하며 실제로 꽤 정확한 값이다. 또한 이 <span class="math inline">\(a_0\)</span> 를 통해 수소원자의 전자의 에너지 <span class="math inline">\(E_0\)</span> 를 계산하면</p>
<p><span id="eq-FLP_1_38_13"><span class="math display">\[
E_0 = \dfrac{\hbar^2}{2ma_0^2} - \dfrac{e^2}{4\pi\epsilon_0 a_0} = -13.6 \text{ eV}
\tag{3.12}\]</span></span></p>
<p>이다. 에너지가 음수인 것은 전자가 수소 원자에 묶여 있기 때문이다. 그리고 이 값은 계산 과정에서 대략적인 근사를 사용했음에도 불구하고 매우 정확한 수소 원자의 이온화 에너지값이다.</p>
</section>
<section id="원자의-안정성" class="level4">
<h4 class="anchored" data-anchor-id="원자의-안정성"><strong>원자의 안정성</strong></h4>
<p>이제 우리가 바닥을 뚫고 지나가서 떨어지지 않는 이유를 알 수 있다. 우리가 걸을 때 우리 신발은 원자의 질량으로 바닥의 원자를 누른다. 이 원자들이 서로 뭉뜽겨러지기 위해서는 원자들이 서로 매우 가까워지고 전자들 역시 훨씬 좁은 공간으로 제한되어야 한다. 그러나 불확정성의 원리에 의해 운동량이 매우 커지게 되고 이는 에너지를 증가시킨다. 원자를 압축시킬때의 이런 효과는 고전적인 효과가 아닌 양자역학적인 효과이다. 고전적으로는 전자와 양성자의 바닥상태는 둘이 붙어있는 상태이다. 양자역학이 등장하기 전까지 원자의 존재는 풀리지 않는 문제였다.</p>
<p>말이 나온김에 말하자면, 많은 전자가 있는 상황에서는 전자들이 서로 멀리 두려고 한다. 한 전자가 특정 공간을 차지하고 있다면, 다른 전자는 같은 공간을 차지하지 않는다. 정확히 말하면, 두 개의 스핀 케이스가 있어 두 개가 서로 위에 앉을 수 있으며, 하나는 한 방향으로 회전하고 다른 하나는 반대 방향으로 회전한다. 하지만 그 이후에는 더 이상 전자를 그곳에 추가 할 수 없다. 우리는 다른 전자를 다른 곳에 배치해야 하며, 그것이 바로 물질이 내구력을 가지는 진정한 이유이다. 만약 모든 전자를 같은 위치에 놓을 수 있다면 현재보다 더 많이 응축될 것이다. 전자들이 모두 서로 겹칠 수 없다는 사실이 테이블과 그 외 모든 것을 단단하게 만드는 이유이다.</p>
<p><br></p>
</section>
</section>
<section id="sec-FLP_1_38_5" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_38_5">I.38-5 에너지 준위</h3>
<p>앞서 원자에 대해 가능한 가장 낮은 에너지 조건에 대해 알아보았지만, 전자는 너 높은 에너지를 가질 수 있다. 양자역학에 따르면 정적인 상태에서는 원자에 대해 정해진 에너지만 존재할 수 있다. 자유전자, 즉 에너지가 양수인 전자는 어떤 에너지든 가질 수 있으며 어떤 속도로든 움직일 수 있지만 속박된 전자의 에너지는 임의적이지 않다.</p>
<p>이제 허용된 에너지를 <span class="math inline">\(E_0,\,E_1,\,E_2,\,E_3\)</span> 하자. 가장 낮은 에너지 <span class="math inline">\(E_0\)</span> 를 갖는 상태를 <strong>바닥 상태 (ground state)</strong> 라고 하고 바닥 상태보다 높은 에너지 <span class="math inline">\(E_1,\,E_2,\,E_3\)</span> 를 갖는 상태를 <strong>들뜬 상태 (excited state)</strong> 라고 한다. 들뜬 상태의 원자는 영원히 거기 있을 수 없으며 빛의 형태로 에너지를 방출하고 더 낮은 에너지 상태로 떨어진다(이를 전이된다고 한다). 방출되는 빛의 진동수는 두 상태의 에너지 차이에 의해 에너지를 보존하는 방식으로 결정된다. 즉 들뜬 상태 <span class="math inline">\(E_j\)</span> 에서 이보다 에너지가 낮은 상태 <span class="math inline">\(E_i\)</span> 로 전이될 때 방출하는 빛의 진동수 <span class="math inline">\(\omega_{ji}\)</span> 는</p>
<p><span id="eq-FLP_1_38_5_1"><span class="math display">\[
\omega_{ji} = \dfrac{E_j - E_i}{\hbar}
\tag{3.13}\]</span></span></p>
<p>이다. 또한 <span class="math inline">\(E_j\)</span> 와 <span class="math inline">\(E_i\)</span> 사이에 <span class="math inline">\(E_k\)</span> 상태가 있어 <span class="math inline">\(E_j &gt; E_k &gt; E_i\)</span> 이며 <span class="math inline">\(\omega_{jk}\)</span> 와 <span class="math inline">\(\omega_{ki}\)</span> 를 안다면</p>
<p><span class="math display">\[
\omega_{ji} = \omega_{jk} + \omega_{ki}
\]</span></p>
<p>이다. 이를 <strong>리츠 조합 원리 (Ritz combinational principle)</strong> 라고 한다.</p>
<p>우리는 이미 양자역학이 특정 진동수와 파수를 갖는 파동처럼 행동하는 진폭으로 표현된다는 것에 대해 논의했다. 원자가 명확한 에너지 상태를 가지고 있다는 진폭 관점에서 이것을 관찰해 보자. 지금까지 설명한 것으로는 이해할 수 없지만 제한된 공간적으로 한정된 파동이 일정한 진동수를 가진다는 사실은 우리 모두 잘 알고 있다. 예를 들어 소리가 오르간 파이프나 그와 유사한 것에 한정된 경우, 소리가 진동할 수 있는 방법은 하나 이상 존재하며, 각 방법마다 일정한 진동수를 가진다. 파동이 한정된 물체는 일정한 공명 주파수를 가지고 있다. 따라서 제한된 공간에 존재하는 파동의 특성은—이 주제는 나중에 공식과 함께 자세히 논의할 것이다—그 파동은 일정한 주파수에서만 존재한다는 것이다. 그리고 진폭과 에너지의 주파수 사이에 일반적인 관계가 존재하므로, 원자에 결합된 전자와 연관된 명확한 에너지를 발견하는 것이 놀랍지 않다.</p>
<p><br></p>
</section>
<section id="sec-FLP_1_38_6" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_38_6">I.38-6 철학적 함의</h3>
<p><br></p>
</section>
</section>
<section id="sec-FLP_1_39" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-FLP_1_39">I.39. 기체의 동역학</h2>
<section id="sec-FLP_1_39_1" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_39_1">I.39-1 물질의 성질</h3>
<section id="새로운-주제-물질" class="level4">
<h4 class="anchored" data-anchor-id="새로운-주제-물질"><strong>새로운 주제 : 물질</strong></h4>
<ul>
<li><p>여기서는 전기적으로 상호작용하고 역학 법칙을 따르는 수많은 원자로 이루어진 “물질 (matter)” 에 대해 알아본다.</p></li>
<li><p>우리가 앞에서 배웠던 역학 또는 빛은 기본 법칙들에서 시작하여 다양한 현상을 이해하였다. 그러나 물질을 이해하기 위해서는 수많은 원자들을 다뤄야 하며 역학과 전자기 법칙만으로 직접 분석하기에는 너무 복잡하다. 보통 많은 단계를 거쳐 이해하지만 각 단계 자체도 많이 복잡하며 점점 정확성이 떨어진다.</p></li>
<li><p>어려운 이유</p>
<ol type="1">
<li>수학적 이유 : 개별 원자의 모든 움직임을 파악하기 보다는 평균적인 운동과 효과를 다루기 때문에 확률 이론이 중요하다.</li>
<li>물리적 이유 : 고전역학이 아닌 양자역학적으로 접근해야 한다.</li>
</ol></li>
</ul>
</section>
<section id="그럼에도-불구하고-지금-다루는-이유" class="level4">
<h4 class="anchored" data-anchor-id="그럼에도-불구하고-지금-다루는-이유"><strong>그럼에도 불구하고 지금 다루는 이유</strong></h4>
<ul>
<li><p>느긋하게! : 우선 다양한 상황에서 일어나야 할 일에 대해 대략적인 아이디어를 얻고, 나중에 우리가 법칙을 더 잘 알게 되면 이를 더 잘 정립하게 될 것이다. 실제 문제에서 물질의 특성을 분석하고자 하는 사람은 기본 방정식을 적어 놓은 뒤 수학적으로 풀어보고자 할 수 있다. 이렇게 하는 사람들은 이 분야에서 실패한다. 물리적인 관점에서 시작하고, 자신이 어디로 갈지 대략 파악한 뒤 올바른 근사를 제시함으로써 복잡한 상황에서 무엇이 크고 무엇이 작은지 아는 사람이 성공한다. 이러한 문제들은 매우 복잡하여, 비록 부정확하고 불완전하더라도 기본적인 이해를 가질 가치가 있으며, 따라서 물리학 과정을 진행하면서 우리는 그 과목을 점점 더 정확하게 반복해서 검토하게 될 것이다.</p></li>
<li><p>고등학교때 배운 것이 있다.</p>
<ul>
<li>아보가드로의 법칙 : 같은 부피의 기체가 동일한 압력과 온도에서 동일한 수의 분자를 포함하고 있다 :아보가드로의 법칙<br>
</li>
<li>기체반응의 법칙 : 두 기체가 화학 반응에서 결합할 때 필요한 부피 사이에는 항상 단순한 정수 비율이 존재한다</li>
</ul></li>
</ul>
</section>
<section id="열역학" class="level4">
<h4 class="anchored" data-anchor-id="열역학"><strong>열역학</strong></h4>
<p>이 주제는 비원자론적 관점에서 공격될 수 있으며, 물질들의 특성들 사이에 많은 상호관계가 존재한다는 것을 알게 될 것이다. 예를 들어, 무언가를 압축하면 가열되고, 가열하면 팽창한다. 이 두 사실 사이에는 관계가 있으며, 이 관계는 배후의 과정과 독립적으로 추론될 수 있다. 이 주제를 <strong>열역학 (thermodynamics)</strong> 라고 한다. 열역학에 대한 가장 심오한 이해는 당연히 실제 그 아래에 있는 과정을 이해하는 데서 비롯되며 우리는 그것을 하려 한다. 우리는 시작부터 원자론적 관점으로 물질의 다양한 특성과 열역학 법칙을 이해하고자 한다.</p>
<p><br></p>
</section>
</section>
<section id="sec-FLP_1_39_2" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="sec-FLP_1_39_2">I.39-2 기체의 압력</h3>
<div id="fig-FLP_1_39_1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_39_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_39/fig_1_39_1.png" class="img-fluid figure-img" width="200">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_39_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.9: 파인만 물리학 강의 I. 그림 39-1 마찰 없는 피스톤이 있는 상자의 기체 원자들
</figcaption>
</figure>
</div>
<p>위의 그림과 같이 마찰이 이 움직일 수 있는 피스톤이 한 면을 차지하고 있는 부피 <span class="math inline">\(V\)</span> 인 상자에 기체 원자가 차 있다고 하자. 다양한 속도로 움직이는 기체 원자가 피스톤에 충돌한다. 만악 상자 외부가 진공이라면 기체 원자가 피스톤과 충돌하면서 피스톤이 운동량을 얻게 되어 점차 밖으로 이동하게 된다. 피스톤이 밖으로 움직이는 것을 막기 위해서 힘 <span class="math inline">\(F\)</span> 를 가한다고 하자. 그리고 피스톤의 단면적을 <span class="math inline">\(A\)</span> 라고 하자. 그렇다면 힘은 <span class="math inline">\(A\)</span> 에 비례할 것이며 이 때 <span class="math inline">\(A\)</span> 에 곱해지는 값을 <strong>압력 (pressure)</strong> 라고 정의한다. 즉, 압력 <span class="math inline">\(P\)</span> 를 다음과 같이 정의한다.</p>
<p><span id="eq-FLP_1_39_1"><span class="math display">\[
P=\dfrac{F}{A}.
\tag{3.14}\]</span></span></p>
<div class="page-columns page-full"><p>또한 미소 일(differential work) <span class="math inline">\(dW\)</span> 를 피스톤이 <span class="math inline">\((-dx)\)</span> 만큼 움직였을 때 기체에 해준 일로 정의한다<span class="math inline">\(^2\)</span>.</p><div class="no-row-height column-margin column-container"><span class="margin-aside"><span class="math inline">\(^2\)</span> 많은 교제애서 반대로 일을 기체가 한 일로 정의하기도 한다. 여기서는 파인만의 정의를 따른다.</span></div></div>
<p><span id="eq-FLP_1_39_2"><span class="math display">\[
dW = F(-dx) = -PA\,dx = -PdV.
\tag{3.15}\]</span></span></p>
<p>힘 <span class="math inline">\(F\)</span> 를 알기 위해서는 단위 시간당 공기 분자의 충돌로 전딜되는 운동량을 계산해야 한다. <span class="math inline">\(F=dp/dt\)</span>. 우선 피스톤이 분자에 대한 완벽한 <em>반사체</em> 라고 가정하자. 그렇지 않다면 피스톤이 가열되기 시작하고 상황이 변하게 되지만, <u>결국 평형상태가 되면 최종 결과는 사실상 완전히 탄성충돌이 된다.</u></p>
<p>초당 운동량은 두부분으로 나누어 계산한다. (1) 특정 분자 하나가 피스톤과 충돌할 때 피스톤에 전달한 운동량을 구하고, (2) 거기에 분자가 벽과 초당 충돌한 횟수를 구한다. 그렇다면 힘은 이 두 요인의 곱이다. 평균적으로, 충돌 전과 후의 입자의 에너지는 같다. 따라서 우리는 기체가 정적 상태(steady state)에 있다고 가정하며, 피스톤이 정지해 있기 때문에 피스톤에 에너지를 잃지 않을 것이다. 이러한 상황에서는 입자의 충돌 전 후의 속도가 같다.</p>
<p>상자의 부피 <span class="math inline">\(V\)</span> 와 기체 분자의 개수 <span class="math inline">\(N\)</span> 으로부터 단위 부피당 개수, 즉 개수 밀도 (number density) <span class="math inline">\(n=N/V\)</span> 를 생각 할 수 있다. 그리고 피스톤이 움직이는 방향을 <span class="math inline">\(x\)</span> 방향이라고 하자. 그리고 모든 분자들이 같은 속력 <span class="math inline">\(v_x\)</span> 를 가진다고 하자. 이제 짧은 시간 <span class="math inline">\(dt\)</span> 동안 피스톤과 충돌하는 분자들은 피스톤으로부터의 거리가 <span class="math inline">\(v_x dt\)</span> 안에 있어야 하며 피스톤의 면적이 <span class="math inline">\(A\)</span> 이므로 피스톤과 충돌할 수 있는 분자들의 부피는 <span class="math inline">\(v_x A dt\)</span> 라고 생각 할 수 있다. 그러나 <span class="math inline">\(v_x\)</span> 의 속력을 가진 분자 가운데 반은 피스톤으로 멀어지는 속도를 가지며 따라서 피스톤과 충돌하지 않기 때문에 <span class="math inline">\(dt\)</span> 의 시간동안 피스톤과 충돌하는 기체 분자의 개수는 <span class="math inline">\(nv_xA\,dt/2\)</span> 이다. 이제 속도가 <span class="math inline">\(v_x\)</span> 인 입자가 피스톤에 충돌하고 반사됬을 때의 운동량의 변화량은 <span class="math inline">\(2mv_x\)</span> 이며 <span class="math inline">\(dt\)</span> 의 시간동안의 충돌 횟수는 <span class="math inline">\(v_x A\,dt\)</span> 이므로 피스톤에 전달되는 힘 <span class="math inline">\(F\)</span> 는</p>
<p><span id="eq-FLP_1_39_3"><span class="math display">\[
F = \dfrac{1}{2}nmv_x A \cdot 2mv_x = nmAv_x^2
\tag{3.16}\]</span></span></p>
<p>이며, 따라서 피스톤에 가해지는 압력 <span class="math inline">\(P\)</span> 는</p>
<p><span id="eq-FLP_1_39_4"><span class="math display">\[
P = nmv_{x}^2
\tag{3.17}\]</span></span></p>
<p>이다. 지금까지는 기체 분자들이 모두 같은 속력을 가진다고 가정했지만 실제로는 그렇지 않다. 따라서 <span class="math inline">\(v_x^2\)</span> 는 평균값으로 바뀌어야 한다.</p>
<p><span id="eq-FLP_1_39_5"><span class="math display">\[
P = nm \left\langle v_x^2 \right\rangle.
\tag{3.18}\]</span></span></p>
<p>또한 우리는 모든 방향에 대해 속도가 등방적이라는 것을 가정 할 수 있다. 따라서</p>
<p><span id="eq-FLP_1_39_6"><span class="math display">\[
\left\langle v_x^2\right\rangle = \left\langle v_y^2\right\rangle =\left\langle v_z^2\right\rangle
\tag{3.19}\]</span></span></p>
<p>일 것이며</p>
<p><span id="eq-FLP_1_39_7"><span class="math display">\[
\left\langle v_x^2\right\rangle  = \dfrac{1}{3}\left\langle v_x^2 + v_y^2+v_z^2\right\rangle = \dfrac{1}{3}\left\langle v^2 \right\rangle
\tag{3.20}\]</span></span></p>
<p>이다. 이를 이용하면 압력을 다음과 같이 쓸 수 있다.</p>
<p><span id="eq-FLP_1_39_8"><span class="math display">\[
P = \dfrac{2}{3} n \left\langle\dfrac{1}{2}mv^2\right\rangle .
\tag{3.21}\]</span></span></p>
<p>위 식에서 속도의 제곱의 평균이 아니라 운동에너지의 평균을 사용한 이유는 <u>분자의 질량중심의 운동에너지 이기 때문이다</u>. 이제 <span class="math inline">\(n=N/V\)</span> 로부터</p>
<p><span id="eq-FLP_1_39_9"><span class="math display">\[
PV = \dfrac{2}{3}N\left\langle\dfrac{1}{2}mv^2\right\rangle
\tag{3.22}\]</span></span></p>
<p>임을 안다. 분자 내부의 들뜸이나 운동을 무시할 경우 질량중심의 운동에너지가 전체 에너지이다. 단원자 분자의 경우는 운동에너지가 전체 에너지이며 분자의 에너지의 합 <span class="math inline">\(U\)</span> 는 운동에너지의 평균에 분자의 개수를 곱한 값이므로 <a href="#eq-FLP_1_39_9" class="quarto-xref">식&nbsp;<span>3.22</span></a> 에 의해</p>
<p><span id="eq-FLP_1_39_10"><span class="math display">\[
PV = \dfrac{2}{3}U
\tag{3.23}\]</span></span></p>
<p>이다. 분자의 에너지의 합을 <strong>총 내부 에너지(total internal energy)</strong> 라고 하며 열역학에서 <span class="math inline">\(U\)</span> 는 총 내부 에너지를 의미한다. 그러나 단원자 분자가 아닌 다른 분자의 경우 분자 내 진동과 같은 내부의 운동이 있으므로 위 식이 적용되지 않고 계산이 훨씬 복잡하다. 일단 이 경우는 이후에 다루기로 하자.</p>
<p>이제 새로운 문제를 생각해보자. 주어진 기체를 <u>천천히</u> 압축시킨다면 얼마만큼의 압력이 필요한가? 압축한다는 것은 부피를 줄인다는 것이므로 우리가 기체에 일을 해주며 따라서 <span class="math inline">\(U\)</span> 가 증가한다. <span class="math inline">\(U\)</span> 가 증가하고 <span class="math inline">\(V\)</span> 가 감소하므로 당연히 <span class="math inline">\(P\)</span> 는 증가한다. 우리는 이에 대해 미분방정식을 세워 풀 수 있다. 그런데 여기에 한가지 가정이 숨어 있다. 우리가 기체를 압축시키면서 해주는 일이 모두 내부에너지로 변환된다는 것이다. 우리가 생각해야 할 다른 요인은 <strong>열 (heat)</strong> 이다. 빠르게 움직이는 분자가 벽을 치면 벽을 뜨겁게 하며 에너지가 사라진다. 하지만 당분간 이것을 무시하기로 하자.</p>
<p><a href="#eq-FLP_1_39_9" class="quarto-xref">식&nbsp;<span>3.22</span></a> 은 좀 더 일반적인 형태로 아래와 같이 쓸 수 있다. 여기서 <span class="math inline">\(\gamma\)</span> 와 같은 단일 문자가 아니라 <span class="math inline">\((\gamma-1)\)</span> 이 곱해지는 것은 역사적인 이유이다.</p>
<p><span id="eq-FLP_1_39_11"><span class="math display">\[
PV = (\gamma-1)U.
\tag{3.24}\]</span></span></p>
<p><a href="#eq-FLP_1_39_9" class="quarto-xref">식&nbsp;<span>3.22</span></a> 는 <span class="math inline">\(\gamma = \frac{5}{3}\)</span> 인 경우이다. 앞서 기체 분자에서 벽으로의(혹은 외부로의) 에너지 유출이 없다고 했는데 이를 <strong>단열 압축 (adiabatic compression)</strong> 이라고 한다. 이 경우 <span class="math inline">\(dU = -PdV\)</span> 이며, 또한 <a href="#eq-FLP_1_39_11" class="quarto-xref">식&nbsp;<span>3.24</span></a> 로 부터 <span id="eq-FLP_1_39_12"><span class="math display">\[
dU = \dfrac{1}{\gamma-1} (PdV + VdP)
\tag{3.25}\]</span></span></p>
<p>이므로 <span class="math inline">\(\gamma\)</span> 를 상수라고 가정하면 다음 관계를 얻는다.</p>
<p><span id="eq-FLP_1_39_14"><span class="math display">\[
PV^\gamma = \text{constant}.
\tag{3.26}\]</span></span></p>
<p>즉 단원자 분자에서는 <span class="math inline">\(PV^{5/3}\)</span> 은 항상 상수이다. 이는 실험적으로도 잘 맞다.</p>
<p><br></p>
</section>
<section id="sec-FLP_1_39_3" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_39_3">I.39-3 복사의 압축</h3>
<p>다수의 광자가 내부가 고온인 상자 안이 있다고 하자. 이 상자는 실제 고온의 별이며 내부에 원자는 무시할 만큼만 있을 정도이다. 태양은 이 기준으로는 충분히 뜨겁지 않다. 일단 광자가 운동량 <span class="math inline">\(\boldsymbol{p}\)</span> 를 가진다고 하자. 광자가 벽에 전달하는 운동량은 <span class="math inline">\(2p_x\)</span> 이고, <span class="math inline">\(dt\)</span> 의 시간 간격 동안 충돌을 발생시키는 광자의 개수는 <span class="math inline">\(nv_xA\,dt/2\)</span> 이므로 (2로 나누어 지는 것은 <span class="math inline">\(v_x\)</span> 가 벽으로 향하는 방향과 벽의 반대쪽으로 향하는 방향을 가질 수 있으며 이중 반만 충돌을 일으키기 때문이다.)</p>
<p><span id="eq-FLP_1_39_15"><span class="math display">\[
PV = Np_xv_x
\tag{3.27}\]</span></span></p>
<p>을 얻는다. <span class="math inline">\(p_xv_x\)</span> 의 평균값은 <span class="math inline">\(\boldsymbol{p\cdot v}\)</span> 의 <span class="math inline">\(1/3\)</span> 로 간주할 수 있으므로</p>
<p><span id="eq-FLP_1_39_16"><span class="math display">\[
PV = \dfrac{1}{3} N\langle \boldsymbol{p\cdot v}\rangle
\tag{3.28}\]</span></span></p>
<p>이다. 광자의 운동량 <span class="math inline">\(p\)</span> 와 광속 <span class="math inline">\(c\)</span> 에 대해 광자의 에너지 <span class="math inline">\(E=pc\)</span> 이다. 상자 속의 광자의 총 에너지 <span class="math inline">\(U\)</span> 를 생각하면</p>
<p><span id="eq-FLP_1_39_17"><span class="math display">\[
PV = \dfrac{1}{3}U
\tag{3.29}\]</span></span></p>
<p>을 얻는다. 즉 광자에 대해서는 <span class="math inline">\(\gamma = 4/3\)</span> 이므로</p>
<p><span id="eq-FLP_1_39_18"><span class="math display">\[
PV^\text{4/3} = \text{constant.}
\tag{3.30}\]</span></span></p>
<p>이다.</p>
<p><br></p>
</section>
<section id="sec-FLP_1_39_4" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="sec-FLP_1_39_4">I.39-4 온도와 운동에너지</h3>
<p>지금까지 우리는 온도를 의도적으로 배재했다. 기체를 압축하면 분자의 에너지가 증가한며, 우리는 가스가 더 뜨거워진다고 말한다. 이것은 온도와 무슨 관련이 있을지 알아보자. 만약 우리가 실험을 단열 조건이 아닌 일정 온도 조건에서 수행하려고 한다면, 우리는 무엇을 하는 것인가? 기체 두 상자를 충분히 오래 나란히 두면 처음에 우리가 서로 다른 온도라고 부르는 상황에 있더라도 결국 같은 온도에 도달한다는 것을 알고 있다. 즉 등온조건은 사물들이 서로 충분히 오래 방치되어 상호작용했을 때의 최종 조건이다.</p>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">
<div id="exm-FLP_1_39_4_1" class="theorem example">
<p><span class="theorem-title"><strong>예제 3.4 (자유롭게 움직일 수 있는 피스톤으로 분리된 두종류의 기체 분자)</strong></span> &nbsp;</p>
<div id="fig-FLP_1_39_2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_39_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_39/fig_1_39_2.png" class="img-fluid figure-img" width="200">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_39_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.10: 파인만 물리학 강의 I. 그림 39-2. 피스톤으로 분리된 상자 안의 두 종류의 기체
</figcaption>
</figure>
</div>
<p>위의 그림과 같이 상자 안에 자유롭게 움직일 수 있는 피스톤으로 분리된 두 단원자 기체가 차 있다고 생각하자. (1) 의 기체 분자의 질량, 속도, 개수 밀도는 각각 <span class="math inline">\(m_1\)</span>, <span class="math inline">\(v_1\)</span>, <span class="math inline">\(n_1\)</span> 이며 (2) 는 <span class="math inline">\(m_2\)</span>, <span class="math inline">\(v_2\)</span>, <span class="math inline">\(n_2\)</span> 라고 하자. 평형이 성랍하는 상황은 두 기체가 피스톤에 작용하는 힘이 동일할 조건이며 이는 압력이 동일할 조건이다. <a href="#eq-FLP_1_39_9" class="quarto-xref">식&nbsp;<span>3.22</span></a> 로부터</p>
<p><span class="math display">\[
n_1 \left\langle \dfrac{m_1v_1^2}{2} \right \rangle = n_2 \left\langle \dfrac{m_2v_2^2}{2} \right \rangle
\]</span></p>
<p>을 얻는다. 그러나 우리는 이것이 유일한 조건이 아니라는 것을 알아야 한다. 예를 들어 (1) 에는 밀도가 크고 평균 속도가 작은 기체가, (2) 에는 밀도가 작고 평균속도가 큰 기체가 있는 상태에서 위 조건을 만족 할 수 있다. 이 경우 (1) 번 기체는 피스톤 벽을 더 많이 치고 (2) 번 기체는 피스톤 벽을 적게 치는 대신 더 세게 친다. 기체의 충돌은 일정하지 않고 불연속적이다. 이 불연속적인 충돌에 의해 피스톤은 끊임없이 흔들리며, 충돌은 정지한 피스톤과 움직이는 기체 분자 사이의 충돌이아닌 흔들리는 피스톤과 움직이는 기체 사이의 충돌이다. 이 와중에서 에너지의 전달이 일어난다. 이 시스템이 평형에 도달하는 것은 피스톤이 기체 원자로부터 에너지를 흡수하고, 원자에 에너지를 다시 공급할 수 있는 평균제곱속도로 움직일 때이다.</p>
</div>
</div>
<p><br></p>
<p>위의 예제는 중간에 멈췄다. 여기서 피스톤의 세부사항을 이해하는것은 이상적으로는 간단하지만, 분석하기는 다소 더 어렵다. 그것을 분석하기 전에, 기체 상자 안에 두 종류의 분자가 존재하는 또 다른 문제를 분석해 보자.</p>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">
<div id="exm-FLP_1_39_4_2" class="theorem example">
<p><span class="theorem-title"><strong>예제 3.5 (상자 안의 두종류의 기체 분자)</strong></span> 두 종류의 기체가 컨테이너 안에서 셖여 있다고 하자. 기체 분자의 질량은 각각 <span class="math inline">\(m_1,\,m_2\)</span> 이며 속도를 각각 <span class="math inline">\(\boldsymbol{v}_1,\,\boldsymbol{v}_2\)</span> 라고 하자. 기체 분자의 충돌은 탄성 충돌이라고 가정한다.</p>
<p>이 때 질량중심죄표계에서 보면 (<a href="../../ClassicalMechanics/12_two_or_three_bodies_problems.html#sec-CM_elastic_collition_in_C_frame">질량중심 좌표계에서의 탄성 충돌</a> 을 참고하라) 이 충돌은 두 입자의 속도의 크기는 일정하며 방향만 바뀌는 충돌이며 질량중심 좌표계에서 이 방향의 분포는 균일하다.</p>
<p>이제 실제 상황에서 보자. 서로 다른 두 분자의 충돌의 질량 중심 속도 <span class="math inline">\(\boldsymbol{V}\)</span> 와 상대속도 <span class="math inline">\(\boldsymbol{v}\)</span> 를 아래와 같이 정한다.</p>
<p><span class="math display">\[
\boldsymbol{v}_\text{CM}=\dfrac{m_1\boldsymbol{v}_1+m_2\boldsymbol{v}_2}{m_1+m_2},\qquad \boldsymbol{u} = \boldsymbol{v}_1-\boldsymbol{v}_2
\]</span></p>
<p>충돌 후에 원자의 분포는 어떻게 될까? 일단 우리는 충돌 전후 질량중심의 속도 <span class="math inline">\(\boldsymbol{v}_\text{CM}\)</span> 이 변하지 않는다는 것을 안다. 또한 <span class="math inline">\(\boldsymbol{u}\)</span> 의 분포는 <span class="math inline">\(\boldsymbol{v}_\text{CM}\)</span> 에 대해 완전히 임의적이다. 즉 <span class="math inline">\(\boldsymbol{v}_\text{CM}\boldsymbol{\cdot u}\)</span> 의 평균값은 <span class="math inline">\(0\)</span> 이다. 또한 <span class="math inline">\(\boldsymbol{v}_1\boldsymbol{\cdot v}_2\)</span> 의 평균값도 <span class="math inline">\(0\)</span> 이라는 데 동의 할 수 있다. 여기서</p>
<p><span class="math display">\[
\boldsymbol{v}_\text{CM}\boldsymbol{\cdot u} = \dfrac{(\boldsymbol{v}_1-\boldsymbol{v}_2) \boldsymbol{\cdot} (m_1\boldsymbol{v}_1 + m_2 \boldsymbol{v}_2)}{m_1+m+2} = \dfrac{(m_1v_1^2 - m_2v_2^2) + (m_2-m_1)(\boldsymbol{v}_1\boldsymbol{\cdot v}_2)}{m_1+m_2}
\]</span></p>
<p>이므로</p>
<p><span class="math display">\[
\left\langle \dfrac{m_1v_1^2}{2}\right\rangle = \left\langle \dfrac{m_2v_2^2}{2}\right\rangle
\]</span></p>
<p>이다. 즉 두 기체 분자의 평균 운동 에너지는 같아진다.</p>
</div>
</div>
<p><br></p>
<p>이제 두종류의 서로 다른 기체가 하나의 상자 안에 분리되어 있더라도 최종적으로 평형에 도달했을 때 평균 운동 에너지가 동일하다고 말하고자 한다.</p>
<div id="fig-FLP_1_39_4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_39_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_39/fig_1_39_4.png" class="img-fluid figure-img" width="200">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_39_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.11: 파인만 물리학 강의 I. 그림 39-4
</figcaption>
</figure>
</div>
<p><strong>1. 고정된 구획에 한 분자만 통과할 수 있는 구멍이 있는 경우</strong> : <a href="#fig-FLP_1_39_4" class="quarto-xref">그림&nbsp;<span>3.11</span></a> 를 생각하자. 한 기체는 구멍을 통과할 수 있지만 다른 기체는 불가능하다고 하자. 혼합된 오른쪽 부분에서는 두 기체가 동일한 평균 운동에너지를 가진다(<a href="#exm-FLP_1_39_4_2" class="quarto-xref">예제&nbsp;<span>3.5</span></a>). 여기서 통과 할 수 있는 기체분자의 일부는 운동 에너지 손실 없이 구멍을 통과하여 이동하며, 따라서 왼쪽의 기체의 평균 운동에너지도 동일하게 된다. 그러나 이 설명은 두 종류의 분자에 대해 한 종류를 다른 종류와 구분하는 구멍이 없을 수도 있기 때문에 만족스럽지 않다..</p>
<p><strong>2. 피스톤 문제 (<a href="#exm-FLP_1_39_4_1" class="quarto-xref">예제&nbsp;<span>3.4</span></a>)</strong> : <span class="math inline">\(m_1\)</span> 분자들과 피스톤의 평형을 생각하자. 피스톤의 운동은 수평운동이며 따라서 <span class="math inline">\(\frac{1}{2}m_2v^2_{2x}\)</span> 와 동일해야 한다. 마찬가지로, 반대편의 평형으로부터 우리는 피스톤의 운동 에너지가 <span class="math inline">\(\frac{1}{2}m_1v^2_{1x}\)</span> 임을 증명할 수 있다. 비록 이것이 기체의 중간이 아니라 한쪽에 위치하지만 피스톤과 가스 분자의 평균 운동 에너지가 모든 충돌의 결과로 동일하다는 것을 다소 어렵게나마 보일 수 있다. <u>(How ?) </u></p>
<p><strong>3. 서로 섞이지 않지만 열적으로 연결된 경우</strong> : 이제 모든 면에서 타격할 수 있는 물체에 의해 평형상태에 도달하는 인위적인 예를 들 수 있다. 피스톤을 통해 각 끝에 볼이 삽입된 짧은 막대가 마찰 없는 슬라이딩 유니버설 조인트 위에 있다고 가정해 보자. 각 공은 분자 중 하나와 같이 둥글며, 모든 면에서 타격받을 수 있다. 이 물체의 총 질량을 <span class="math inline">\(m\)</span> 이라고 하고 이전과 같이 질량 <span class="math inline">\(m_1\)</span>, <span class="math inline">\(m_2\)</span> 인 가스 분자가 양쪽에 있다고 하자. 충돌의 결과 한쪽에 있는 분자와의 충돌로 인한 <span class="math inline">\(m\)</span> 의 운동 에너지는 평균 <span class="math inline">\(\frac{1}{2}m_1v^2_1\)</span> 이어야 한다. 마찬가지로, 반대편에 있는 분자와의 충돌 때문에 평균은 <span class="math inline">\(\frac{1}{2}m_2v^2_2\)</span> 이어야 한다. 따라서 양측은 열평형 상태에 있을 때 동일한 운동 에너지를 가져야 한다. <a href="#exm-FLP_1_39_4_2" class="quarto-xref">예제&nbsp;<span>3.5</span></a> 에서 기체 혼합물에 대해서만 증명했지만, 같은 온도에서 서로 다른 두 개의 별개의 기체가 존재하는 경우에도 쉽게 된다. 따라서 우리는 다음과 같은 결론을 내릴 수 있다.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">중요</span><strong>온도와 에너지</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p>두 기체가 같은 온도에 있을 때, 질량중심 운동의 평균 운동 에너지는 동일하다.</p>
</div>
</div>
<p>평균 분자 운동 에너지는 오직 “온도” 의 속성일 뿐이며 기체의 속성이 아니기 때문에, 우리는 이를 온도의 정의로 사용할 수 있다. 즉 분자의 평균 운동 에너지는 온도의 함수이다. 온도를 평균 에너지에 비례하도록 정하고 그 비례상수로 <strong>볼츠만 상수 (Boltzmann constant)</strong></p>
<p><span id="eq-FLP_definition_of_boltzmann_constant"><span class="math display">\[
k_B = 1.380 649 \times 10^{−23} \text{ J}\cdot \text{K}^{-1}
\tag{3.31}\]</span></span></p>
<div class="page-columns page-full"><p>를 사용한다. 따라서 <span class="math inline">\(T\)</span> 가 절대 온도라면, 우리의 정의에 따르면 평균 분자 운동 에너지는 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 이다<span class="math inline">\(^3\)</span>.</p><div class="no-row-height column-margin column-container"><span class="margin-aside"><span class="math inline">\(^3\)</span> 앞으로 배우겠지만 특정 방향으로의 운동 성분과 연관된 운동 에너지가 단지 <span class="math inline">\(\frac{1}{2}k_B T\)</span> 임을 보일 수 있으며 이를 <strong>등분배 정리(equipartition theorem)</strong> 라고 한다. 세개의 독립적인 방향을 가지므로 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 이 된다.</span></div></div>
<p><br></p>
</section>
<section id="sec-FLP_1_39_5" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_39_5">I.39-5 이상기체법칙</h3>
<section id="단원자-분자의-이상기체법칙" class="level4">
<h4 class="anchored" data-anchor-id="단원자-분자의-이상기체법칙"><strong>단원자 분자의 이상기체법칙</strong></h4>
<p>앞서 말했듯이 분자의 평균 온동에너지가 <span class="math inline">\(\frac{3}{2}k_B T\)</span> 이므로 <a href="#eq-FLP_1_39_9" class="quarto-xref">식&nbsp;<span>3.22</span></a> 는 다음과 같다.</p>
<p><span id="eq-FLP_1_39_22"><span class="math display">\[
PV=Nk_BT.
\tag{3.32}\]</span></span></p>
<p>실용적으로는 분자 혹은 원자의 개수를 사용하지 않고 아보가드로수</p>
<p><span class="math display">\[
N_A=6.02214076 × 10^{23}
\]</span></p>
<p>를 단위로 <span class="math inline">\(N_A\)</span> 의 몇배인지를 센다. 즉 <span class="math inline">\(N=\nu N_A\)</span> 일 때 <span class="math inline">\(\nu\)</span> 를 분자 혹은 원자의 몰수라고 한다. 또한 기체상수 <span class="math inline">\(R\)</span> 을</p>
<p><span id="eq-FLP_definition_of_gas_constant"><span class="math display">\[
R=N_A k_B = 8.314\,462\,618\,153\,24 \;\text{J}\cdot \text{mol}^{−1}\cdot \text{K}^{−1}
\tag{3.33}\]</span></span></p>
<p>로 정의하면</p>
<p><span id="eq-FLP1_39_23"><span class="math display">\[
PV = \nu RT
\tag{3.34}\]</span></span></p>
<p>이다.</p>
<p>지금까지 단원자 기체의 원자들의 질량중심 운동만을 다루었다. 여기에 힘이 존재하면 어떻게 될까? 우선 피스톤이 수평 스프링에 의해 지지되고 그 위에 힘이 작용하는 경우를 생각해보자. 물론, 원자와 피스톤 사이의 흔들림 운동 교환은 피스톤의 위치에 따라 달라지지 않는다. 평형 조건은 동일하다. 피스톤이 어디에 있든, 그 운동 속도는 분자에 에너지를 정확히 전달하도록 해야 하며 따라서 스프링에 대해서는 차이가 없다. 피스톤이 이동해야 하는 속도는 평균적으로 동일하며 따라서 한 방향에서 운동 에너지의 평균값이 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 라는 우리 정리는 힘이 존재하든 존재하지 않든 참이다.</p>
</section>
<section id="이원자-분자의-경우" class="level4">
<h4 class="anchored" data-anchor-id="이원자-분자의-경우"><strong>이원자 분자의 경우</strong></h4>
<p>이제 <span class="math inline">\(m_A\)</span> 와 <span class="math inline">\(m_B\)</span> 원자로 구성된 이원자 분자를 생각하자. <span class="math inline">\(A\)</span> 와 <span class="math inline">\(B\)</span> 의 질량중심 운동이 평형상태에서<br>
<span class="math display">\[
\left\langle \dfrac{1}{2}m_Av^2_A\right\rangle = \left\langle \dfrac{1}{2}m_B v^2_B\right\rangle =\dfrac{3}{2}k_BT
\]</span></p>
<p>이다. 이 둘이 서로 묶여있는데 어떻게 <span class="math inline">\(m_A\langle v_A^2\rangle = m_B \langle v_B^2\rangle\)</span> 이 가능할까? 비록 그들이 서로 고정되어 있더라도, 자기 위치에서 돌거나 다른 위치를 중심으로 회전할 때, 무언가와 충돌하여 에너지를 교환한다면 중요한 것은 그들이 얼마나 빠르게 움직이는가이다. 그것만으로도 충돌에서 에너지를 교환하는 속도를 결정한다. 특정 상황에서는 힘은 필수적인 요인이 아니다. 따라서 같은 원리는 힘이 있을 때조차도 옳다.</p>
<p>마지막으로, 기체 법칙이 내부 운동과 무관하게 성립한다는 것을 증명해보자. 우리는 이전에 내부 움직임을 포함하지 않는 단원자 기체만을 다뤘다. 하지만 이제 우리는 전체 물체를 질량 <span class="math inline">\(M\)</span> 인 단일 물체로 간주하면 질량 중심 속도 <span class="math inline">\(\boldsymbol{v}_\text{CM}\)</span> 에 대해 다음을 만족한다.</p>
<p><span id="eq-FLP_1_39_24"><span class="math display">\[
\left\langle \dfrac{1}{2}Mv_{\text{CM}}^2 \right \rangle = \dfrac{3}{2}k_BT
\tag{3.35}\]</span></span></p>
<p>다시 말해, 우리는 개별 부분들을 고려하거나 전체를 고려하건 간에 운동에너지의 평균은 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 이다.</p>
<p>그 이유를 살펴보자: 이원자 분자의 질량 <span class="math inline">\(M = m_A+m_B\)</span>, 질량 중심의 속도 <span class="math inline">\(\boldsymbol{v}_\text{CM}=(m_A\boldsymbol{v}_A+m_B\boldsymbol{v}_B)/M\)</span> 에 대해 <span class="math inline">\(\left\langle \boldsymbol{v}_\text{CM}^2\right\rangle\)</span> 을 계산해 보자.</p>
<p><span class="math display">\[
v^2_\text{CM} = \dfrac{m_A^2v_A^2 + 2m_Am_B \boldsymbol{v}_A\boldsymbol{\cdot v}_B + m_B^2v_B^2}{M^2}
\]</span></p>
<p>이므로</p>
<p><span class="math display">\[
\begin{aligned}
\left\langle \dfrac{1}{2}Mv^2_\text{CM}\right \rangle &amp;= \dfrac{1}{M}\left(m_A \left\langle \dfrac{1}{2}m_A v_A^2\right\rangle + m_B \left\langle \dfrac{1}{2}m_B v_B^2\right\rangle + m_Am_B\langle \boldsymbol{v}_A\boldsymbol{\cdot v}_B\rangle \right) \\[0.3em]
&amp;= \dfrac{1}{M}\left(m_A \dfrac{3}{2}k_BT + m_B \dfrac{3}{2}k_B T + m_Am_B\langle \boldsymbol{v}_A\boldsymbol{\cdot v}_B\rangle \right) \\[0.3em]
&amp;= \dfrac{3}{2}k_BT + \dfrac{m_Am_B\langle \boldsymbol{v}_A\boldsymbol{\cdot v}_B\rangle }{M}
\end{aligned}
\]</span></p>
<p>이다. 이제 <span class="math inline">\(\langle \boldsymbol{v}_A\boldsymbol{\cdot v}_B\rangle=0\)</span> 임을 보이자. 상대속도 <span class="math inline">\(\boldsymbol{u}=\boldsymbol{v}_A-\boldsymbol{v}_B\)</span> 에 대해 <span class="math inline">\(\boldsymbol{u}\)</span> 는 특정 방향을 선호하지 않으므로</p>
<p><span class="math display">\[
\langle \boldsymbol{u \cdot v}_\text{CM}\rangle =0
\]</span></p>
<p>이다. 여기서</p>
<p><span class="math display">\[
\begin{aligned}
\boldsymbol{u\cdot v}_\text{CM} &amp;= \dfrac{(\boldsymbol{v}_A-\boldsymbol{v}_B)\boldsymbol{\cdot}(m_A\boldsymbol{v}_A+ m_B\boldsymbol{v}_B)}{M} \\[0.3em]
&amp;= \dfrac{m_Av_A^2 - m_B v_B^2 + (m_A-m_B)(\boldsymbol{v}_A\boldsymbol{\cdot v}_B)}{M}
\end{aligned}
\]</span></p>
<p>이며 우리는 <span class="math inline">\(\langle m_Av_A^2 \rangle = \langle m_B v_B^2\rangle\)</span> 임을 안다. 따라서 <span class="math inline">\(\boldsymbol{v}_A\boldsymbol{\cdot v}_B=0\)</span> 임을 알 수 있다. 즉 분자 하나를 하나의 입자로 간주해도 그 평균 운동에너지는 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 이다.</p>
<p>또한 이로부터 이원자 분자의 내부 운동에 대한 평균 운동 에너지가 질량중심의 운동을 제외하고 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 임을 알 수 있다.예를 들어, 분자의 각 부분들의 총 운동 에너지는 <span class="math inline">\(\frac{1}{2}m_Av^2_A+\frac{1}{2}m_Bv^2_B\)</span> 이며, 평균은 <span class="math inline">\(\frac{3}{2}k_BT+\frac{3}{2}k_BT =3k_BT\)</span> 이다. 질량 중심 운동의 운동 에너지는 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 이므로, 분자 내부 두 원자의 회전 및 진동 운동 평균 운동 에너지 차이는 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 이다.</p>
<p>질량 중심 운동의 평균 에너지에 관한 정리는 일반적이며, 전체로 고려될 때 힘이 있든 없든 모든 독립된 운동 방향에 대해 그 운동의 평균 운동 에너지는 <span class="math inline">\(\frac{1}{2}k_B T\)</span> 이다. 이러한 ‘독립적인 운동 방향’ 은 때때로 시스템의 <strong>자유도 (degree of freedom)</strong> 라고 불린다. <span class="math inline">\(r\)</span> 개의 원자로 구성된 분자의 자유도는 그 위치를 정의하기 위해 세 개의 좌표가 필요하기 때문 <span class="math inline">\(3r\)</span> 이다. 분자의 전체 운동 에너지는 개별 원자들의 운동 에너지의 합 혹은 CM 운동의 운동 에너지와 내부 운동의 운동 에너지의 합으로 표현될 수 있다. 후자는 때때로 분자의 회전 운동 에너지와 진동 에너지의 합으로 표현될 수 있지만, 이는 근사값이다. 우리의 정리는 <span class="math inline">\(r\)</span>-원자 분자에 적용된 것으로, 분자는 평균적으로 <span class="math inline">\(3rk_BT/2\)</span> 의 운동 에너지를 갖게 되며, 그 중 <span class="math inline">\(\frac{3}{2}k_B T\)</span> 는 전체 분자의 질량 중심 운동에 대한 운동 에너지이고, 나머지 <span class="math inline">\(\frac{3}{2}(r−1)k_B T\)</span> 는 내부 진동 및 회전 운동 에너지이다.</p>
<p><br></p>
</section>
</section>
</section>
<section id="i.40.-통계역학의-원리" class="level2">
<h2 class="anchored" data-anchor-id="i.40.-통계역학의-원리">I.40. 통계역학의 원리</h2>
<section id="sec-FLP_1_40_1" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_40_1">I.40.1 지수적 대기</h3>
<p>지금까지 다수의 서로 충돌하는 원자들의 일부 특성에 대해 알아보았다. 이 주제를 분자 운동론(kinetic theory) 이라고 하며, 원자 간 충돌의 관점에서 물질을 기술한다. 근본적으로, 우리는 물질의 많은 특성이 부분들의 운동으로 설명될 수 있어야 한다고 주장한다. 여기서 열평형 조건에만 한정하여 적용되는 역학 법칙은 통계역학(statistical mechanics) 이라고 하며, 이 절에서는 통계역학의 몇가지 핵심 정리를 다룬다.</p>
<p>우리는 이미 통계역학의 정리 중 하나인 등분배 정리를 통해 절대 온도 <span class="math inline">\(T\)</span> 에서의 모든 운동에 대한 운동 에너지의 평균값은 자유도마다 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 임을 안다. 이제 우리는 두 가지 질문을 던질 수 있다: 분자에 힘이 작용할 때 분자는 우주에서 어떻게 분포하고, 그리고 그 분자들의 속도는 어떻게 분포하는가? 두 질문은 완전히 독립적이며, 속도 분포는 항상 동일함이 밝혀졌습다. 우리는 이미 후자의 사실에 대한 힌트를 받았으며, 분자에 작용하는 힘과 관계없이 자유도당 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 의 동일한 평균 운동 에너지를 가진다는 것을 안다. 분자들의 속도 분포는 힘과 무관하며, 충돌 속도는 힘에 의존하지 않기 때문이다. 이제 한가지 예로부터 시작하자.</p>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">
<div id="exm-TD_feynmann_1" class="theorem example">
<p><span class="theorem-title"><strong>예제 3.6 (높이에 따른 압력의 변화)</strong></span> &nbsp;</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fig_1_40/fig_1_40_1.png" class="img-fluid figure-img" width="300"></p>
<figcaption>파인만 물리학 강의 I. 그림 40-1</figcaption>
</figure>
</div>
<p>예를 들어 보자: 우리가 아는 대기와 같은 분자 분포를 갖지만 바람 및 기타 다양한 교란이 없는 경우이다. 높이까지 뻗어 있고 열평형 상태에 있는 기체 기둥이 있다고 가정하자. 높은 위치에서 차가운 우리가 아는 대기와는 다르다.그림과 같이 위와 아래의 공기의 출입은 막으면서 열만을 전달해주는 메카니즘을 설치했다고 하자. 이를 통해 위 와 아래의 기체의 온도는 결곡 같아진다.</p>
<p>이제 온도가 모든 높이에서 일정하다면 문제는 높이가 올라갈수록 공기가 희박해지게 하는 이유를 알아보자. 온도 <span class="math inline">\(T\)</span>, 압력 <span class="math inline">\(P\)</span>, 부피 <span class="math inline">\(V\)</span>, 볼츠만 상수 <span class="math inline">\(k_B\)</span>, 공기 분자 개수 <span class="math inline">\(N\)</span> 에 대해 <span class="math inline">\(PV=Nk_BT\)</span> 이며 개수분포 <span class="math inline">\(n=N/V\)</span> 이다. 이로부터 <span class="math inline">\(P=n k_BT\)</span> 임을 알며 <span class="math inline">\(T\)</span> 가 일정하므로 <span class="math inline">\(P \propto n\)</span> 이다. 그런데 압력 자체는 낮은 높이에서 해야 하는데 이는 낮은 위치의 기체는 높은 위치의 기체보다 더 많은 (위의 기체가 누르는) 힘을 버텨여 하기 때문이다. <span class="math inline">\(h+dh\)</span> 높이에서 아래쪽을 누르는 단위 면적당 수직으로 작용하는 힘은 은 중력이 없을 경우 동일하지만, 중력이 작용하면 아래에서의 힘이 <span class="math inline">\(h\)</span> 와 <span class="math inline">\(h+dh\)</span> 사이의 구간에서 기체 무게를 더하여 위에서 가해야 하기 때이다. 기체 분자의 질량이 <span class="math inline">\(m\)</span> 이라면</p>
<p><span class="math display">\[
P_{h+dh}-P_h = dP = -mgn\,dh
\]</span></p>
<p>이며 <span class="math inline">\(P = nk_BT\)</span> 으로부터 <span class="math inline">\(dP = dnk_B T\)</span> 임을 안다. 따라서</p>
<p><span class="math display">\[
\dfrac{dn}{dh}= - \dfrac{mg}{k_B T}n
\]</span></p>
<p>이며 이 미분방정식의 해는 <span class="math inline">\(h=0\)</span> 일 때의 개수 밀도를 <span class="math inline">\(n_0\)</span> 라고 했을 때 아래와 같다.</p>
<p><span id="eq-FLP_1_40_1"><span class="math display">\[
n(h) = n_0 e^{-mgh/k_BT}.
\tag{3.36}\]</span></span></p>
</div>
</div>
<p><br></p>
<p>다른 질량의 분자는 각각 다른 지수로 감소한다는 것을 알 수 있다. 무거운 분자는 가벼운 분자보다 더 빨리 감소한다. 이에 따르면 산소가 질소보다 무거우며 이로부터 점점 더 높아질수록 질소 비율이 증가하겠지만 실제 대기에서는, 적어도 합리적인 고도에서는 기체가 활발하게 섞이기 때문에 그렇지 않다. 또한 등온도 아니다. 그럼에도 불구하고 수소와 같은 가벼운 분자가 대기 중 매우 높은 고도에서 우세하게 나타나는 경향이 있다.</p>
</section>
<section id="sec-FLP_1_40_2" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_40_2">I.40-2 볼츠만 법칙</h3>
<p><a href="#eq-FLP_1_40_1" class="quarto-xref">식&nbsp;<span>3.36</span></a> 은 다음의 형태이다.</p>
<p><span class="math display">\[
e^{-\text{원자 1개당 포텐셜 에너지}/k_B T}.
\]</span></p>
<p>그것은 사고일 수 있으며, 즉 균일한 중력장의 특정 경우에만 해당될 수 있습니다. 하지만, 우리는 그것이 보다 일반적인 명제임을 보여줄 수 있습니다. 가스의 분자에 중력이 아닌 다른 종류의 힘이 작용했다고 가정해 보십시오. 예를 들어, 분자는 전기적으로 전하를 띤 수 있으며, 전기장이나 이를 끌어당기는 다른 전하에 의해 작용할 수 있습니다. 또는 원자들이 서로, 혹은 벽이나 고체, 혹은 무언가에 대한 상호 끌림 때문에, 위치에 따라 달라지는 끌어당김 힘이 존재하여 모든 분자에 작용합니다. 이제 간단히 가정해 보겠습니다. 분자들은 모두 동일하고, 힘이 각각에 작용하므로 기체 한 조각에 작용하는 전체 힘은 단순히 분자 수에 각 분자에 작용하는 힘을 배한 것입니다. 불필요한 복잡성을 피하기 위해, 힘의 방향인 F를 x축으로 하는 좌표계를 선택합시다.</p>
<p>이겻은 <a href="#exm-TD_feynmann_1" class="quarto-xref">예제&nbsp;<span>3.6</span></a> 에서 제시한 특정 상황-균일한 중력장-에서만 성립하는 명제가 아니라 일반적인 상황에서 성립하는 명제임을 보일 수 있다. 동일한 기체 분자에 중력이 아닌 다른 종류의 힘이 작용한다고 가정하자. 분자들은 모두 동일하고, 힘이 각각에 작용하므로 한 부분에 작용하는 힘은 한 분자에 작용하는 힘에 부분의 분자의 개수를 곱한 값이다.</p>
<p>기체 안의 <span class="math inline">\(d\boldsymbol{r}\)</span> 만큼 떨어진 두 평행한 평면을 생각하자. 각 원자에 가해지는 힘 <span class="math inline">\(\boldsymbol{F}\)</span>, 기체 분자의 개수 밀도 <span class="math inline">\(n\)</span>, 그리고 <span class="math inline">\(d\boldsymbol{r}\)</span> 을 곱한 값은 두 평면의 압력 차와 균형을 이루어야 한다. 따라서</p>
<p><span class="math display">\[
n\boldsymbol{F \cdot}d\boldsymbol{r} = dP = k_BT dn
\]</span></p>
<p>이므로</p>
<p><span class="math display">\[
\boldsymbol{F} = k_BT \left(\nabla \ln n\right)
\]</span></p>
<p>이다. <span class="math inline">\(\boldsymbol{F}\)</span> 가 보존력으로 <span class="math inline">\(\boldsymbol{F}=-\nabla U(\boldsymbol{r})\)</span> 라면 포텐셜 <span class="math inline">\(U\)</span> 와 어떤 상수 <span class="math inline">\(n_0\)</span> 에 대해</p>
<p><span id="eq-FLP_1_40_3"><span class="math display">\[
n = n_0 e^{-U/k_BT}
\tag{3.37}\]</span></span></p>
<p>이어야 한다. 여기서 <span class="math inline">\(\boldsymbol{F}\)</span> 가 보존력이 아니라면 <a href="#eq-FLP_1_40_3" class="quarto-xref">식&nbsp;<span>3.37</span></a> 는 더이상 해가 아니며 열역학적 평형에 도달 할 수 없다. <a href="#eq-FLP_1_40_3" class="quarto-xref">식&nbsp;<span>3.37</span></a> 을 <strong>볼츠만 법칙 (Boltzmann’s law)</strong> 라고 하며 이로부터 주어진 공간 배치에서 분자를 찾을 확률은 그 배치의 위치 에너지의 음수를 <span class="math inline">\(k_BT\)</span> 로 나눈 값에 따라 지수적으로 변한다는 것을 알 수 있다.</p>
<p><br></p>
</section>
<section id="sec-FLP_1_40_3" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_40_3">I.40-3 액체의 증발</h3>
<p>분자들의 집합을 생각하자. 이 분자들 사이에는 쌍마다 서로의 거리만 의존하는 상호작용, 즉 포텐셜 에너지가 존재한다. 이 때 두 분자 사이의 거리 <span class="math inline">\(r\)</span> 에 따른 포텐셜 <span class="math inline">\(V(r)\)</span> 은 일반적으로 아래 그림과 같은 형태이며 <span class="math inline">\(r&lt;r_0\)</span> 일 때는 척력이 <span class="math inline">\(r&gt;r_0\)</span> 일 때는 인력이 작용한다.</p>
<div id="fig-FLP_1_40_3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_40_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_40/fig_1_40_3.png" class="img-fluid figure-img" width="300">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_40_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.12: 파인만 물리학 강의 I 그림 40-3(redraw)
</figcaption>
</figure>
</div>
<p>이런 기체 분자로 차 있는 상자를 생각하자. 이 기체 분자들 사이의 포텐셜은 각 개별 쌍의 포텐셜의 합이라고 가정하자. (세개 이상에 대한 상호작용도 존재한다(<a href="https://en.wikipedia.org/wiki/Three-body_force">Three-body force</a> 를 참고하라.) 그렇다면 볼츠만의 법칙에 따라 분자 쌍이 <span class="math inline">\(r_{ij}\)</span> 만큼의 거리를 두고 존재할 확률은 다음에 비례한다.</p>
<p><span class="math display">\[
\exp \left[-\sum_{i,j} V(r_{ij})/k_BT\right].
\]</span></p>
<ul>
<li><span class="math inline">\(k_BT \gg |V(r_{0})|\)</span> 일 경우 위 값은 거의 모든 곳에서 <span class="math inline">\(1\)</span> 에 가깞다. 즉 온도가 매우 높을 경우 분자를 발견할 확률은 위치에 거의 무관하게 된다.</li>
<li><span class="math inline">\(k_BT \ll |V(r_0)|\)</span> 인 경우 <span class="math inline">\(r=r_0\)</span> 주위에서 발견할 확률이 매우 크다.</li>
</ul>
<p>증발현상을 이해하려면 다음을 알아야 한다.</p>
<ul>
<li><p><span class="math inline">\(V(r)\)</span> 은 양자역학 혹은 실험을 통해 발견한다. 하지만 분자들 사이의 힘의 법칙을 고려하면 수십억 개의 분자가 무엇을 할지를 알아내는 것은 단지 함수 <span class="math inline">\(\exp (- \sum V_{ij}/k_BT)\)</span> 를 연구하는 것에 불과하다. 이는 매우 단순한 함수이자 매우 쉬운 아이디어이지만 변수의 수가 매우 많기 때문에 어렵다. 그러나 이 문제는 소위 “다체 문제” 의 한 예이며 매우 흥미로운 분야이다. 이 식에는 기체의 응고나 고체의 결정의 형태와 같은 모든 세부 사항이 포함되어야 하며, 사람들의 노력에도 불구하고 수학적으로 방대한 변수들을 다루는 것이 어렵다.</p></li>
<li><p>이후 공간에서 입자들의 분포를 알아낸다. 그것은 고전 통계역학의 목표이다. 실제로 힘을 알면 원칙적으로 공간에서의 분포를 찾을 수 있고, 속도의 분포는 각각의 경우와 무관하게 한 번에 해결될 수 있다.</p></li>
</ul>
<p><br></p>
</section>
<section id="sec-FLP_1_40_4" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_40_4">I.40-4 분자 속력의 분포</h3>
<section id="지수적-대기의-경우" class="level4">
<h4 class="anchored" data-anchor-id="지수적-대기의-경우"><strong>지수적 대기의 경우</strong></h4>
<p>이제 속도의 분포에 대해 알아보자. 이를 위해 앞서 대기에서 발견한 사실들을 활용한다. 일단 대기의 기체를 이상기체로 간주한다. 따라서 원자들간의 상호작용은 일단 생각하지 않으며 중력에 의한 위치에너지만 생각하며 충돌을 무시하더라도 차이가 없다(잠시 후 다룬다). <a href="#eq-FLP_1_40_1" class="quarto-xref">식&nbsp;<span>3.36</span></a> 에 따르면 공기의 밀도는 올라갈수록 지수적으로 감소한다. 그리고 이로부터 주어진 높이 <span class="math inline">\(h_0\)</span> 를 오를 만큼 충분한 속도를 갖지 못한 분자의 분포를 알 수 있다.</p>
<p>우선 <span class="math inline">\(h_0&gt;0\)</span> 을 정하자. 그리고 <span class="math inline">\(h=0\)</span> 에서 <span class="math inline">\(z\)</span> 방향의 속도를 가진 입자가 <span class="math inline">\(h_0\)</span> 에 간신히 도달할때의 속도를 <span class="math inline">\(u\)</span> 라고 하자. <span class="math inline">\(mgh_0 = \frac{1}{2}mu^2\)</span> 로부터 <span class="math inline">\(u\)</span> 를 알 수 있다. 그렇다면 평형상태에서</p>
<p><span class="math display">\[
\left[\begin{array}{c}h=0\text{ 인 평면을 } v_z&gt;u \\ \text{ 의 속도로 통과하는 입자의 개수} \end{array}\right]= \left[ \begin{array}{c} h=h_0\text{ 인 평면을 } v_z &gt;0 \\ \text{ 의 속도로 통과하는 입자의 개수} \end{array}\right]
\]</span></p>
<p>이 성립해야 한다. 또한 우리는 <span class="math inline">\(h=0\)</span> 을 <span class="math inline">\(v_z&gt;0\)</span> 으로 통과하는 분자의 개수가 <span class="math inline">\(h=h_0\)</span> 를 <span class="math inline">\(v_z&gt;0\)</span> 으로 통과하는 분자의 개수보다 많다는 것을 안다. 두 높이에서 온도가 동일하며 <a href="#eq-FLP_1_40_1" class="quarto-xref">식&nbsp;<span>3.36</span></a> 로부터 <span class="math inline">\(n(0) &gt; n(h_0)\)</span> 이기 때문이다. 이로부터 우리는 다음을 얻을 수 있다.</p>
<p><span id="eq-FLP_velocity_distribution_of_exponential_air"><span class="math display">\[
\dfrac{n_{v_z&gt;u}(0)}{n_{v_z&gt;0}(0)}=\dfrac{n(h_0)}{n(0)}=e^{-mgh_0/k_BT} = e^{-mu^2/2k_BT}.
\tag{3.38}\]</span></span></p>
<p>위 식은 임의로 선택된 높이 <span class="math inline">\(0\)</span> 뿐만 아니라 다른 높이에서도 참이며, 따라서 속도 분포는 모두 동일하며, 결과적으로 속도 분포를 제시하는 일반 명제이다. 가스 파이프 측면에 매우 작은 구멍을 뚫어 충돌 간격이 적고, 즉 구멍의 직경보다 더 멀리 떨어지게 하면, 나오는 입자들의 속도가 달라지지만, <span class="math inline">\(u\)</span> 보다 큰 속도로 나오는 입자의 비율은 <span class="math inline">\(e^{−mu^2/2k_BT}\)</span> 이다.</p>
</section>
<section id="충돌을-고려한다면" class="level4">
<h4 class="anchored" data-anchor-id="충돌을-고려한다면"><strong>충돌을 고려한다면?</strong></h4>
<p>충돌을 무시해도 차이가 없다는 것을 보이자. 이제 유한한 높이 <span class="math inline">\(h\)</span> 가 아니라 충돌의 여지가 거의 없는 무한소 높이 <span class="math inline">\(dh\)</span> 를 사용해도 동일한 결론이 난다. 우리가 생각할 것은 포텐셜 및 운동에너지와 에너지 보존, 충돌시 분자들 간의 에너지 교환이다. 하지만 에너지가 단지 다른 분자와 교환되는 경우 중요한 것은 동일한 분자를 추적하는 지가 아니라 분포이며 이 경우 결과에는 여전히 차이가 없다는 것이 밝혀졌다.</p>
</section>
<section id="확률분포표현" class="level4">
<h4 class="anchored" data-anchor-id="확률분포표현"><strong>확률분포표현</strong></h4>
<p><a href="#eq-FLP_velocity_distribution_of_exponential_air" class="quarto-xref">식&nbsp;<span>3.38</span></a> 와 속도의 분포는 순전히 온도에 의해 결정된다는 사실로부터 <span class="math inline">\(u\)</span> <u>보다 큰 속도로 정해진 높이의 평면을 통과하는 기체 분자의 밀도</u> <span class="math inline">\(n_{&gt;u}\)</span> 가 다음을 만족한다는 것을 안다.</p>
<p><span id="eq-FLP_1_40_4"><span class="math display">\[
n_{&gt;u} \propto e^{-mu^2/2k_BT}.
\tag{3.39}\]</span></span></p>
<p>이것을 수학적으로 더 다루기 쉽게 표현하는 방법은 확률분포함수를 사용하는 것이다. 속도 <span class="math inline">\(u\)</span> 에 대한 확률분포함수는</p>
<p><span id="eq-FLP_1_40_5"><span class="math display">\[
\int_{-\infty}^\infty f(u)\,du = 1
\tag{3.40}\]</span></span></p>
<p>를 만족하며 <a href="#eq-FLP_1_40_4" class="quarto-xref">식&nbsp;<span>3.39</span></a> 에 대해</p>
<p><span id="eq-FLP_1_40_6"><span class="math display">\[
\int_{u}^\infty uf(u)\,du =\text{const.} \cdot e^{-mu^2/2k_BT}
\tag{3.41}\]</span></span></p>
<p>이어야 한다. 적분인자가 왜 <span class="math inline">\(f(u)\)</span> 가 아닐까? 그것은 <span class="math inline">\(n_{&gt;u}\)</span> 가 어떤 높이의 속도 분포가 아니라 어떤 높이에서 정해진 평면을 통과하는 입자의 분포와 관련이 있기 때문에다. 즉 빠른 입자는 더 많이 통과한다. 정해진 <span class="math inline">\(dt\)</span> 동안 특정한 면을 통과하는 입자의 개수는 <span class="math inline">\(u\,dt\)</span> 에 비례한다는 것을 압력을 도입할 때 사용했다. <a href="#eq-FLP_1_40_6" class="quarto-xref">식&nbsp;<span>3.41</span></a> 와 <a href="#eq-FLP_1_40_5" class="quarto-xref">식&nbsp;<span>3.40</span></a> 로부터</p>
<p><span id="eq-FLP_1_40_7"><span class="math display">\[
f(u) \,du=\sqrt{\dfrac{m}{2\pi k_B T}}e^{-mu^2/2k_BT} \,du
\tag{3.42}\]</span></span></p>
<p>임을 알 수 있다.</p>
<p>속도와 운동량이 비례하므로, 운동량의 분포도 단위 운동량 범위당 <span class="math inline">\(e^{−\text{K.E.}/k_BT}\)</span> 에 비례한다고 말할 수 있다. 상대성 이론에는 속도가 아니라 운동량에 대해서만 성립하므로 운동량 <span class="math inline">\(p\)</span> 를 이용하여 기억하는 것이 좋다.</p>
<p><span id="eq-FLP_1_40_8"><span class="math display">\[
f(p) \,dp = C e^{-\text{K.E.}/k_BT} \, dp.
\tag{3.43}\]</span></span></p>
<p>따라서 우리는 운동에너지 및 퍼텐셜 에너지에 대한 확률이 모두 <span class="math inline">\(e^{−\text{energy}/k_BT}\)</span> 로 주어진다는 것을 알게되었다.</p>
</section>
<section id="속도-분포" class="level4">
<h4 class="anchored" data-anchor-id="속도-분포"><strong>속도 분포</strong></h4>
<p>지금까지 우리는 지수적 대기로부터 속도의 분포를 유도하였으며 이는 특정 방향에 대한 속도 분포만을 생각했다는 의미이다. 당연히 다른 방향에 대한 분포, 그리고 속도의 크기의 분포에 관심이 있다. 후자의 경우 당연히 방향과 무관한 것이어야 하며 속도의 크기의 제곱에만 의존하는 함수여야 한다. <span class="math inline">\(v_z\)</span> 에 대한 분포로부터 속도의 분포함수 <span class="math inline">\(f(v_x,\,v_y,\,v_z)\)</span> 가 다음과 같다는 것을 이해 할 수 있다.</p>
<p><span id="eq-FLP_1_40_9"><span class="math display">\[
f(v_x,\,v_y,\,v_z)\,dv_x dv_y dv_z \propto e^{-(mv_x^2+mv_y^2+mv_z^2)/2k_BT} \,dv_x dv_y dv_z .
\tag{3.44}\]</span></span></p>
<p><br></p>
</section>
</section>
<section id="sec-FLP_1_40_5" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_40_5">I.40-5 기체의 비열</h3>
<p>이제 우리는 이론을 검증하는 몇 가지 방법을 살펴보고, 가스에 대한 고전 이론이 얼마나 성공적인지 살펴보자.</p>
<ul>
<li>단원자 기체의 경우 <span class="math inline">\(PV\)</span> 는 원자들의 질량 중심 운동의 운동 에너지의 <span class="math inline">\(\frac{2}{3}\)</span> 과 동일하다는 것과 운동 에너지는 내부 에너지와 같다는 것을 안다. 따라서 <a href="#eq-FLP_1_39_11" class="quarto-xref">식&nbsp;<span>3.24</span></a> 에서 <span class="math inline">\(\gamma -1 =\frac{2}{3}\)</span> 임을 안다.</li>
<li>보다 복잡한 분자라고 가정하면 회전 혹은 진동이 가능하다(고전 역학에 따르면 사실임이 밝혀졌다). 이 경우 내부 운동의 에너지도 <span class="math inline">\(k_BT\)</span> 에 비례한다고 가정해 보자. 그렇다면 주어진 온도에서 운동 에너지 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 외에 내부 진동 및 회전 에너지를 가지고 있으며 따라서 단원자 분자와는 다른 <span class="math inline">\(\gamma\)</span> 값을 생각해야 한다.</li>
</ul>
<p>기술적으로, <span class="math inline">\(\gamma\)</span> 를 측정하는 가장 좋은 방법은 비열을 측정하는 것이며, 이는 온도에 따른 에너지의 변화를 의미한다. 우리는 <span class="math inline">\(\gamma\)</span> 를 단열 압축시의 <a href="#eq-FLP_1_39_14" class="quarto-xref">식&nbsp;<span>3.26</span></a> 에서 실험적으로 구한다고 가정하자.</p>
<p>일부 경우에 대해 <span class="math inline">\(γ\)</span> 를 계산해 보자. 우선 단원자 기체의 경우 <span class="math inline">\(\gamma = \frac{5}{3}\)</span> 임을 안다. 산소(O<sub>2</sub>), 요오드화수소(HI), 수소(H<sub>2</sub>) 와 같은 이원자 분자 기체의 경우 <a href="#fig-FLP_1_40_3" class="quarto-xref">그림&nbsp;<span>3.12</span></a> 와 같은 포텐셜이 존재한다고 가정할 수 있다. 이 경우 관심 있는 온도에서는 원자 쌍이 대부분 <span class="math inline">\(r_0\)</span> 만큼 분리된다. 이것이 성립하지 않는다면 원자로 존재하는 비율이 무시할수 없을 만큼 크다는 의미이다. 우리는 실제로 단일 산소 원자가 매우 적다는 것을 알고 있으며, 이는 <span class="math inline">\(|V(r_0)| \gg k_BT\)</span> 임을 의미한다. 따라서 포텐셜은 <span class="math inline">\(r_0\)</span> 근처의 2차함수로 근사할 수 있고 이는 조화 진동자를 의미한다. 실제로 산소 분자는 스프링으로 연결된 두 원자로 잘 근사된다.</p>
<p>이제 온도 <span class="math inline">\(T\)</span> 에서 이 분자의 총 에너지를 구해보자. 두 원자 각각의 운동 에너지가 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 이므로 두 원자의 운동 에너지의 합은 <span class="math inline">\(3k_BT\)</span> 이다. 이를 다른 방식으로 표현하면 질량 중심의 운동 에너지 <span class="math inline">\(\frac{3}{2}k_BT\)</span>, 회전의 운동 에너지 <span class="math inline">\(\frac{2}{2}k_BT\)</span>, 그리고 진동의 운동 에너지 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 로도 볼 수 있다. 진동의 운동 에너지는 하나의 차원에만 관여하며 따라서 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 이다. 회전과 관련해서는 두 축 중 하나를 중심으로 회전할 수 있으므로 두 개의 독립적인 운동이 존재한다. 우리는 원자들이 일종의 점이며, 그것들을 연결하는 선을 중심으로 을 회전할 수 없다고 가정한다. 만약 불일치를 발견할 경우 이것이 문제일 수 있으므로 주의해야 한다. 여기에 진동의 포텐셜 에너지를 생각해야 한다. 조화 진동에서는 평균 운동 에너지와 평균 위치 에너지가 동일하므로, 진동의 위치 에너지도 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 이다. 에너지의 총합은 <span class="math inline">\(U=\frac{7}{2}k_BT\)</span> 이며, <span class="math inline">\(k_BT\)</span>는 원자당 <span class="math inline">\(\frac{2}{7}U\)</span> 이다. 즉, <span class="math inline">\(\gamma\)</span> 는 <span class="math inline">\(\frac{5}{3}\)</span> 이 아니라 <span class="math inline">\(\frac{9}{7}\)</span>, 즉 <span class="math inline">\(\gamma=1.286\)</span> 이다.</p>
<div style="margin-right: 100px; margin-bottom: 30px;margin-left: 100px;">
<div class="center-table">
<div id="tbl-FLP_1_40_1" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-FLP_1_40_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
표&nbsp;3.1: 여러 기체에서의 <span class="math inline">\(\gamma\)</span> 값
</figcaption>
<div aria-describedby="tbl-FLP_1_40_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">기체</th>
<th style="text-align: right;">온도 (<span class="math inline">\(^\circ\,\text{C}\)</span>)</th>
<th style="text-align: right;"><span class="math inline">\(\gamma\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">He</td>
<td style="text-align: right;">-180</td>
<td style="text-align: right;">1.660</td>
</tr>
<tr class="even">
<td style="text-align: center;">Kr</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">1.68</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ar</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">1.668</td>
</tr>
<tr class="even">
<td style="text-align: center;">H<sub>2</sub></td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.404</td>
</tr>
<tr class="odd">
<td style="text-align: center;">O<sub>2</sub></td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.399</td>
</tr>
<tr class="even">
<td style="text-align: center;">HI</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.40</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Br<sub>2</sub></td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">1.32</td>
</tr>
<tr class="even">
<td style="text-align: center;">I<sub>2</sub></td>
<td style="text-align: right;">185</td>
<td style="text-align: right;">1.30</td>
</tr>
<tr class="odd">
<td style="text-align: center;">NH<sub>3</sub></td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">1.310</td>
</tr>
<tr class="even">
<td style="text-align: center;">C<sub>2</sub>H<sub>6</sub></td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">1.22</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="xec-FLP_1_40_6" class="level3">
<h3 class="anchored" data-anchor-id="xec-FLP_1_40_6">I.40-6 고전역학의 실패</h3>
<p>위의 불일치를 해결하기 위해 조화진동이 이외의 다른 힘의 법칙을 시도할 수도 있지만, 다른 어떤 것이든 <span class="math inline">\(U\)</span> 를 더 크게 만들 뿐이며 더 많은 형태의 에너지를 포함한다면, <span class="math inline">\(\gamma\)</span> 는 <span class="math inline">\(1\)</span> 에 더 가깝게 접근하게 되고 이는 사실과 모순된다. 생각할 수 있는 모든 고전 이론적 것들은 상황을 더욱 악화시킬 뿐이다. 실제로는 각 원자에 전자가 존재하고, 그들의 스펙트럼을 통해 내부 운동이 존재한다는 것을 알 수 있습니다; 각 전자는 최소 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 의 운동 에너지를 가져야 하며, 이는 퍼텐셜 에너지에 해당하므로 이를 더하면 <span class="math inline">\(\gamma\)</span> 가 더욱 작아진다. 이것은 터무니없이 잘못되었다.</p>
<p>기체의 동역학 이론에 관한 최초의 위대한 논문은 맥스웰의 1859 논문이다. 우리가 논의해 온 아이디어를 바탕으로, 그는 보일의 법칙, 확산 이론, 기체의 점도, 그리고 다음 장에서 논의할 내용 등 많은 알려진 관계들을 정확하게 설명할 수 있었다. 그는 최종 요약에 이러한 위대한 성공들을 모두 열거한 후, 마지막에 이렇게 말했다. “마침내 모든 입자들의 평행 이동과 회전 운동(그는 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 정리) 사이의 필수적인 관계를 확립함으로써, 그러한 입자들의 시스템이 두 비열 사이의 알려진 관계를 만족시킬 수 없음을 증명했습니다.” 그는 <span class="math inline">\(\gamma\)</span> 를 언급하고 있으며(이는 비열을 측정하는 두 가지 방법과 관련이 있다), 그리고 정답을 얻을 수 없다는 것을 알고 있다고 말했다.</p>
<p>10년 후 한 강연에서 멕스웰은 “이제 나는 분자 이론이 지금까지 겪은 가장 큰 어려움이라고 생각되는 것을 여러분 앞에 제시합니다.”라고 말했다. 이는 고전 물리학의 법칙이 잘못되었다는 최초의 표현이며 엄밀하게 증명된 정리가 실험과 일치하지 않았기 때문에 근본적으로 불가능한 것이 존재한다는 최초의 징표였다. 1905년경, 제임스 홉우드 진스 경과 레일리 경(존 윌리엄 스트럿)이 다시 이 퍼즐에 대해 이야기하기도 했다. 사람들은 종종 19세기 후반의 물리학자들이 모든 중요한 물리 법칙을 알고 있었으며, 소수점 자리수를 더 계산하기만 하면 된다고 생각했다는 말을 듣는다. 누군가가 한 번 그렇게 말했을 수도 있고, 다른 사람들은 그것을 베꼈다. 하지만 당시 문헌을 면밀히 읽어보면 그들은 모두 무언가에 대해 걱정하고 있었다. 진스 경은 이 퍼즐이 매우 신비로운 현상이며, 온도가 낮아질 때 특정 종류의 움직임이 “얼어붙는” 것처럼 보인다고 말했다.</p>
<p>예를 들어 진동 운동이 저온에서는 존재하지 않고 고온에서도 존재했다고 가정한다면, 기체가 진동 운동이 일어나지 않을 정도로 충분히 낮은 온도에서 존재할 수 있다고 상상할 수 있으며, 따라서 진동이 존재하지 않는 낮은 온도에서는 <span class="math inline">\(\gamma=1.40\)</span> 이며 더 높은 온도에서 진동이 도입되면 <span class="math inline">\(\gamma\)</span> 가 낮아진다고 할 수 있다. 동일한 것이 회전에 대해서도 주장될 수 있다. 충분히 낮은 온도에서 회전이 사라져 “얼어붙는다”고 말할 수 있다면, 낮은 온도에서 수소의 <span class="math inline">\(\gamma\)</span> 가 <span class="math inline">\(1.66\)</span> 에 가까워진다는 사실을 이해할 수 있다. 물론 이러한 운동이 “얼어붙는” 것은 고전 역학으로는 이해될 수 없으며 양자역학을 통해 이해될 수 있었다.</p>
<p>양자역학 이론의 통계역학 결과를 증명 없이 진술해보자. 양자역학에 따르면 포텐셜에 의해 구속된 시스템은 이산적인 에너지 준위, 즉 서로 다른 에너지 상태를 갖게 된다는 것을 기억하자. 이제 양자역학에 의해 통계역학은 어떻게 수정해야 하는가가 문제이다. 흥미롭게도, 대부분의 문제는 고전 역학보다 양자역학에서 더 어려운 반면, 통계역학의 문제는 양자 이론에서 훨씬 쉽다! 고전 역학에서 우리가 도출하는 간단한 결과인 <span class="math inline">\(n = n_0 e^{−\text{에너지/}k_BT}\)</span> 는 다음과 같은 매우 중요한 정리가 된다: 예를 들어, 분자 상태 집합의 에너지가 <span class="math inline">\(E_0\)</span>, <span class="math inline">\(E_1\)</span>, <span class="math inline">\(E_2\)</span>, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(E_i\)</span>, <span class="math inline">\(\ldots\)</span> 라고 하면, 열평형 상태에서 에너지 <span class="math inline">\(E_i\)</span> 를 가진 특정 상태에 있는 분자를 찾을 확률은 <span class="math inline">\(e^{-E_i/k_BT}\)</span> 에 비례한다. 즉 상태 <span class="math inline">\(E_1\)</span> 에 있을 확률과 상태 <span class="math inline">\(E_0\)</span> 에 있을 확률에 대한 상대적인 확률은</p>
<p><span id="eq-FLP_1_40_10"><span class="math display">\[
\dfrac{P_1}{P_0} = \dfrac{e^{-E_1/k_BT}}{e^{-E_0/k_BT}},
\tag{3.45}\]</span></span></p>
<p>이며 이는 <span class="math inline">\(P_1 = n_1/N,\, P_0=n_0/N\)</span> 이므로 다음 식과 같다.</p>
<p><span id="eq-FLP_1_40_11"><span class="math display">\[
n_1=n_0e^{-(E_1-E_0)/k_BT}.
\tag{3.46}\]</span></span></p>
<p>이에 따르면 낮은 에너지 상태보다 높은 에너지 상태에 있을 가능성이 낮다.</p>
<p>양자역학에 따르면 조화 진동자의 경우 에너지 레벨이 고르게 배치되어 있다. 가장 낮은 에너지 <span class="math inline">\(E_0=\frac{1}{2}\hbar \omega\)</span> 에 대해 <span class="math inline">\(k\)</span> 번째 들뜬 상태의 에너지 <span class="math inline">\(E_k\)</span> 는 다음과 같다.</p>
<p><span id="eq-FLP_energy_level_of_quantum_mechanical_harmonic_oscillator"><span class="math display">\[
E_k = \left(\dfrac{1}{2}+k\right)\hbar \omega.
\tag{3.47}\]</span></span></p>
<p>이제 무슨 일이 일어나는지 보자. 우리는 이원자 분자의 진동을 조화 진동자로 근사하여 연구한다. 상태 <span class="math inline">\(E_0\)</span> 가 아닌 상태 <span class="math inline">\(E_1\)</span> 에서 분자를 찾을 수 있는 상대적인 확률은 무엇일까? 답은 상태 <span class="math inline">\(E_1\)</span> 에서 그것을 찾을 확률이 상태 <span class="math inline">\(E_0\)</span> 에서 찾을 확률에 비해 <span class="math inline">\(e^{−\hbar \omega/k_BT}\)</span> 로 감소한다는 것이다. 이제 <span class="math inline">\(k_BT\)</span> 가 <span class="math inline">\(\hbar \omega\)</span> 보다 훨씬 작면, 즉 저온이라면 <span class="math inline">\(E_1\)</span> 상태에 있을 확률은 매우 낮으며 실질적으로 모든 원자는 <span class="math inline">\(E_0\)</span> 상태에 있다. 온도를 변화시키되 여전히 매우 작게 유지한다면, 그 상태가 <span class="math inline">\(E_1=\hbar \omega\)</span> 에 있을 확률은 무한히 작게 된다. 즉 진동자의 에너지는 거의 <span class="math inline">\(E_0\)</span> 에 가깝다. 온도가 <span class="math inline">\(\hbar \omega\)</span> 보다 훨씬 낮을 경우 온도에 따라 변하지 않습니다. 모든 진동자는 바닥 상태에 있으며, 그 움직임은 실질적으로 “동결” 되어 있고 비열에 기여하지 않는다. 따라서 <a href="#tbl-FLP_1_40_1" class="quarto-xref">표&nbsp;<span>3.1</span></a> 에서 우리는 100 <span class="math inline">\(^\circ \text{C}\)</span> 에서 <span class="math inline">\(k_BT\)</span> 가 산소 또는 수소 분자의 진동 에너지보다 훨씬 낮지만, 요오드 분자에서는 그렇지 않다는 것을 판단할 수 있다. 이 차이의 이유는 요오드 원자가 수소에 비해 매우 무겁기 때문이다. 요오드와 수소에서 힘이 비슷할 수 있지만 요오드 분자는 너무 무거워서 진동의 고유 주파수가 수소의 고유 주파수에 비해 매우 낮다. 수소의 경우 실온에서 <span class="math inline">\(\hbar \omega\)</span> 가 <span class="math inline">\(k_BT\)</span> 보다 높고, 요오드의 경우 낮으며, 오직 후자인 요오드만이 고전적인 진동 에너지를 나타낸다. 기체의 온도를 매우 낮은 <span class="math inline">\(T\)</span> 값부터 상승시키면, 분자들이 거의 모두 바닥상태에 있을 다가 점차 첫 번째 들뜬상태에 있을 확률이 크게 높아지고, 온도가 더 높아지면 더 높은 에너지의 상태에 있을 확률이 높아진다. 많은 상태에 대해 확률이 크게 나타날 때, 기체의 거동은 고전 물리학이 제시한 것에 근접하게 된다. 이는 양자화된 상태가 에너지 연속체와 거의 구별되지 않게 되며, 시스템은 거의 모든 에너지를 가질 수 있기 때문이다. 따라서 온도가 상승함에 따라 우리는 다시 고전 물리학의 결과를 얻어야 한다. 원자의 회전 상태도 양자화된다는 것을 같은 방식으로 보여줄 수 있지만, 이 상태들의 에너지 차이는 일반적으로 <span class="math inline">\(k_BT\)</span> 보다 작으며 따라서 시스템 내 회전 운동 에너지가 고전적인 방식으로 참여힌다. 실온에서 이것이 완전히 사실이 아닌 한 가지 예는 수소이다.</p>
<p>이번이 우리가 실험과 비교하여 고전 물리학에 문제가 있음을 진정으로 추론한 첫 번째 경우이며, 우리는 실재 그랬던 것과 거의 동일한 방식으로 난관의 해결착을 양자역학에서 찾았다. 다음 난관 발견되기까지 30~40년이 걸렸으며, 역시 통계역학과 관련이 있었지만 이번에는 광자기체의 역학이었다. 그 문제는 20세기 초에 플랑크에 의해 해결되었다.</p>
<p><br></p>
</section>
</section>
<section id="sec-FLP_1_41" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-FLP_1_41">I.41. 브라운 운동</h2>
<section id="sec-FLP_1_41-1" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="sec-FLP_1_41-1">I.41-1 에너지의 등분배</h3>
<p>브라운 운동은 1827년에 식물학자 로버트 브라운에 의해 발견되었다. 그는 현미경으로 액체 안에서 식물 꽃가루의 작은 입자들이 흔들리는 것을 관찰했으며, 그것이 살아있는 것이 아니라 물속에서 움직이는 작은 먼지 조각에 불과하다는 것을 인식했다. 사실 그는 물을 가둔 석영 조각을 땅에서 얻었는데 이는 생명과 무관함을 입증하는 데 도움이 되었다. 그것은 수백만 년 동안 갇혀 있었던 것이 틀림없지만, 그 안에서 같은 움직임을 볼 수 있었다. 보이는 것은 매우 작은 입자들이 계속해서 흔들리고 있다는 것이었다.</p>
<p>이는 나중에 분자 운동의 효과 중 하나임이 입증되었다. 우리는 이전 장에서 액체나 기체에 매달린 작은 입자가 분자에 비해 매우 무겁지만 그 평균 운동 에너지가 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 임을 알고 있다. 그것이 그것이 매우 무겁고, 따라서 속도가 비교적 느리더라도 그렇게 느리지 않다는 것이 밝혀졌다. 직경이 1~2 마이크론인 물체의 경우 <span class="math inline">\(1 \text{mm}/\text{sec}\)</span> 정도이다. 그런데 현미경에서도 이를 확인하기 매우 어려운데 이는 입자가 지속적으로 방향을 전환하여 어디에도 도달하지 않기 때문이다. 얼마나 진행되는지는 현재 장의 끝에서 논의하겠다. 이 문제는 20세기 초에 아인슈타인에 의해 처음 해결되었다.</p>
<div class="page-columns page-full"><p>이 입자의 평균 운동 에너지가 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 라는 것은 운동 이론, 즉 뉴턴의 법칙에서 도출되었다. 우리는 동역학 이론으로부터 많은 놀라운 결론을 도출할 수 있다는 것을 확인하게 될 이다. 이렇게 매우 적은 것(뉴턴의 법칙이 “작다”는 뜻이 아니라, 우리가 많은 일을 하지 않을것이라는 의미에서)으로부터 많은 것을 얻을 수 있다는 점이 가장 흥미롭다. 이렇게 많은 결과를 얻을 수 있었던 것은 우리가 중요한 것-열역학 제 0 법칙-을 가정했기 때문이다<span class="math inline">\(^4\)</span>. </p><div class="no-row-height column-margin column-container"><span class="margin-aside"><span class="math inline">\(^4\)</span> 파인만은 명시적으로 열역학 제 0 법칙이라고 표현하지 않는다.</span></div></div>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">중요</span><strong>열역학 제 0 법칙</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p>한 계가 온도 <span class="math inline">\(T\)</span> 에서 열평형상태에 있다면 같은 온도 <span class="math inline">\(T\)</span> 인 다른 시스템과도 열평형 상태이다.</p>
</div>
</div>
<p>한 입자(입자란 말이 많이 나오니 이 한 입자를 <span class="math inline">\(q\)</span>-입자 라고 하자)가 물과 실제로 충돌할 때 어떻게 움직이는지 확인하고 싶다면, 물과 상호작용하지 않고 “hard” 충돌을 할 뿐인 물과 다른 작은 미세 공 입자로 구성된 기체가 존재한다고 상상할 수 있다. <span class="math inline">\(q\)</span>-입자에 뿔이 튀어나와 있다고 가정하면, 미세 공 입자는 그 뿔을 때란다. 우리는 온도 <span class="math inline">\(T\)</span> 에서 이 가상의 미세 공 입자 기체에 대해 모두 알고 있다—이는 이상기체이다. 물은 복잡하지만, 이상기체는 간단하다. 이제 우리 <span class="math inline">\(q\)</span>-입자는 미세 공 입자 기체와 평형 상태에 있어야 하며 따라서 <span class="math inline">\(q\)</span>-입자의 평균 운동은 기체 충돌에서 얻어지는 것과 같아야 한다. 왜냐하면 입자가 물에 비해 적절한 속도로 이동하지 않고, 예를 들어 <span class="math inline">\(q\)</span>-입자가 더 빠르게 움직이고 있다면, 이는 미세 공 입자 기체가 그로부터 에너지를 흡수하여 물보다 더 뜨거워진다는 의미이기 때문이다. 하지만 우리는 그것들을 같은 온도에서 시작했으며, 사물이 한 번 평형 상태에 있으면 평형 상태를 유지한다고 가정한다. 한 부분이 뜨거워지면서 동시에 다른 부분이 차가워지는 현상은 발생하지 않는다.</p>
<p>이 명제는 참이며 역학 법칙으로부터 증명될 수 있있지만 어려운 역학을 사용해야 하며 양자역학을 통해 증명하는 것이 훨씬 쉽다. 볼츠만에 의해 처음 증명되었으며 일단 사실로 받아들이자. 이에 따르면 입자가 물과 충돌하면서 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 의 에너지를 가진다면 물이 아니라 인위제걱인 미세 공 입자 기체와 충돌해서도 <span class="math inline">\(\frac{3}{2}k_BT\)</span> 를 가져야 한다. 이는 다소 이상한 논증이지만 완전히 타당하다.</p>
<p>브라운 운동이 처음 발견된 콜로이드 입자의 운동 외에도, 실험실 및 기타 상황에서 브라운 운동을 볼 수 있는 다양한 현상이 존재한다. 가능한 가장 섬세한 장비를 만들려고 한다면, 예를 들어 <a href="#fig-FLP_1_41_1" class="quarto-xref">그림&nbsp;<span>3.13</span></a> 과 같은 매우 정밀한 탄도 갈바노미터를 위해 얇은 석영 섬유 위에 아주 작은 거울을 설치하면, 거울은 제자리에 머무르지 않고 계속 흔들어 빛을 비추며 그 지점의 위치를 확인할 때 거울이 항상 흔들리기 때문에 완벽한 기기가 아닌데 이 거울의 회전 평균 운동 에너지는 평균적으로 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 이어야 하기 때문이다.</p>
<div id="fig-FLP_1_41_1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_41_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_41/fig_1_41_1.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_41_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.13: 파인만 물리학 강의 I. 그림 41-1. (a) 정밀 광선 갈바노미터. <span class="math inline">\(L\)</span> 로부터의 빛은 작은 거울에서 반사되어 자(scale) 로 향한다. (b) 시간에 따른 광선의 위치
</figcaption>
</figure>
</div>
<p>거울이 흔들리는 평균 제곱각을 알아보자. 한쪽을 살짝 두드려서 거울이 잠시 회전했다가 되돌아 오는 시간을 통해 거울의 회전의 자연진동수 <span class="math inline">\(\omega_0\)</span> 를 확인할 수 있다. 관성모먼트 <span class="math inline">\(I\)</span> 에 대해 회전 운동 에너지 <span class="math inline">\(T=\frac{1}{2}I\omega^2\)</span> 이며 위치 에너지는 <span class="math inline">\(V=\frac{1}{2}\alpha \theta^2\)</span> 이다. 거울의 자연진동수를 이용하면 위치 에너지는 <span class="math inline">\(V=\frac{1}{2}I\omega_0^2\theta^2\)</span> 이다. 우리는 단순조화진동자의 주기당 평균 운동에너지와 위치에너지가 같다는 사실과 1차원 운동의 평균 운동에너지가 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 임을 을 알고 있으며, 이로부터</p>
<p><span id="eq-FLP_1_41_4"><span class="math display">\[
\left\langle \theta^2 \right\rangle = k_BT/I\omega_0^2
\tag{3.48}\]</span></span></p>
<p>임을 안다. 이와 같이 우리는 갈바노미터 거울의 진동을 계산하고 이를 통해 기기의 한계를 알 수 있다. 더 작은 진동을 원한다면 거울을 식혀야 한다. 어디를? 이는 진동의 원인이 어디인지에 따라 다르다. 섬유를 통과한다면, 위쪽에서 냉각한다. 거울이 기체에 둘러싸여 기체 분자의 충돌로 진동하는 경우 가스를 냉각하는 것이 좋다. 실제로 진동의 감쇠가 어디에서 오는지 알면, 그것이 항상 요동의 원인이고 다시 살펴볼 지점이다.</p>
<div id="fig-FLP_1_41_2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_41_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_41/fig_1_41_2.png" class="img-fluid figure-img" width="300">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_41_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.14: 파인만 물리학 강의 I. 그림 41-2. 높은 <span class="math inline">\(Q\)</span> 값을 갖는 공명 회로 (a) 온도 <span class="math inline">\(T\)</span> 의 실제 회로 (b) 소음 없는 저항과 소음 발생기 <span class="math inline">\(G\)</span> 를 갖는 인위적인 회로
</figcaption>
</figure>
</div>
<p>동일한 현상이 전기 회로에서도 발생한다. 특정 주파수에 대해 매우 민감하고 정확한 증폭기를 제작하고, 입력에 공명 회로(<a href="#fig-FLP_1_41_2" class="quarto-xref">그림&nbsp;<span>3.14</span></a>)를 설치하여 라디오 수신기와 같이 해당 주파수에 매우 민감하게 만든다고 가정하자. 우리가 가장 낮은 한계까지 내려가고자 한다고 가정하면, 전압을 빼서 인덕턴스에서 차감한 뒤 증폭기의 나머지 부분으로 전달합니다. 물론, 이와 같은 회로에서는 일정량의 손실이 존재합니다. 완벽한 공진 회로는 아니지만 매우 좋은 회로이며 약간의 저항이 있습니다(예를 들어 저항을 삽입해 볼 수 있게 했지만, 작아야 합니다). 이제 인덕턴스에 걸친 전압은 얼마나 변동할까? 우리는 <span class="math inline">\(\frac{1}{2}LI^2\)</span> 가 “운동 에너지”, 즉 공명 회로의 코일과 연관된 에너지임을 알고 있다(제25장). 따라서 <span class="math inline">\(\frac{1}{2}LI^22\)</span> 의 평균값은 <span class="math inline">\(\frac{1}{2}k_BT\)</span> 와 같으며, 이를통해 RMS 전류와 RMS 전압을 알 수 있다. 인덕터에 걸리는 전압 <span class="math inline">\(\hat{V}_L = i\omega L\hat{I}\)</span> 이고 전압의 절대값의 제곱평균 <span class="math inline">\(\left\langle V_L^2\right\rangle = L^2\omega_0^2 \left\langle I^2\right\rangle\)</span> 이며 <span class="math inline">\(\frac{1}{2}L\left\langle I^2\right\rangle = \frac{1}{2}k_BT\)</span> 이므로</p>
<p><span id="eq-FLP_1_41_2"><span class="math display">\[
\left\langle V_L^2 \right\rangle = I\omega_0^2 k_BT
\tag{3.49}\]</span></span></p>
<p>이다. 이제 우리는 회로를 설계하고, 열 변동과 관련된 소음인 <em>존슨 노이즈 (Johnson noise)</em> 가 언제 발생할지 판단할 수 있다! 이 변동의 원인은 어디인가? 그것은 저항기이다—저항기 내 전자들이 저항기 내 물질과 열평형을 이루고 있기 때문에 흔들리며 전자 밀도에 변동을 발생한다. 따라서 공진 회로를 구동하는 작은 전기장을 발생시킨다.</p>
<p>전기 엔지니어는 답을 다른 방식으로 표현합니다. 물리적으로 저항은 실질적으로 잡음의 원천이다. 하지만 우리는 잡음을 발생시키는 진짜 물리적 저항을 가진 실제 회로를 소음을 나타내는 작은 발전기를 포함하는 인공 회로로 대체할 수 있다. 여기서 저항기는 이상적이며 소음을 발생시키지 않고 모든 소음은 인공 발전기에 있다. 따라서 저항기에 의해 발생하는 잡음의 특성을 알고 그에 대한 공식이 있다면, 우리는 그 잡음에 대해 회로가 어떤 반응을 할지 계산할 수 있다. 따라서, 우리는 소음 변동에 대한 공식이 필요합니다. 이제 저항기에서 발생하는 잡음은 모든 주파수에서 발생하며, 저항기 자체는 공진되지 않기 때문입니다. 물론 공진 회로는 올바른 주파수에 가까운 부분만 “듣습니다”, 하지만 저항기에는 다양한 주파수가 많이 포함되어 있습니다. 우리는 발전기의 강도를 다음과 같이 설명할 수 있습니다: 저항기가 노이즈 발생기에 직접 연결될 경우 발전기의 전압이 <span class="math inline">\(E\)</span> 일 때 흡수하는 평균 전력은 <span class="math inline">\(\langle E^2\rangle/R\)</span> 이다. 하지만 우리는 각 주파수마다 전력이 얼마나 되는지 더 자세히 알고 싶습니다. 하나의 주파수에서는 전력이 거의 없으며, 이는 분포입니다. <span class="math inline">\(P(\omega)\, d\omega\)</span> 를 동일한 저항기에 주파수 범위 <span class="math inline">\(d\omega\)</span> 에서 발전기가 전달할 전력이라고 하자. 그렇다면 우리는 power 가 저항에 무관하게 다음과 같다는 것을 증명 할 수 있다.</p>
<p><span id="eq-FLP_1_41_3"><span class="math display">\[
P(\omega)\,d \omega = \dfrac{2k_BT}{\pi} \,d\omega.
\tag{3.50}\]</span></span></p>
<p><br></p>
</section>
<section id="eq-FLP_1_41_2" class="level3">
<h3 class="anchored" data-anchor-id="eq-FLP_1_41_2">I.41-2 복사의 열평형</h3>
<p>빛에 대해 논의할 때와 같이 전하를 띤 진동자를 생각하자. 예를 들어 전자가 위아래로 진동하면 빛을 낼 수 있다. 이제 이 진동기가 매우 얇은 다른 원자들의 기체에 있다고 가정하고, 때때로 원자들이 진동자와 충돌한다고 가정하자. 평형 상태에서 오랜 시간이 지나면 이 진동자는 진동의 운동 에너지가 <span class="math inline">\(\frac{1}{2}k_B T\)</span> 가 되도록 에너지를 흡수하며, 조화 진동자이므로 전체 에너지는 <span class="math inline">\(k_BT\)</span> 일 것이다. 물론 현재까지는 잘못된 설명이다. 진동자의 전하와 에너지 <span class="math inline">\(k_BT\)</span> 로 인해 위아래로 흔들리며 빛을 방출한다. 따라서 그 안에 있는 전하가 빛을 방출하지 않고는 실제 물질만으로는 평형을 이루는 것이 불가능하며, 빛이 방출될 때 에너지는 흐르고 진동자는 시간이 흐름에 따라 <span class="math inline">\(k_BT\)</span> 를 잃게 되며, 따라서 진동자와 충돌하는 전체 기체가 점차 냉각된다. 이것이 그것은 따뜻한 스토브가 빛을 하늘로 방출하면서 식는 방식이며, 원자들이 전하를 흔들어 지속적으로 방출하고, 이 복사 때문에 서서히 진동 움직임이 느려진다.</p>
<p>반대로, 빛이 무한의 영역으로 사라지지 않도록 전체를 상자에 가두면 결국 열평형을 얻을 수 있다. 우리는 상자 벽에 빛을 되 쏘아주는 라디에이터가 있다고 할 수 도 있고 그 상자에 거울 벽이 있다고 가정할 수도 있다. 그 경우에 대해 생각하는 것이 더 쉽다. 따라서 우리는 진동자에서 방출되는 모든 빛이 상자 안에서 계속 흐르고 있다고 가정한다. 그렇다면 진동자가 복사하기 시작하는 것은 사실이지만, 복사하고 있음에도 불구하고 에너지 <span class="math inline">\(k_B T\)</span> 를 유지할 수 있다. 이는 상자의 벽에서 반사된 자체 빛에 의해 비추어지고 있기 때문이라고 말할 수 있다. 즉, 진동자가 일부를 복사하고 있지만 빛이 돌아와 복사된 에너지의 일부를 반환한다.</p>
<p>이제 우리는 온도 <span class="math inline">\(T\)</span> 에서 이러한 상자 안에 들어 있어야 할 빛의 양을 결정하여, 이 발진기에 빛이 비추어져 그 빛이 방출한 빛을 충분히 반영하도록 할 수 있다.</p>
<p>기체 원자들이 서로 매우 떨어져 있고 밀도가 낮다면 복사 저항(radiation resistance)을 제외한 저항이 전혀 없는 이상적인 진동자를 갖는다. 그리고 열평형에서 진동자가 동시에 두 가지 일을 수행하고 있다볼수 있다. 먼저 평균 에너지 <span class="math inline">\(k_B T\)</span> 를 가지고 있으며 그것이 방출하는 방사선량을 계산할 수 있다. 둘째, 이 복사선은 진동자에 산란되기 때문에 발생하는 양과 정확히 같아야 한다. 에너지가 갈 수 있는 다른 곳이 없으므로, 이 효과적인 복사는 실제로 그 안에 있는 빛으로부터 산란된 빛에 불과하다다.</p>
<p>따라서 진동자가 특정 에너지를 가지고 있을 경우, 진동자가 초당 방출하는 에너지를 먼저 계산해보자. (우리는 방사선 저항성에 관한 32장에서 여러 방정식을 차용하며, 그 파생을 되돌아보지 않습니다.) 라디안당 방출되는 에너지를 진동자의 에너지로 나눈 것을 <span class="math inline">\(1/Q\)</span> (<span class="quarto-unresolved-ref">?eq-FLP_1_32_8</span>) 라고 하며 <span class="math inline">\(1/Q=(dW/dt)/\omega_0 W\)</span> 이다. 감쇠 상수 <span class="math inline">\(γ\)</span> 를 이용하여 <span class="math inline">\(1/Q=\gamma/\omega_0\)</span> 로 표기할 수 있으며, 여기서 <span class="math inline">\(\omega_0\)</span> 는 진동자의 고유 주파수이다. 감마가 매우 작으면 <span class="math inline">\(Q\)</span> 는 매우 크다. 그때 초당 방출되는 에너지는</p>
<p><span id="eq-FLP_1_41_4"><span class="math display">\[
\dfrac{dW}{dt}=\dfrac{\omega_0 W }{Q}= \dfrac{\omega_0 W \gamma}{\omega_0}=\gamma W
\tag{3.51}\]</span></span></p>
<p>이다. 따라서 초당 방출되는 에너지는 단순히 진동자의 에너지에 감마를 곱한 것이다. 이제 진동자는 평균 에너지 <span class="math inline">\(k_B T\)</span> 를 가져야 하므로, <span class="math inline">\(\gamma k_B T\)</span> 는 초당 방출되는 평균 에너지 양임을 알 수 있다.</p>
<p><span id="eq-FLP_1_41_5"><span class="math display">\[
\left\langle \dfrac{dW}{dt}\right \rangle =\gamma k_B T.
\tag{3.52}\]</span></span></p>
<p>이제 우리는 감마만 구하면 된다. <span class="quarto-unresolved-ref">?eq-FLP_1_32_12</span> 로부터</p>
<p><span id="eq-FLP_1_41_6"><span class="math display">\[
\gamma = \dfrac{\omega_0}{Q}=\dfrac{2}{3}\dfrac{r_0 \omega_0^2}{c},
\tag{3.53}\]</span></span></p>
<p>이며, 여기서 <span class="math inline">\(r_0=e^2/mc^2\)</span> 는 고전적인 전자 반지름이고, <span class="math inline">\(\lambda =  2πc/\omega_0\)</span> 으로 놓았다. 따라서 <span class="math inline">\(\omega_0\)</span> 주위에서 방출되는 평균적인 복사율은</p>
<p><span id="eq-FLP_1_41_7"><span class="math display">\[
\left\langle \dfrac{dW}{dt} \right\rangle  = \dfrac{2}{3}\dfrac{r_0\omega_0^2 k_BT}{c}
\tag{3.54}\]</span></span></p>
<p>이다.</p>
<p>다음으로 우리는 진동자에 얼마나 많은 빛이 비추어야 하는지 알아보자 빛으로부터 흡수된 에너지(그리고 그에 따라 산란되는)가 정확히 이 정도일 정도로 충분해야 합니다. 방출된 빛과 공동 내 진동자에 비추는 빛의 양이 같아야 한다. 이제 진동자에 비치는 특정 양의—알 수 없는—복사량이 있을 경우, 산란되는 양을 계산해야 한다. <span class="math inline">\(\omega\)</span> 주위의 <span class="math inline">\(d\omega\)</span> 범위에서 존재하는 빛의 양을 <span class="math inline">\(I(\omega)\,d\omega\)</span> 라고 하자. 여기서 <span class="math inline">\(I(\omega)\)</span> 는 우리가 알아야 할 스펙트럼 분포이며, 온도 <span class="math inline">\(T\)</span> 에서 우리가 문을 열고 구멍을 통해 보이는 용광로의 색이다. 지금 얼마나 많은 빛이 흡수되나요? 우리는 주어진 입사광선으로부터 흡수되는 방사선량을 계산하고, 이를 단면을 기준으로 계산했습니다. 마치 우리가 특정 단면에 떨어지는 모든 빛이 흡수된다고 말한 것과 같습니다. 따라서 재방사(산란)되는 총량은 입사 강도 <span class="math inline">\(I(\omega)\,d\omega\)</span> 에 단면적 <span class="math inline">\(\sigma\)</span> 를 곱한 값이다.</p>
<p>우리가 유도한 단면에 대한 공식 <span class="quarto-unresolved-ref">?eq-FLP_1_32_19</span> 에는 감쇄가 포함되지 않았다. 우리가 넘어간 저항 항을 넣고 단면을 계산하면</p>
<p><span id="eq-FLP_1_41_8"><span class="math display">\[
\sigma_s=\dfrac{8\pi r_0^2}{3}\left[ \dfrac{\omega^4}{(ω^2−ω^2_0)^2+\gamma^2 \omega^2} \right]
\tag{3.55}\]</span></span></p>
<p>이다.</p>
<p>주파수의 함수로서, <span class="math inline">\(\sigma_s\)</span> 는 자연 주파수 <span class="math inline">\(\omega_0\)</span> 에 매우 가깝게 있는 <span class="math inline">\(\omega\)</span> 에 대해서만 유의미한 크기를 가진다. (복사 진동자의 <span class="math inline">\(Q\approx 10^8\)</span>) 진동자는 <span class="math inline">\(\omega\)</span> 가 <span class="math inline">\(\omega_0\)</span> 와 같을 때 매우 강하게 산란하고, 다른 <span class="math inline">\(\omega\)</span> 값에서는 매우 약하게 산란하며 따라서 다음을 얻는다.</p>
<p><span id="eq-FLP_1_41_9"><span class="math display">\[
\sigma_s= \dfrac{2\pi r^2_0 \omega^2_0}{3[(\omega − \omega_0)^2+\gamma^2/4]}
\tag{3.56}\]</span></span></p>
<p>이제 전체 곡선이 <span class="math inline">\(\omega = \omega_0\)</span> 근처에 위치한다. (우리는 실제로 근사값을 만들 필요는 없지만, 방정식을 약간 단순화하면 적분을 수행하는 것이 훨씬 쉬워집니다.) 이제 우리는 주어진 주파수 범위의 강도에 산란 단면을 곱하여 <span class="math inline">\(d\omega\)</span> 범위에 산란된 에너지 양을 구합니다. 전체 산란된 에너지는 모든 <span class="math inline">\(\omega\)</span> 에 대해 이것의 적분이 됩니다. 따라서</p>
<p><span id="eq-FLP_1_41_10"><span class="math display">\[
\dfrac{dW_s}{dt}=\int_0^\infty I(\omega) \sigma_s(\omega)\,d \omega=\int_0^\infty \dfrac{2\pi r_0^2  \omega_0^2 I(\omega) \,d\omega}{3[(\omega−\omega_0^2)^2+\gamma^2/4]}.
\tag{3.57}\]</span></span></p>
<p>이제 <span class="math inline">\(dW_s/dt=3\gamma k_BT\)</span> 라고 놓을 수 있다. 왜 <span class="math inline">\(3\)</span> 이 곱지는가? 32 장에서 단면적 분석을 할 때 우리는 편광이 빛이 진동자를 구동할 수 있을 정도라고 가정했기 때문이다. 만약 우리가 한 방향으로만 움직일 수 있는 진동자를 사용했고, 예를 들어 빛이 잘못된 방향으로 편광된다면, 산란을 발생시키지 않을 것이다. 따라서 우리는 빛의 입사 및 편광 모든 방향에 걸쳐 한 방향으로만 이동할 수 있는 진동자의 단면적을 평균해야 하며, 보다 쉽게는 장이 어느 방향을 가리키든 장을 따라가는 진동자를 상상할 수 있다. 그러한 진동자는 세 방향으로 동일하게 진동할 수 있으며, 해당 진동자의 자유도가 <span class="math inline">\(3\)</span> 이기 때문에 평균 에너지가 <span class="math inline">\(3k_BT\)</span> 이다. 따라서 <span class="math inline">\(3\gamma k_BT\)</span> 를 사용한다.</p>
<div id="fig-FLP_1_41_3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_41_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_41/fig_1_41_3.png" class="img-fluid figure-img" width="300">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_41_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.15: 파인만 물리학 강의 I. 그림 41-3. <a href="#eq-FLP_1_41_10" class="quarto-xref">식&nbsp;<span>3.57</span></a> 의 <span class="math inline">\(I(\omega)\)</span>. 픽은 공명 곡선 <span class="math inline">\(1/[(\omega-\omega_0)^2+\gamma^2/4]\)</span> 이다. <span class="math inline">\(I(\omega)\)</span> 는 근사적으로 <span class="math inline">\(I(\omega_0)\)</span> 와 잘 일치한다.
</figcaption>
</figure>
</div>
<p>이제 적분을 하자. 빛의 스펙트럼 분포 <span class="math inline">\(I(\omega)\)</span> 가 매끄러운 곡선이며, <span class="math inline">\(\sigma_s\)</span> 가 <span class="math inline">\(\omega_0\)</span> 근처의 좁은 영역에서 거의 변하지 않는다고 가정하자(<a href="#fig-FLP_1_41_3" class="quarto-xref">그림&nbsp;<span>3.15</span></a>). 그렇다면 유의미한 기여는 <span class="math inline">\([\omega_0-\gamma/2,\, \omega_0+\gamma/]2\)</span> 영역에서 발생하며 <span class="math inline">\(I(\omega)\)</span> 가 알 수 없고 복잡한 함수일지라도, 매끄러운 곡선을 ’상수’로 대체할 수 있다. 즉 이 적분 영역에서 <span class="math inline">\(I(\omega)\approx I(\omega_0)\)</span> 로 놓고 적분한다. 이제 적분은</p>
<p><span class="math display">\[
\dfrac{2}{3}\pi r_0^2 \omega_0^2 I(\omega_0) \int_0^\infty \dfrac{d\omega}{(\omega − \omega_0)^2+\gamma2/4} = 3\gamma k_BT
\]</span></p>
<p>이다. 이제 적분은 0 에서 <span class="math inline">\(\infty\)</span> 까지 진행되어야 하지만, 0 은 <span class="math inline">\(\omega_0\)</span> 에서 너무 멀리 떨어져 있어 그 시점까지 곡선이 모두 완성되므로 우리는 대신 <span class="math inline">\(-\infty\)</span> 에서 <span class="math inline">\(\infty\)</span> 까지 적분하는 것으로 바꿀 수 있으며 이 적분값은 <span class="math inline">\(2π/\gamma\)</span> 이다. 그렇다면</p>
<p><span id="eq-FLP_1_41_12"><span class="math display">\[
I(\omega_0)=\dfrac{9\gamma^2 k_BT}{4\pi^2 r_0^2 \omega_0^2}
\tag{3.58}\]</span></span></p>
<p>이다. <a href="#eq-FLP_1_41_6" class="quarto-xref">식&nbsp;<span>3.53</span></a> 을 대입하면, 그리고 <span class="math inline">\(\omega_0\)</span> 를 <span class="math inline">\(\omega\)</span> 로 교체하면 <span class="math inline">\(I(\omega)\)</span> 를 얻는다.</p>
<p><span id="eq-FLP_1_41_13"><span class="math display">\[
I(\omega)=\dfrac{\omega^2 k_B T}{\pi^2 c^2}
\tag{3.59}\]</span></span></p>
<p>위 식은 뜨거운 용광로에서 나오는 빛의 분포를 우리에게 제공한다. 즉 흑체 복사이다. 검은색은 온도가 영도일 때 우리가 보는 용광로의 구멍이 검은색이기 때문이다.</p>
<p><a href="#eq-FLP_1_41_13" class="quarto-xref">식&nbsp;<span>3.59</span></a> 은 온도 <span class="math inline">\(T\)</span> 의 닫힌 상자 내부에서의 복사에너지 분포이다. 여기서 진동자의 전하와 질량, 그리고 진동자의 특이한 모든 성질은 상쇄된다. 왜냐하면 한 진동자와 평형에 도달하면 다른 질량을 가진 다른 오실레이터와 평형에 있어야 하기 때문이다. 이것은 평형이 우리가 평형 상태에 있는 것에 의존하지 않고 오직 온도에만 의존한다는 명제에 대한 중요한 일종의 검증이다. 아래 <a href="#fig-FLP_1_41_4" class="quarto-xref">그림&nbsp;<span>3.16</span></a> 은 <span class="math inline">\(I(\omega)\)</span> 를 보여준다.</p>
<div id="fig-FLP_1_41_4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_41_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_41/fig_1_41_4.png" class="img-fluid figure-img" width="300">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_41_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.16: 파인만 물리학 강의 I. 그림 41-4. 실선: 고전물리학에서 예측하는 두 온도에서의 흑체복사 강도 분포. 파선 : 실제 분포
</figcaption>
</figure>
</div>
<p><span class="math inline">\(I(\omega) \propto \omega^2\)</span> 이다. 즉 어떤 온도의 상자건 방출되는 X-선은 강해야 한다. 그러나 우리는 이것이 거짓이라는 것을 알고 있다. 우리가 난로를 열어 보더라도 엑스레이 때문에 눈이 전혀 타지 않다는 것을 안다. 게다가 상자 안의 총 에너지, 즉 모든 주파수에 대한 이 모든 강도의 합은 이 무한 곡선의 주파수에 대한 적분이며 무한대로 발산하므로 근본적이고 절대적으로 잘못되었다. 즉 고전 이론은 흑체에서 나오는 빛의 분포를 정확히 기술할 수 없다. 물리학자들은 이에 대해 다양한 관점에서 우왕좌왕 했다. <a href="#eq-FLP_1_41_13" class="quarto-xref">식&nbsp;<span>3.59</span></a> 은 <strong>레일리 법칙 (Layleigh’s law)</strong> 이라고 불리는 고전 물리학의 예측으로 명백히 터무니없습니다.</p>
<p><br></p>
</section>
<section id="eq-FLP_1_41_3" class="level3">
<h3 class="anchored" data-anchor-id="eq-FLP_1_41_3">I.41-3 양자 진동자의 등분배</h3>
<p>위의 난제는 고전 물리학에서 계속된 문제중의 하나로 기체의 비열문제로부터 흑체복사문제까지 아우른다. 실제 곡선에 대한 측정도 많이 있었고(<a href="#fig-FLP_1_41_4" class="quarto-xref">그림&nbsp;<span>3.16</span></a>) X-선은 거기에 없다. 고전 이론에 따르면 온도를 낮추면 전체 곡선이 <span class="math inline">\(T\)</span> 에 비례하여 하강하지만, 관측된 곡선은 낮은 온도에서 더 빨리 짤린다. 따라서 곡선의 낮은 진동수쪽의 극한은 옳지만, 높은 진동수쪽은 틀렸다. 왜일까? 제임스 진스 경은 가스의 비열에 대해 높은 진동수의 운동은 온도가 너무 낮아지면 “동결”된다고 언급했다. 즉, 온도가 너무 낮고 주파수가 너무 높으면 발진기는 평균적으로 <span class="math inline">\(k_BT\)</span> 의 에너지를 갖지 않는다. 이제 <a href="#eq-FLP_1_41_13" class="quarto-xref">식&nbsp;<span>3.59</span></a> 을 어떻게 유도했는지 상기하자. 모든 것은 열평형에서 진동자의 에너지에 달려 있다. <a href="#eq-FLP_1_41_5" class="quarto-xref">식&nbsp;<span>3.52</span></a> 의 <span class="math inline">\(k_BT\)</span> 와 <a href="#eq-FLP_1_41_13" class="quarto-xref">식&nbsp;<span>3.59</span></a> 의 동일한 <span class="math inline">\(k_B T\)</span> 는 온도 <span class="math inline">\(T\)</span> 에서 진동수가 <span class="math inline">\(\omega\)</span> 인 고주파 진동자의 평균 에너지이다. 전통적으로는 이것이 <span class="math inline">\(k_B T\)</span> 이지만, 실험적으로는 그렇지 않다—온도가 너무 낮거나 진동자 주파수가 너무 높을 때는 그렇지 않다. 따라서 곡선이 떨어지는 이유는 가스의 비열이 실패하는 이유와 동일하다. 가스의 비열보다 흑체복사 곡선을 연구하는 것이 더 쉽다. 가스의 비열은 매우 복잡하므로, 따라서 우리는 진정한 흑체복사 곡선을 결정하는 데 집중하고 있다. 왜냐하면 이 곡선은 모든 주파수에서 조화 진동자의 평균 에너지가 온도의 함수로 정확히 얼마인지 정확히 알려주기 때문이다.</p>
<p>플랑크는 이 곡선을 연구하면서 먼저 관찰된 곡선을 매우 잘 맞는 좋은 함수와 맞추어 경험적으로 답을 결정했고, 이렇게 그는 진동수의 함수인 조화 진동자의 평균 에너지에 대한 경험적 공식을 가지게 되었다. 다시 말해, 그는 <span class="math inline">\(k_B T\)</span> 대신 올바른 공식을 가지고 있었으며, 그 후 간단한 유도방법을 발견했는데, 이 방법은 매우 특이한 가정에 기반한다. 이 특이한 가정은 고주파 진동자가 한 번에 <span class="math inline">\(\hbar \omega\)</span> 만 에너지를 받아들일 수 있다는 것이었다. 그들이 어떤 에너지라도 가질 수 있다는 생각은 거짓이다. 물론, 그것은 고전 역학의 종말의 시작이었다.</p>
<div id="fig-FLP_1_41_5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FLP_1_41_5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_1_41/fig_1_41_5.png" class="img-fluid figure-img" width="350">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FLP_1_41_5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;3.17: 파인만 물리학 강의 I. 그림 41-5. 조화진동자의 에너지 준위는 등간격이다.
</figcaption>
</figure>
</div>
<p>이제 최초로 올바르게 결정된 양자역학 공식이 도출된다. 조화 진동자의 허용된 에너지 준위는 <span class="math inline">\(\hbar \omega_0\)</span> 의 동일한 간격이다(<a href="#fig-FLP_1_41_5" class="quarto-xref">그림&nbsp;<span>3.17</span></a>). 플랑크는 여기서 제시된 논증보다 다소 복잡한 주장을 제시했는데 이는 당시 양자역학의 시작 단계였고 그는 몇 가지를 증명해야 했기 때문이다. 하지만 우리는 에너지 준위 <span class="math inline">\(E\)</span> 를 차지할 확률이 <span class="math inline">\(P(E)=\alpha e^{−E/k_B T}\)</span> 라는 사실을 받아들일 것이다.</p>
<p>이제 다수의 진동자가 있으며, 그리고 각각은 <span class="math inline">\(\omega_0\)</span> 의 진동수를 갖는다고 가정하자. 이 진동자들 중 일부는 낮은 양자 상태에 있을 것이며, 일부는 다음 상태에 있을 것이며, 이와 같이 계속된다. 우리가 알고 싶은 것은 이 모든 진동자들의 평균 에너지로 모든 진동자의 총 에너지를 계산하고 진동자의 수로 나누면 된다. 그것은 열평형에서 진동자당 평균 에너지이며, 흑체 복사와 평형에 있는 에너지이기도 하여 <a href="#eq-FLP_1_41_13" class="quarto-xref">식&nbsp;<span>3.59</span></a> 의 <span class="math inline">\(k_BT\)</span> 를 대신한다. <span class="math inline">\(N_i\, (i=0,\,1,\ldots)\)</span> 를 에너지 <span class="math inline">\(E_i\)</span> 상태의 진동자의 개수라고 하자. 우리가 아직 증명하지 않은 가설에 따르면, 확률 <span class="math inline">\(e^{−\text{P.E.}/k_BT}\)</span> 또는 <span class="math inline">\(e^{−\text{K.E.}/k_BT}\)</span> 를 대체한 양자역학의 법칙은 초과 에너지 <span class="math inline">\(\Delta E\)</span> 에 대해 확률이 <span class="math inline">\(e^{−\Delta E/k_B T}\)</span> 로 감소한다는 것이다. 그렇다면 <span class="math inline">\(N_n = N_0 e^{-n\hbar \omega}\)</span> 이며 평균 에너지 <span class="math inline">\(\langle E\rangle\)</span> 은 다음과 같다.</p>
<p><span class="math display">\[
\begin{aligned}
\langle E \rangle = \dfrac{E_\text{tot}}{N_\text{tot}} &amp;= \dfrac{N_0\hbar \omega (0 + 1\cdot e^{-\hbar\omega/k_BT} + 2\cdot e^{-2\hbar\omega/k_BT} + 3e^{-3\hbar\omega/k_BT}+ \cdots )}{N_0(1 + \cdot e^{-\hbar\omega/k_BT} + \cdot e^{-2\hbar\omega/k_BT} + e^{-3\hbar\omega/k_BT}+ \cdots)}
\end{aligned}
\]</span></p>
<p>위 식은 다음과 같다는 것을 쉽게 보일 수 있다.</p>
<p><span id="eq-FLP_1_41_15"><span class="math display">\[
\langle E \rangle = \dfrac{\hbar \omega}{e^{\hbar \omega/k_BT} -1}.
\tag{3.60}\]</span></span></p>
<p>위 식은 지금까지 알려진, 그리고 논의된 최초의 양자역학 공식이었으며, 수십 년에 걸친 혼란의 아름다운 정점이었다. 맥스웰은 뭔가 잘못됐다는 것을 알고 있었지만 플랑크까지 무엇이 옳지는 몰랐다. 위 식에서 <span class="math inline">\(\omega \to 0\)</span> 또는 <span class="math inline">\(T \to \infty\)</span> 극한에 대해 <span class="math inline">\(\langle E\rangle = k_BT\)</span> 이다.</p>
<p>이것은 Jeans가 찾고 있던 유명한 절단 요소 이며, <a href="#eq-FLP_1_41_13" class="quarto-xref">식&nbsp;<span>3.59</span></a> 에서 <span class="math inline">\(k_BT\)</span> 대신 이를 사용하면 검은 상자에서의 빛을 분포를 얻는다.</p>
<p><span id="eq-FLP_1_41_16"><span class="math display">\[
I(\omega) \, d\omega =\dfrac{\hbar \omega^3 d\omega}{\pi^2c^2 \left (e^{\hbar \omega/k_BT}−1 \right)}.
\tag{3.61}\]</span></span></p>
<p><span class="math inline">\(\omega\)</span> 가 큰 경우, 분자의 <span class="math inline">\(\omega^3\)</span> 에도 불구하고 분모의 <span class="math inline">\(e^{\hbar \omega/kB_T}\)</span> 가 훨씬 빠르게 커지므로 <span class="math inline">\(I(\omega)\)</span> 가 빠르게 0 으로 감소한다. 즉 자외선 및 X-선이 사라진다.</p>
<p><a href="#eq-FLP_1_41_16" class="quarto-xref">식&nbsp;<span>3.61</span></a> 을 얻을 때 조화 진동자의 에너지 준위에 양자 이론을 사용했지만, 횡단면적 <span class="math inline">\(\sigma_s\)</span> 를 결정하는 데는 고전 이론을 사용했다고 불평할 수 있다. 하지만 빛이 조화 진동자와 상호작용한다는 양자 이론은 고전 이론과 정획히 동일한 결과를 제시한다. 때문에 작은 진동자와 같은 원자 모델을 사용하여 굴절률과 빛의 산란을 분석하는 데 많은 시간을 할애 하는 것이 정당화된다. 양자식은 실질적으로 동일하다.</p>
<p>이제 저항기에서 Johnson 소음으로 돌아가겠습니다. 우리는 이미 이 잡음 전력 이론이 고전적인 흑체 분포 이론과 실제로 동일하다는 점을 언급했습니다. 사실, 다소 재미있게도, 우리는 이미 회로의 저항이 실제 저항이 아니라 안테나(안테나는 에너지를 방출하기 때문에 저항처럼 작동한다)와 복사 저항이라면, 전력이 얼마인지 계산하기가 쉬울 것이라고 이미 말했습니다. 그것은 주변에 있는 빛으로부터 안테나로 흐르는 전력일 뿐이며, 우리는 동일한 분포를 얻게 되지만 한두 배 정도만 변경됩니다. 우리는 저항기가 전력 스펙트럼 P(ω)을 알 수 없는 발전기라고 가정할 수 있습니다. 스펙트럼은 이 동일한 발생기가 그림 41–2(b)와 같이 모든 주파수의 공진 회로에 연결되어 인덕턴스에서 식에 제시된 크기의 전압을 발생시킨다는 사실에 의해 결정됩니다. (41.2). 따라서 (41.10)과 동일한 적분으로 인도되며, 동일한 방법이 식을 제공합니다. (41.3). 저온에서는 (41.3)의 kT를 물론 (41.15)로 교체해야 합니다. 두 이론(흑체 복사와 존슨 노이즈)은 물리적으로도 밀접하게 관련되어 있으며, 물론 공진 회로를 안테나에 연결할 수 있기 때문에 저항 R은 순수한 방사선 저항입니다. (41.2)는 저항의 물리적 기원에 의존하지 않으므로, 실제 저항에 대한 발생기 G와 복사 저항에 대한 발생기가 동일함을 알 수 있습니다. 저항 R이 온도 T에서 환경과 평형을 이루는 이상적인 안테나일 경우, 생성된 전력 P(ω)의 기원은 무엇입니까? 온도 T에서 공간에 있는 복사 I(ω)가 안테나에 영향을 가하고, “수신된 신호”로서 효과적인 발생기를 만듭니다. 따라서 P(ω)와 I(ω)의 직접 관계를 추론할 수 있으며, 이는 (41.13)에서 (41.3)으로 이어집니다.</p>
<p>우리가 이야기해 온 모든 것들—소위 존슨 노이즈와 플랑크의 분포, 그리고 우리가 곧 설명하려는 브라운 운동의 올바른 이론—은 20세기 초반 약 10년 정도의 발전입니다. 이제 그 점들과 그 역사를 염두에 두고, 우리는 브라운 운동으로 돌아갑니다.</p>
<p><br></p>
</section>
<section id="sec-FLP_1_41_4" class="level3">
<h3 class="anchored" data-anchor-id="sec-FLP_1_41_4">I.41-4 마구 걷기</h3>
<p>흔들리는 입자의 위치가 시간에 따라 어떻게 변하는지, “킥” 사이의 시간에 비해 매우 긴 시간 동안 어떻게 변해야 하는지 생각해 보자. 불규칙하게 흔들리는 물 분자들에 의해 사방에 폭격을 받아 흔들리는 작은 브라운 운동 입자를 생각하자.</p>
<p>질문: <strong>주어진 시간이 지난 후, 그것이 시작된 곳으로부터 얼마나 떨어져 있을까?</strong></p>
<p>이 문제는 아인슈타인과 스몰루초프스키(Smoluchowski)에 의해 해결되었다. 시간을 작은 구간 예를 들여 1/100 초로 나눈다고 하고 1/100 초마다의 운동을 추적한다고 생각하자. 1초 동안 물 한 분자는 10<sup>14</sup> 번 정도 충돌하기 때문에 1/100 초는 매우 긴 시간이며 1/100 초가 지나면 이전에 일어난 일을 기억하지 못할 것이다. 다시 말해, 충돌은 모두 무작위이며 한 “step”은 이전 “step”에 독립적이다. 입자가 각 스텝마다 취하는 각도도 무작위적으로 선택된다. 따라서 우리는 그가 어디에 있는지 모르며 말할 수 없다. 단지 어딘가에는 있을 것이다. 그렇다면 평균적으로 어디에 있는가? 즉 평균적으로 그는 얼마나 멀리 나갔는가? 우리는 이미 여기에 대한 답을 알고 있다. <a href="vol1_2.html#sec-FLP_1_30">제 30장</a> 에서 많은 광원들의 빛의 중첩에 대해 논의했으며, 이는 다양한 각도에서 많은 화살표를 추가하는 것을 의미했기 때문이다. 거기서 우리는 일련의 마구 걷기에 대해 한쪽 끝에서 다른 쪽 끝까지의 거리의 평균 제곱, 30장에서는 빛의 강도가 각각의 조각들의 강도 합임을 발견했다. <span class="math inline">\(\boldsymbol{R}_N\)</span> 이 <span class="math inline">\(N\)</span> 단계 후 원점으로부터의 벡터 거리라면, 원점으로부터의 거리의 평균 제곱이 N 단계 수에 비례한다는 것을 증명할 수 있다. 즉, 각 단계의 길이 <span class="math inline">\(L\)</span> 에 대해 <span class="math inline">\(\langle R^2_N\rangle⟩=NL^2\)</span> 이다. 현재 문제에서 단계 수가 시간에 비례하므로, 평균 제곱 거리도 시간에 비례한다:</p>
<p><span id="eq-FLP_1_41_17"><span class="math display">\[
\langle R^2\rangle =\alpha t.
\tag{3.62}\]</span></span></p>
<p>이는 평균 거리가 시간에 비례한다는 의미가 아닙니다. 평균 거리가 시간에 비례한다면, 이는 드리프팅이 좋은 균일한 속도임을 의미합니다. 그 선원은 비교적 합리적인 진전을 하고 있지만, 평균 제곱 거리가 시간에 비례하도록 하고 있습니다. 그것은 무작위 보행의 특징입니다.</p>
<p>우리는 각 연속 단계에서 거리의 제곱이 평균적으로 <span class="math inline">\(L^2\)</span> 만큼 증가한다는 것을 매우 쉽게 보일 수 있다. <span class="math inline">\(\boldsymbol{R}_N= \boldsymbol{R}_{N−1}+\boldsymbol{L}\)</span> 이라고 쓰면,</p>
<p><span class="math display">\[
\boldsymbol{R}_N\boldsymbol{\cdot R}_N = R^2_N = R^2_{N−1}+2\boldsymbol{R}_{N−1}\boldsymbol{\cdot L} + L2
\]</span></p>
<p>이며 스텝에 대해 평균하면, <span class="math inline">\(\langle \boldsymbol{R}_{N−1}\boldsymbol{\cdot L}\rangle = 0\)</span> 이므로 <span class="math inline">\(\langle R_N^2\rangle =\langle R_{N-1}^2\rangle + L^2\)</span> 이다. 따라서 다음이 성립한다.</p>
<p><span id="eq-FLP_1_41_18"><span class="math display">\[
\langle R^2_N\rangle = NL^2.
\tag{3.63}\]</span></span></p>
<p>이제 <a href="#eq-FLP_1_41_17" class="quarto-xref">식&nbsp;<span>3.62</span></a> 에서의 계수 <span class="math inline">\(\alpha\)</span> 를 계산해보자. 이를 위해서는 기능을 추가해야 한다.</p>
<ol type="1">
<li><p>이 입자에 힘을 가했을 때 (브라우니언 운동과는 전혀 관련이 없으며, 당분간 부수적인 사안으로 간주한다), 그 입자가 가지는 관성, 혹은 유효질량을 <span class="math inline">\(m\)</span> 이라고 하자. 입자를 움직이려면 입자 뿐만 아니라 입자 주위의 물도 움직여야 하므로 실제 입자의 질량과 반드시 동일할 필요는 없다. 한쪽 방향의 운동을 생각한다면 한쪽에 <span class="math inline">\(m(d^2x/dt^2)\)</span> 항이 존재할 것이다.</p></li>
<li><p>우리가 물체에 지속적인 인력을 유지한다면, 그 속도에 비례하여 유체에 인한 인력이 발생할 것이라고 가정한다. 유체의 관성 외에도, 점성와 유체의 복잡성으로 인해 흐름에 대한 저항이 존재한다. 요동이 발생하려면 되돌릴 수 없는 손실, 예를 들어 저항과 같은 것이 절대적으로 필수적이다. 손실이 발생하지 않는 한 <span class="math inline">\(k_BT\)</span> 를 생산할 방법은 없다. 요동의 원인은 이러한 손실과 매우 밀접하게 관련되어 있다. 이 항력의 메커니즘이 무엇인지 곧 이야기하겠다.—속도에 비례하는 힘과 그 출처에 대해 이야기할것이다. 하지만 지금은 일단 그런 저항이 있다고 가정한다.</p></li>
</ol>
<p>그렇다면 외부 힘에 의한 움직임에 대한 공식은 다음과 같다.</p>
<p><span id="eq-FLP_1_41_19"><span class="math display">\[
m\dfrac{d^2 x}{dt^2} + \mu \dfrac{dx}{dt}=F_\text{ext}.
\tag{3.64}\]</span></span></p>
<p>여기서 <span class="math inline">\(\mu\)</span> 는 실험적으로 결정되는 값이며 많은 콜로이드 물질에 대해 그 값이 알려져 있다.</p>
<p>이제 힘이 외부가 아니라 브라운 운동의 불규칙한 힘과 같은 경우에 동일한 공식을 사용한다. 그리고 물체가 이동하는 평균 제곱 거리를 계산한다. 우선 3차원에서 한쪽 방향만(<span class="math inline">\(x\)</span>) 고려하여 <span class="math inline">\(x^2\)</span> 의 평균을 구해보자. <span class="math inline">\(\langle x^2\rangle=\langle y^2\rangle = \langle z^2\rangle\)</span> 이므로 거리의 제곱평균은 <span class="math inline">\(x^2\)</span> 의 평균의 3배이다. 불규칙한 힘의 <span class="math inline">\(x\)</span>-성분은 물론 다른 모든 구성 요소와 마찬가지로 불규칙하다.</p>
<p><span class="math display">\[
\dfrac{d(x^2)}{dt}=2x\dfrac{dx}{dt}
\]</span></p>
<p>이므로 위치와 속도의 곱의 평균을 구하여 2를 곱하면 평균제곱거리이다. 결론부터 말하자면 이 값은 상수이며, 따라서 평균 제곱 반경이 시간에 비례하여 증가한다. 이제 <a href="#eq-FLP_1_41_19" class="quarto-xref">식&nbsp;<span>3.64</span></a> 에 <span class="math inline">\(x\)</span> 를 곱하여 평균을 취하면</p>
<p><span class="math display">\[
m \left \langle x\dfrac{d^2x}{dt^2} \right\rangle + \mu \left\langle x\dfrac{dx}{dt}\right\rangle = \langle xF_x\rangle
\]</span></p>
<p>이다. 위의 세 항을 생각해보자.</p>
<p><strong>1.</strong> <span class="math inline">\(\langle xF_x\rangle\)</span> : 입자의 위치와 가해지는 힘 사이에 어떠한 상관관계도 기대할 수 없으며 따라서 <span class="math inline">\(0\)</span> 이다.</p>
<p><strong>2.</strong> <span class="math inline">\(m\left \langle x\dfrac{d^2x}{dt^2}\right\rangle\)</span> :</p>
<p><span class="math display">\[
mx\dfrac{d^2x}{dt^2} = m \dfrac{d\left[ x(dx/dt)\right]}{dt} - m \left(\dfrac{dx}{dt}\right)^2
\]</span></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../../src/Feynman/vol1/vol1_2.html" class="pagination-link" aria-label="$I$-2: 특수상대성이론과 광학">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><span class="math inline">\(I\)</span>-2: 특수상대성이론과 광학</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../../src/Feynman/vol2/vol2_1.html" class="pagination-link" aria-label="$II$-1 : 정전기와 정자기">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><span class="math inline">\(II\)</span>-1 : 정전기와 정자기</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>