---
title: "I-1 : 고전역학"
number-sections: true
number-depth: 1
crossref:
  chapters: true
---


{{< include ../../../latexmacros.qmd >}} 

## 2. 기본적인 물리

### 2.1 소개 {#sec-FLP_1_2_1}

</br>

### 2.2 1920 년 이전의 물리학 {#sec-FLP_1_2_2}

- 1920 년 이전의 우리의 세계관
  - 우주가 펼쳐지는 무대는 3차원 공간이며 시간이라는 매개체 속에서 사물이 변화한다.
  - 이 무대의 elements 는 입자(예를 들면 원자) 이며 두가지 성질을 가진다.


- 입자의 두가지 성질
  1. 관성 : 힘이 작용하지 않는다면 입자는 하던 운동을 계속한다. 
  2. 힘 : 
     1. 여러 원자들의 복잡하고 상이한 조합을 유지하는 상호작용.
     2. 중력 



</br>

## 9. 뉴턴의 동역학 법칙


::: {.callout-important icon="false"}

#### **갈릴레오의 관성의 법칙** 혹은 **뉴턴의 제 1 운동법칙**

물체 하나만 존재한다면(if an object is left alone), 운동하고 있는 물제는 직선상의 등속운동을 하고 정지해 있는 물체는 정지해 있다. 이러한 성질을 **관성(inertia)** 라고 한다.

:::


::: {.callout-note icon="false"}

#### **운동량**

운동량 $\bf{p}$ 는 질량 $m$ 과 속도 $\bf{v}$ 의 곱으로 정의된다.

$$
\bf{p}:=m\bf{v}.
$$ {#eq-FLP_1_definition_of_momentum}



:::

::: {.callout-important icon="false"}

#### **뉴턴의 제 2 운동법칙**

운동량 $\bf{p}=m\bf{v}$ 의 시간에 대한 변화량이 힘 $\bf{F}$ 이다. 
$$
\bf{F}=\dfrac{d\bf{p}}{dt} = \dfrac{d}{dt}(m\bf{v}).
$$ {#eq-FLP_newton_2nd_law}

:::


::: {.callout-note icon="false"}

#### **보편 중력**

각각의 질량이 $m,\,M$ 인 두 입자가 각각 $\bf{r}_1,\,\bf{r}_2$ 에 위치했을 때 $m$ 인 입자가 느끼는 힘 $\bf{F}_m$ 은 다음과 같다.

$$
\bf{F}_m = \dfrac{GmM \hat{\bf{r}}}{r^3} = \dfrac{GmM(\bf{r}_2-\bf{r}_1)}{\|\bf{r}_2-\bf{r}_1\|^3}.
$$

여기서 $\bf{r}=\bf{r}_2-\bf{r}_1,\,r=\|\bf{r}\|,\, \hat{\bf{r}}=\bf{r}/r$ 이다. 

:::

</br>

## 10. 운동량 보존

### 10-1 뉴턴의 제 3 운동법칙 {#sec-FLP_1_10_1}

- 뉴턴이 자신의 물리법칙을 발표했을 때 보편중력에 대한 정확한 식을 알고 있었으며, 보편 중력 이외의 다른 힘에 대해서는 정확한 식을 알고 있지는 않았다. 그러나 모든 힘이 따라야 할 하나의 규칙을 알고 있었으며 이것을 운동법칙으로 표현한다.


::: {.callout-important icon="false"}

#### **뉴턴의 제 3 운동법칙**

한 입자 $A$ 의 존재에 의해 다른 입자 $B$ 에 힘 $\bf{F}$ 가 가해질 때(작용) $B$ 의 존재에 의해 $A$ 에 $-\bf{F}$ 의 힘이 가해진다. 

:::

- 뉴턴은 작용과 반작용이 같은 직선상에 존재한다고 생각했지만(작용-반작용의 강한 조건), 같은 직선상에 존재하지 않는다는 것이 밝혀 졌다. 다만 $\bf{F}$ 와 $-\bf{F}$ 의 관계인 것은 유지된다(작용-반작용의 약한 조건).

</br>

### 10-2 운동량 보존 {#sec-FLP_1_10_2}


 
