---
title: "실험적 사실"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

## 상대성 원리와 결정론

일련의 실험적 사실들이 고전역학의 기반이다. 아래는 그 중 우리가 다음 절에서부터 구성할 수학적 모델의 근거가 된다. 



### 시간과 공간 {#sec-MS_time_and_space}

우리의 공간은 3차원 유클리드 공간이며, 시간은 1차원 유클리드 공간이다.

</br>

### 갈릴레이 상대성 원리 {#sec-MS_galilean_relativity}

아래의 두 특성을 갖는 관성좌표계(intertial frame)가 존재한다.

&emsp;**1**. 자연의 모든 법칙은 모든 관성 좌표계에 대해 모든 순간 동일하다.

&emsp;**2**. 한 관성좌표계에 대해 균일한 직선 운동을 하는 좌표계는 관성좌표계이다.

</br>

### 뉴턴의 결정론 {#sec-MS_newton_determinacy}

역학계의 초기 조건, 어느 특정 시점에서의 위치와 운동량에 대한 모든 정보는 모든 운동을 유일하게 결정한다. 


## 갈릴레이 군과 뉴턴 방정식

### 주요 개념 {#sec-MS_important_concepts}

- $n$ 차원 실벡터 공간은 $\R^n$ 으로 표기한다.
- $n$ 차원 아핀공간은 $A^n$ 으로 표기한다. 아핀공간은 고정된 원점이 없다는 점에서 구분된다.
- $\R^n$ 은 $A^n$ 에 대한 평행이동군으로 작용한다. 즉 $a\in A^n$, $\bf{b}\in \R^n$ 에 대해 다음이 성립한다.

$$
\boldsymbol{b} a = a+\boldsymbol{b} \in A^n.
$$

- $\R^n$ 에서의 유클리드 구조는 스칼라곱, 혹은 내적이라고 불리는 쌍선형 형식을 말한다. 이 스칼라곱을 이용하여 거리 함수 혹은 노름(norm) 이라 불리는 함수 $\rho: \R^n \times \R^n \to \R$ 을 아래와 같이 정의 할 수 있다.

$$
\rho(x,\,y) := \|x-y\| = \sqrt{(x-y,\,, x-y)}.
$$

- 유클리드 구조를 가진 아핀 공간을 유클리드 공간이라고 하며 $n$ 차원 유클리드 공간을 $E^n$ 으로 표기한다.

</br>

### 갈릴레이 구조 {#sec-MS_galilean_structure}

::: {.callout-note appearance="minimal" icon="false"}

::: {#def-MS_galilean_space}

#### 갈릴레이 구조와 갈릴레이 공간

아래의 3가지 성질을 **갈릴레이 구조 (gaililean structure)** 혹은 **갈릴레이 시공간 구조 (galilean spact-time structure)** 라고 하며 갈릴레이 구조를 가진 4차원 아핀 공간을 **갈릴레이 공간 (galilean space)** 이라고 한다.

**1. 우주 :** 우주는 4차원 아핀 공간 $A^4$ 이다. $A^4$ 상의 한 점을 **사건(event)** 혹은 **세계점(world point)** 라고 하며 $A^4$ 내의 평행 이동은 4차원 벡터 공간 $\R^4$ 이다.

**2. 시간 :** 시간은 우주에 대한 평행 이동의 벡터공간으로부터 실수 시간축으로의 선형 사상이다. 즉 $t:\R^4 \to \R$ 이다. 두 사건 $a,\,b\in A^4$ 사이의 **시간 간격(time interval)** 은 $t(b-a)$ 이며, $t(b-a)=0$ 일 때 두 사건은 동시적(be simultaneous)이라고 한다.

어떤 사건과 동시적인 사건들의 집합은 $A^4$ 의 3차원 아핀 부분공간을 이루며, **동시 사건 공간 (space of simultaneous events)** $A^3$ 라고 한다. $t$ 의 커널은 $\R^4$ 의 3차원 부분공간이다.

**3. 동시 사건의 거리 :** 동시적인 두 사건 사이의 거리 $\rho : A^3 \times A^3 \to \R$ 는 아래와 같이 정의된다.

$$
\rho(a,\,b) = \|a-b\| -\sqrt{(a-b,\, a-b)}.
$$ {#eq-MS_distance_between_simultaneous_events}

:::
:::

</br>

::: {.callout-note appearance="minimal" icon="false"}

::: {#def-MS_galilean_group}

#### 갈릴레이 군

갈릴레이 구조를 보존하는 갈릴레이 공간 사이의 변환을 **갈릴레이 군 (galilean group)** 이라고 하며, 이 군의 성분을 **갈릴레이 변환 (galilean transformation)** 이라고 한다. 즉 갈릴레이 변환은 시간 간격과 거리를 보존하는 아핀 변환이다. 

:::

:::

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MS_galilean_coorinate_space}

#### 갈릴레이 좌표 공간과 갈릴레이 변환

시간과 3차원 공간에 대한 데카르트곱 $\R \times \R^3$ 를 생각하자. 여기서 $\R^3$ 가 유클리드 공간이라면 이 $\R\times \R^3$ 는 자연스러운 갈릴레이 구조를 갖게 된다. 이런 공간을 **갈릴레이 좌표 공간 (galilean coordinate space)** 라고 한다.

이 갈릴레이 좌표공간에는 3가지 기본적인 갈릴레이 변환이 존재한다. 

&emsp;($1$) 속도 $\bf{v}$ 에 대한 등속도 운동 : $g_1(t,\,\bf{x}) = (t,\, \bf{x}+\bf{v}t)$,

&emsp;($2$) 원점의 평행이동 : $g_2(t,\,\bf{x}) = (t+s,\, \bf{x}+\bf{s})$, 

&emsp;($3$) 좌표축의 회전 : $g_3(t,\,\bf{x}) =(t,\, R\bf{x})$.

여기서 ($3$) 의 $R$ 는 3차원 직교 행렬이다.

:::

</div></br>


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-arnold_1_2_1}

#### Arnold 1.2.1
$\R\times \R^4$ 에서의 갈릴레이 변환은 회전, 평행이동, 등속도 운동의 합성으로 표현할 수 있음을 보여라. 따라서 갈릴레이 군의 차원은 $3+4+3 = 10$ 이다.

:::

</div>

::: {.solution}



:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-arnold_1_2_2}

#### Arnold 1.2.2

모든 갈릴레이 공간은 동형(isomorphic) 임을 보여라. 또한 좌표공간 $\R\times \R^3$ 와 동형임을 보여라.

:::

</div>

::: {.solution}


:::

</br>

집합 $M$ 에 대해 어떤 전단사 함수 $\varphi_1 : M \to \R \times \R^3$ 가 존재한다면 이 $\varphi_1$ 을 집합 $M$ 에서의 **갈릴레이 좌표계(galilean coordinate system)** 라고 한다. 다른 갈릴레 좌표계 $\varphi_2$ 에 대해 $\varphi_1 \circ \varphi_2^{-1} : \R\times \R^3 \to \R \times \R^3$ 는 갈릴레이 변환이다. $M$ 에 대한 두 갈릴레이 좌표계는 $M$ 에 같은 갈릴레이 구조를 부여한다.

</br>

### 운동, 속도, 가속도 {#sec-MS_motion_velocity_acceleration}


::: {.callout-note appearance="minimal" icon="false"}

::: {#def-MS_motion_velocity_acceleration}

#### 운동, 속도, 가속도
</br>

&emsp;($1$) 실수 구간 $I$ 에 대해 미분가능한 사상 $\bf{x}:I \to \R^N$ 을 $\R^N$ 에서의 운동이라고 한다.

&emsp;($2$) $\bf{x}(I)$ 를 **경로 (trajectory)** 라고 한다.

&emsp;($3$) $\dot{\bf{x}}(t_0) :=\left.\dfrac{d\bf{x}}{dt}\right|_{t=t_0}$ 를 $t_0$ 에서의 **속도 벡터(velocity vector)** 라고 한다.

&emsp;($4$) $\ddot{\bf{x}}(t_0) :=\left.\dfrac{d^2\bf{x}}{dt^2}\right|_{t=t_0} =$ 를 $t_0$ 에서의 **가속도 벡터(acceleration vector)** 라고 한다.

&emsp;($4$) $W:I \to \R\times \R^3$, $W(t) = (t,\, \bf{x})$ 를 **세계선 (world line)** 이라고 한다.
:::

:::

</br>

우리는 특별한 언급이 없는 한 $\bf{x}(t)$ 가 무한번 미분가능한 함수, 즉 $C^\infty$ 급 함수임을 가정한다.

</br>


$n$ 개의 점입자의 운동은 갈릴레이 공간에서 $n$ 개의 세계선으로 나타나며 갈릴레이 좌표계에서 $n$ 개의 미분가능한 사상

$$
\bf{x}_i :\R \to \R^3,\qquad i=1,\ldots,\,n
$$

으로 기술된다. 이 때 $n$ 개의 $\R^3$ 의 직곱을 $n$ 점입자에 대한 **짜임새 공간 (configuration space)** 라고 부른다. 이 $n$ 개의 $\{\bf{x}_i:i=1,\ldots,\,n\}$ 은 

$$
\bf{x} :\R \to \R^{3n}
$$

사상을 정의한다. 이 때 $\bf{x}(I)$ 가 이 $n$ 점입자의 경로가 된다.

</br>

### 뉴턴 방정식 {#sec-MS_neuton_equation}

뉴턴의 결정론(@sec-MS_newton_determinacy) 에 따르면 모든 시스템의 운동은 특정 시간 $t_0$ 에서의 위치($\bf{x}(t_0)\in \R^N$) 와 초기 속도 ($\bf{\dot{x}}(t_0)\in \R^{N}$) 에 의해 결정된다. 측히 초기 위치와 속도가 가속도를 결정한다. 즉 어떤 함수 $\mathbf{F}:\R^N \times \R^n \times \R \to \R^N$ 이 존재하여

$$
\bf{\ddot{x}} = \bf{F}(\bf{x},\, \bf{\dot{x}},\,t)
$$ {#eq-MS_newton_equation}

이다. 위의 @eq-MS_newton_equation 을 우리는 뉴턴 방정식이라고 부른다. 상미분 방정식에서의 해의 존재성과 유일성의 정리에 의해 초기 조건 $\bf{x}(t_0)$ 와 $\bf{\dot{x}}(t_0)$ 가 주어졌을 때 운동 $\bf{x}(t)$ 가 유일하게 결정된다.

</br>

### 상대성 이론에 의해 부과된 제약 {#sec-MS_constraints_imposed_by_the_principle_of_relativity}

갈릴레이의 상대성 원리는 물리적 시공간 안에 다음과 같은 성질을 가지는 선택된 갈릴레이 구조(즉, "관성 좌표계의 집합")가 존재한다고 말한다. 어떤 하나의 갈릴레이 변환을 모든 역학계의 모든 점들의 세계선에 적용하면, 우리는 같은 계의 세계선을 얻게 된다 (단, 새로운 초기 조건을 갖는다).

@eq-MS_newton_equation 의 우변은 갈릴레이 변환에 대해 불변이어야 한다.


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MS_galilean_trasformation_of_time_translation}

시간에 대한 평행이동은 갈릴레이 변환에 포함되며 따라서 에 대해 불변이어야 한다. 즉 $\bf{x}=\bf{\varphi}(t)$ 가 @eq-MS_newton_equation 의 해라면 임의의 $s\in \R$ 에 대해  $\bf{x}=\bf{\varphi} (t+s)$ 도 역시 해이다. 그런데 이를 만족하기 위해서는 @eq-MS_newton_equation 의 우변이 시간에 대해 의존하지 않아야 한다. 즉

$$
\bf{\ddot{x}} = \bf{\Phi}(\bf{x},\,\bf{\dot{x}})
$$

이어야 한다.

:::

</div></br>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MS_galilean_trasformation_of_spatial_translation}

3차원 공간에서의 평행이동 역시 갈릴레이 변환에 포함되며 따라서 이 변환에 대해 불변이어야 한다. 공간에 대한 이런 성질을 **공간의 균질성 (homogeneity of space)** 라고 한다. 즉 $\bf{x}_i=\bf{\varphi}_i(t)$ 가 $n$ 개의 점입자 시스템에서 $i$ 번째 점입자의 운동이며 @eq-MS_newton_equation 를 만족한다면 임의의 $\bf{r}\in \R^3$ 에 대해 $\bf{\varphi}_i(t) +\bf{r}$ 역시 @eq-MS_newton_equation 를 만족해야 한다.

이를 통해 우리가 알 수 있는 것은 @eq-MS_newton_equation 의 $\bf{F}$ 가 점입자 사이의 상대적인 좌표 $\bf{x}_j-\bf{x}_i$ 에 의존해야 한다는 것이다. 예를 들어 균일한 등속 운동을 하는 좌표계에서 $\bf{x}_j-\bf{x}_i$,\, $\bf{\ddot{x}}$ 는 불변이며 $\bf{x}_j$ 는 $\bf{x}_j +\bf{v}$ 가 되므로 @eq-MS_newton_equation 의 우변은 속도가 아닌 상대속도에 의존해야 한다. 즉,

$$
\bf{\ddot{x}}_i = \bf{f}_i (\{\bf{x}_j-\bf{x}_k,\, \bf{\dot{x}}_j - \bf{\dot{x}}_k\}) ,\qquad i,\,j,\,k = 1,\ldots,\,n.
$$

이어야 한다.

:::

</div></br>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MS_galilean_trasformation_of_rotation}

3차원 공간의 회전 역시 갈릴레이 변환이므로 뉴턴 방정식 역시 회전에 대해 불변이어야 한다. 이러한 성질을 **공간의 등방성(isotropy of space)** 라고 한다. 따라서 $\bf{\varphi}_i$ 가 뉴턴 방정식의 해 이고 $R:\R^3 \to \R^3$ 가 직교 행렬이라면 $R\bf{\varphi}_i : \R \to \R^3$ 역시 뉴턴 벙정식의 해이다. 즉,

$$
\bf{F}(R\bf{x},\, R\bf{\dot{x}}) = R\bf{F}(\bf{x},\, \bf{\dot{x}})
$$

이다. 이 때 $R\bf{x} = (R\bf{x}_1,\ldots,\, R\bf{x}_n)$ 을 의미한다.

:::

</div></br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-arnold_1_2_3}

#### Arnold 1.2.3

역학계가 오직 하나의 점입자로 이루어졌다면 관성 좌표계의 가속도는 $0$ 임을 보여라.

:::

</div>

::: {.solution}

@exm-MS_galilean_trasformation_of_time_translation 에 의해 시간 의존성이 없으며, @exm-MS_galilean_trasformation_of_spatial_translation 에 의해 위치 및 속도 의존성도 없다. 따라서 $\bf{F}$ 는 상수벡터이다. 그런데 회전에 대해서 불변이어야 하므로 $\bf{F}=\bf{0}$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-arnold_1_2_4}

#### Arnold 1.2.4

두개의 점입자로 이루어진 역학계를 생각하자. 초기조건으로 속도가 둘 다 $0$ 으로 주어졌다. 이 점입자들은 초기에 이 둘을 이엇던 직선상에서 움직인다는 것을 보여라.

:::

</div>

::: {.solution}


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-arnold_1_2_5}

#### Arnold 1.2.5

거울로 반사시켜 본 시스템의 역학이 원래의 역학과 같다는 것을 보여라.

:::

</div>

::: {.solution}


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-arnold_1_2_5}

#### Arnold 1.2.5

거울로 반사시켜 본 시스템의 역학이 원래의 역학과 같다는 것을 보여라.

:::

</div>