---
title: "해밀턴 동역학"
number-sections: true
number-depth: 2
crossref:
  chapters: true
---

우리는 라그랑지안이 운동방정식을 세우고 그로부터 역학계를 기술하는데 아주 유용하다는 것을 안다. 이제 소위 해밀토니안(Hamintonian) 을 통해 운동을 기술하는 방법을 소개하고자 한다. 실제의 운동방정식을 세우고 푸는데 해밀토니안 방법이 라그랑지안 방법보다 유리한 경우는 거의 없다. 그러나 해밀토니안 방법은 고전역학 이후에 발전한 통계역학과 양자역학의 이론적 발전에 지대한 영향을 끼쳤으며, 고전역학을 새로운 관점을 보는데도 매우 유용하다.

여기서는 모든 시스템이 holonomic 이며(즉 역학적 제한조건이 좌표에만 의존한다), 힘이 monogenic 이거나 (즉 위치만의 함수인 포텐셜에 의해 힘이 주어진다) 속도에 의존적인 일반화된 포텐셜의 미분으로 힘이 주어지는 경우만을 생각하기로 하자.

</br>

## Hamiltonian

라그랑지안 $L$ 은 일반화된 좌표계 $\{q_i\}$ 에 대해 $\{q_i\}$ 와 $\{\dot{q}_i\}$ 의 함수이다. 이 때 **canonical momentum** $p_i$ 는 다음과 같이 정의된다.

$$
p_i := \dfrac{\partial L}{\partial \dot{q}_i}
$$

라그랑지안 $L$ 은 $\dot{q}_i$ 에 대해 convex 이다. 따라서  $\dot{q}_i$ 에 대해 [르장드르 변환](../topics/mathematical.qmd#sec-legendre_transform) 을 수행 할 수있으며, 이 변환의 결과를 **해밀토니안(Hamiltonian)** 이라고 한다. 즉, 해밀토니안 $H$ 는 다음과 같다.

$$
H\left(\{q_i\}, \{p_i\}, t\right) = \sum_{i} \dot{q}_i p_i - L(\{q_i\}, \{\dot{q}_i\}, t)
$$ {#eq-hamiltonian}

해밀토니안은 $\{q_i\},\, \{p_i\},\, t$ 에 대한 함수이므로 그 differrentail 은 다음과 같다.

$$
dH = \sum_i \left(\dfrac{\partial H}{\partial q_i}\right) dq_i + \sum_i \left(\dfrac{\partial H}{\partial p_i}\right) dp_i + \dfrac{\partial H}{\partial t}\, dt
$$

또한 @eq-hamiltonian 으로 부터, 

$$
dH = \sum_i\left(-\dfrac{\partial L}{\partial q_i}\right)dq_i + \sum_i \left(\dot{q}_i\right)\, dp_i + \left(p_i - \sum_i \dfrac{\partial L}{\partial \dot{q}_i}\right) d\dot{q}_i - \dfrac{\partial L}{\partial t}\,dt
$$

을 얻는다. 여기서 $d\dot{q}_i$ 앞의 항은 $p_i$ 의 정의에 의해 $0$ 이다. 또한 오일러 라그랑쥬 방정식에 의해

$$
0 = \dfrac{d}{dt}\left( \dfrac{\partial L}{\partial \dot{q}_i}\right) - \dfrac{\partial L}{\partial q_i} = \dot{p}_i - \dfrac{\partial L}{\partial q_i}
$$

이므로, 

$$
dH = -\sum_i (\dot{p}_i dq_i + \dot{q}_i dp_i )+ \dfrac{\partial H}{\partial t} 
$$

이며 이로부터

$$
\dot{q}_i = \dfrac{\partial H}{\partial p_i},\qquad \dot{p}_i =- \dfrac{\partial H}{\partial q_i}, \qquad \dfrac{\partial H}{\partial t} = -\dfrac{\partial L}{\partial t}
$$ {#eq-canonical_equation_of_hamiltonian}

를 얻는다.  


