<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>21&nbsp; 열역학 계 와 열역학 법칙 – 고전물리학</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../src/ThermalPhysics/02_entropy.html" rel="next">
<link href="../../src/ThermalPhysics/00_index.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-deb0270857c9bdf5e055ff61468a997e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../src/ThermalPhysics/00_index.html">열역학</a></li><li class="breadcrumb-item"><a href="../../src/ThermalPhysics/01_thermodynamic_systems.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">열역학 계 와 열역학 법칙</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../src/ThermalPhysics/00_index.html">열역학</a></li><li class="breadcrumb-item"><a href="../../src/ThermalPhysics/01_thermodynamic_systems.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">열역학 계 와 열역학 법칙</span></a></li></ol></nav>
      <h1 class="title"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">열역학 계 와 열역학 법칙</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">고전물리학</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../src/ClassicalMechanics/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">고전역학</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ClassicalMechanics/01_basic_principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">뉴튼역학의 기본 원리와 달랑베르 원리</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ClassicalMechanics/02_variational_principle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">변분 원리와 라그랑쥬 방정식</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ClassicalMechanics/03_hamilton_dynamics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">해밀턴 동역학</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ClassicalMechanics/04_canonical_transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">정준 변환</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ClassicalMechanics/11_one_body_problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">고전역학의 1체 문제</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ClassicalMechanics/12_two_or_three_bodies_problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">고전역학의 다체 문제 - 충돌과 산란</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ClassicalMechanics/13_small_oscillations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">작은 진동</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ClassicalMechanics/A_proofs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">증명들</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ClassicalMechanics/P1_problems01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">문제 모음</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../src/Mechanics_and_Symmetry/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">고전역학과 대칭</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Mechanics_and_Symmetry/01_experimental_facts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">실험적 사실</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Mechanics_and_Symmetry/02_equations_of_motion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">운동방정식</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../src/Electrodynamics/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">전기자기학</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Electrodynamics/01_introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">들어가며</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Electrodynamics/02_1_electrostatics1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">정전기 I</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Electrodynamics/02_2_electrostatics2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">정전기 II</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Electrodynamics/03_magnetostatics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">정자기</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Electrodynamics/04_electrodynamics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">전기동력학</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Electrodynamics/A1_mathematics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">부록 A. 수학</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Electrodynamics/A2_waves.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">부록 B. 파동</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../src/Relativity/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">상대론</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Relativity/01_introduction_to_special_relativity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">특수 상대론의 기초</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/Relativity/02_introduction_to_classical_field.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">고전 장론 입문</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../src/ThermalPhysics/00_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">열역학</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ThermalPhysics/01_thermodynamic_systems.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">열역학 계 와 열역학 법칙</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ThermalPhysics/02_entropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">열역학 제 2 법칙-열역학적 접근</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ThermalPhysics/03_introduction_to_statistical_mechanics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">통계역학의 기초</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ThermalPhysics/04_interaction_and_implication.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">상호작용과 결과</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/ThermalPhysics/0A_mathematics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Appendix</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../src/topics/Topics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">별도의 주제들</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/topics/mathematical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">수학적 자료</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#sec-TD_thermal_equillibrium_schroeder" id="toc-sec-TD_thermal_equillibrium_schroeder" class="nav-link active" data-scroll-target="#sec-TD_thermal_equillibrium_schroeder"><span class="header-section-number">21.1</span> 열평형</a>
  <ul class="collapse">
  <li><a href="#sec-TD_thermal_equillibrium_and_relaxation_time" id="toc-sec-TD_thermal_equillibrium_and_relaxation_time" class="nav-link" data-scroll-target="#sec-TD_thermal_equillibrium_and_relaxation_time">열평형과 이완 시간</a></li>
  <li><a href="#평형" id="toc-평형" class="nav-link" data-scroll-target="#평형">평형</a></li>
  </ul></li>
  <li><a href="#sec-TD_state_and_transform_of_system_fermi" id="toc-sec-TD_state_and_transform_of_system_fermi" class="nav-link" data-scroll-target="#sec-TD_state_and_transform_of_system_fermi"><span class="header-section-number">21.2</span> 계의 상태와 변환</a>
  <ul class="collapse">
  <li><a href="#sec-TD_mechanical_system_and_thermodynamic_system_fermi" id="toc-sec-TD_mechanical_system_and_thermodynamic_system_fermi" class="nav-link" data-scroll-target="#sec-TD_mechanical_system_and_thermodynamic_system_fermi">역학적 계와 열열학적 계</a></li>
  <li><a href="#sec-TD_exmaples_of_thermodynamic_system_fermi" id="toc-sec-TD_exmaples_of_thermodynamic_system_fermi" class="nav-link" data-scroll-target="#sec-TD_exmaples_of_thermodynamic_system_fermi">열역학적 계</a></li>
  <li><a href="#sec-TD_enssemble_of_state_and_equillibrium_fermi" id="toc-sec-TD_enssemble_of_state_and_equillibrium_fermi" class="nav-link" data-scroll-target="#sec-TD_enssemble_of_state_and_equillibrium_fermi">앙상블과 평형상태</a></li>
  <li><a href="#sec-TD_work" id="toc-sec-TD_work" class="nav-link" data-scroll-target="#sec-TD_work">일</a></li>
  <li><a href="#sec-TD_cycle" id="toc-sec-TD_cycle" class="nav-link" data-scroll-target="#sec-TD_cycle">사이클</a></li>
  </ul></li>
  <li><a href="#sec_TD_perfect_gas_0" id="toc-sec_TD_perfect_gas_0" class="nav-link" data-scroll-target="#sec_TD_perfect_gas_0"><span class="header-section-number">21.3</span> 이상 기체</a>
  <ul class="collapse">
  <li><a href="#sec-TD_perfect_gas_fermi" id="toc-sec-TD_perfect_gas_fermi" class="nav-link" data-scroll-target="#sec-TD_perfect_gas_fermi">이상 기체</a></li>
  <li><a href="#sec-TD_partial_pressure_fermi" id="toc-sec-TD_partial_pressure_fermi" class="nav-link" data-scroll-target="#sec-TD_partial_pressure_fermi">부분압</a></li>
  <li><a href="#sec-TD_microscopic_model_of_ideal_gas" id="toc-sec-TD_microscopic_model_of_ideal_gas" class="nav-link" data-scroll-target="#sec-TD_microscopic_model_of_ideal_gas">이상기체의 미시적 모델</a></li>
  <li><a href="#sec-TD_ideal_gas_and_equipartition_theorem" id="toc-sec-TD_ideal_gas_and_equipartition_theorem" class="nav-link" data-scroll-target="#sec-TD_ideal_gas_and_equipartition_theorem">이상기체와 등분배 정리</a></li>
  <li><a href="#연습문제" id="toc-연습문제" class="nav-link" data-scroll-target="#연습문제">연습문제</a></li>
  </ul></li>
  <li><a href="#sec-TD_the_1st_law_of_thermodynamics_fermi" id="toc-sec-TD_the_1st_law_of_thermodynamics_fermi" class="nav-link" data-scroll-target="#sec-TD_the_1st_law_of_thermodynamics_fermi"><span class="header-section-number">21.4</span> 열역학 제 1 법칙</a>
  <ul class="collapse">
  <li><a href="#sec-TD_energy_of_system_and_conservation_of_energy" id="toc-sec-TD_energy_of_system_and_conservation_of_energy" class="nav-link" data-scroll-target="#sec-TD_energy_of_system_and_conservation_of_energy">계의 에너지와 에너지 보존</a></li>
  <li><a href="#sec-TD_heat_the_another_form_of_energy" id="toc-sec-TD_heat_the_another_form_of_energy" class="nav-link" data-scroll-target="#sec-TD_heat_the_another_form_of_energy">에너지 보존과 열</a></li>
  <li><a href="#sec-TD_the_first_law_of_thermodynamics" id="toc-sec-TD_the_first_law_of_thermodynamics" class="nav-link" data-scroll-target="#sec-TD_the_first_law_of_thermodynamics">열역학 제 1 법칙</a></li>
  </ul></li>
  <li><a href="#sec-TD_ideal_gas_and_the_1st_law_of_thermodynamics" id="toc-sec-TD_ideal_gas_and_the_1st_law_of_thermodynamics" class="nav-link" data-scroll-target="#sec-TD_ideal_gas_and_the_1st_law_of_thermodynamics"><span class="header-section-number">21.5</span> 이상기체와 열역학 제 1 법칙</a>
  <ul class="collapse">
  <li><a href="#sec-TD_the_first_law_of_thermocynaics_in_Vp_diagram" id="toc-sec-TD_the_first_law_of_thermocynaics_in_Vp_diagram" class="nav-link" data-scroll-target="#sec-TD_the_first_law_of_thermocynaics_in_Vp_diagram">상태가 <span class="math inline">\((V,\,p)\)</span> 도식으로 표현되는 계에서의 열역학 제 1 법칙</a></li>
  <li><a href="#sec-TD_heat_capapcity" id="toc-sec-TD_heat_capapcity" class="nav-link" data-scroll-target="#sec-TD_heat_capapcity">열용량과 비열</a></li>
  <li><a href="#sec-TD_the_heat_capacity_of_ideal_gas" id="toc-sec-TD_the_heat_capacity_of_ideal_gas" class="nav-link" data-scroll-target="#sec-TD_the_heat_capacity_of_ideal_gas">이상기체의 열용량</a></li>
  <li><a href="#sec-TD_adiabatic_reversible_process_of_ideal_gas" id="toc-sec-TD_adiabatic_reversible_process_of_ideal_gas" class="nav-link" data-scroll-target="#sec-TD_adiabatic_reversible_process_of_ideal_gas">이상기체의 단열 가역 과정</a></li>
  <li><a href="#잠열" id="toc-잠열" class="nav-link" data-scroll-target="#잠열">잠열</a></li>
  <li><a href="#연습문제-1" id="toc-연습문제-1" class="nav-link" data-scroll-target="#연습문제-1">연습문제</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">





<div class="hidden">
<p>% %</p>
<p>% </p>
<p><span class="math display">\[
\DeclarePairedDelimiters{\set}{\{}{\}}
\DeclareMathOperator*{\argmax}{argmax}
\]</span></p>
</div>
<section id="sec-TD_thermal_equillibrium_schroeder" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="sec-TD_thermal_equillibrium_schroeder"><span class="header-section-number">21.1</span> 열평형</h2>
<section id="sec-TD_thermal_equillibrium_and_relaxation_time" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_thermal_equillibrium_and_relaxation_time">열평형과 이완 시간</h3>
<ul>
<li>두 물체가 충분히 오랜 시간 열적으로 접촉한다면 <strong>열평형 (thermal equillibrium)</strong> 에 도달한다.</li>
<li>계가 열평형에 도달하는데 걸리는 시간을 <strong>이완 시간 (relaxation time)</strong> 이라고 한다.</li>
</ul>
</section>
<section id="평형" class="level3">
<h3 class="anchored" data-anchor-id="평형">평형</h3>
<ul>
<li>열평형</li>
<li>역학적 평형</li>
<li>확산 평형 (diffusive equillibrium) : 충분히 섞인 상태</li>
</ul>
</section>
</section>
<section id="sec-TD_state_and_transform_of_system_fermi" class="level2 page-columns page-full" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="sec-TD_state_and_transform_of_system_fermi"><span class="header-section-number">21.2</span> 계의 상태와 변환</h2>
<section id="sec-TD_mechanical_system_and_thermodynamic_system_fermi" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_mechanical_system_and_thermodynamic_system_fermi">역학적 계와 열열학적 계</h3>
<ul>
<li>특정 시점에서의 역학계의 <strong>상태 (state)</strong> 는 각각의 입자의 위치와 속도에 의해 완벽하게 특정된다. 즉 <span class="math inline">\(N\)</span> 입자계는 <span class="math inline">\(6N\)</span> 변수에 의해 기술된다.</li>
<li>그러나 열역학에서는 <span class="math inline">\(N\approx 10^{23}\)</span> 개의 입자로 이루어진 계를 다루며 <span class="math inline">\(6N\)</span> 개의 변수를 특정하는 것은 실질적으로 불가능하다.</li>
<li>더우기 열역학에서 다루는 양은 이 계의 평균적인 특성이며, 각각의 입자에 대한 정보는 불필요하다.</li>
</ul>
</section>
<section id="sec-TD_exmaples_of_thermodynamic_system_fermi" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_exmaples_of_thermodynamic_system_fermi">열역학적 계</h3>
<section id="화학적으로-정의된-동일한-종류의-유체로-구성된-계" class="level4">
<h4 class="anchored" data-anchor-id="화학적으로-정의된-동일한-종류의-유체로-구성된-계"><strong>화학적으로 정의된 동일한 종류의 유체로 구성된 계</strong></h4>
<ul>
<li>온도 <span class="math inline">\(T\)</span>, 부피 <span class="math inline">\(V\)</span>, 압력 <span class="math inline">\(p\)</span> 에 의해 상태가 결정된다.</li>
<li>이 계의 기하학은 부피 뿐만 아니라 형태에 의해 결정된다. 대부분의 경우 기하학적 모양은 열역학적 특성에 영향을 끼치지 않지만 표면적이 부피에 비해 매우 클때는 표면이 고려되어야 한다.</li>
<li>물질이 주어졌을 때 온도, 부피, 압력은 서로 독립적이지 않으며 <strong>상태방정식 (equation of state)</strong> 이라고 불리는 아래와 같은 형태의 방정식으로 관련된다. <span id="eq-TD_form_of_equation_of_state"><span class="math display">\[
f(p, V, T) = 0.
\tag{21.1}\]</span></span></li>
<li>상태방정식의 구체적인 형태는 물질에 따라 다르다. 또한 세 변수중 한 변수는 다른 두 변수의 함수로 기술할 수 있다. 즉 세 변수가운데 두 값을 안다면 상태를 결정 할 수 있다.</li>
</ul>
</section>
<section id="화학적으로-정의된-동일한-종류의-고체로-구성된-계" class="level4">
<h4 class="anchored" data-anchor-id="화학적으로-정의된-동일한-종류의-고체로-구성된-계"><strong>화학적으로 정의된 동일한 종류의 고체로 구성된 계</strong></h4>
<ul>
<li>유체와는 다르게 압력의 방향이 특정되어야 하지만 많은 경우 등방적인 압력을 가정한다.</li>
</ul>
</section>
<section id="여러-화합물이-균일하게-섞여있는-계" class="level4">
<h4 class="anchored" data-anchor-id="여러-화합물이-균일하게-섞여있는-계"><strong>여러 화합물이 균일하게 섞여있는 계</strong></h4>
<ul>
<li>온도, 부피, 압력 이외에 농도가 고려되어야 한다.</li>
</ul>
</section>
<section id="불균일한-계" class="level4">
<h4 class="anchored" data-anchor-id="불균일한-계"><strong>불균일한 계</strong></h4>
<ul>
<li>불균일한 계를 다수의 균일한 부분으로 분할한다. 부분적인 균일성이 연속적으로 변할 때는 균일한 부분의 갯수가 무한일 수 있다.</li>
<li>이 경우 상태는 각각의 균일한 부분의 질량, 화학 조성, 뭉친 정도, 압력, 부피, 온도 에 의해 결정된다.</li>
</ul>
</section>
<section id="움직이는-부분을-가진-계" class="level4">
<h4 class="anchored" data-anchor-id="움직이는-부분을-가진-계"><strong>움직이는 부분을 가진 계</strong></h4>
<ul>
<li>대부분의 열역학적 계는 계의 각각의 부분이 정지해 있거나, 매우 느리게 움직여 부분의 운동에너지를 무시할 수 있다고 간주된다. 이 가정이 적용되지 않는다면 계의 각각의 부분의 속도를 특정해야 한다.</li>
</ul>
</section>
</section>
<section id="sec-TD_enssemble_of_state_and_equillibrium_fermi" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_enssemble_of_state_and_equillibrium_fermi">앙상블과 평형상태</h3>
<ul>
<li>열역학적 상태를 아는것은 동역학적 상태를 결정하기에는 부족하다. 예를 들어 균일한 유체로 이루어진 계에서 주어진 온도와 부피에 대해 (압력도 따라서 정해진다) 무한에 가까운 분자 운동 상태가 존재한다. 시간이 흐름에 따라 계는 이 가능한 무한한 상태를 순회한다. 이 관점으로는 열역학적 상태는 분자 운동의 결과로 이 계가 순회하는 모든 동역학적 상태의 <strong>앙상블 (enssemble)</strong> 이라고 볼 수 있다.</li>
<li><strong>평형상태 (states of equillibrium)</strong> 는 외부의 조건이 변화하지 않았을 때 계의 성질이 변화하지 않는 상태를 의미한다.</li>
<li>많은 경우 우리는 계가 초기상테애서 최종상태까지 중간의 무수한 상태를 거쳐 연속적으로 전행되는 것을 생각한다. 이것을 <strong>열역학적 과정(thermondynamic process)</strong> 혹은 줄여서 <strong>과정 (process)</strong> 이라고 한다. 만약 상태가 <span class="math inline">\((V,\,p)\)</span> 도식에 의해 표현 될 수 있다면 이 변환은 초기상태를 의미하는 점과 최종상태를 의미하는 점을 잇는 곡선으로 표현된다.</li>
<li>이 변환에서 거치는 모든 상태가 평형상태와 단지 아주 조금의 차이밖에 없다면 이 과정을 <strong>가역과정(reversible process)</strong> 이라고 한다. 따라서 가역과정의 초기상태와 최종상태는 평형상태 이어야 한다.</li>
<li>가역과정은 실제적으로 외부 조건을 매우 느리게 변화시켜 계가 각각의 단계에서 변화된 조건에 적응하게 하여 구현한다.</li>
<li>초기상태 <span class="math inline">\(A\)</span> 에서 최종상태 <span class="math inline">\(B\)</span> 까지 가역변환 되었다면 이 과정을 역으로 수행하면 <span class="math inline">\(B\)</span> 에서 <span class="math inline">\(A\)</span> 까지 변환될 수 있다.</li>
</ul>
</section>
<section id="sec-TD_work" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="sec-TD_work">일</h3>
<div id="fig-TD_simple_system" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-TD_simple_system-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fermi/simple_system/simple_system.png" class="img-fluid figure-img" width="200">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-TD_simple_system-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;21.1: 실린더-피스톤
</figcaption>
</figure>
</div>
<ul>
<li><p>열역학적 과정에서 계가 외부에 일을 하거나(음의 일) 외부가 계에 일을 할 수 있다(양의 일)<span class="math inline">\(^1\)</span>. </p></li>
<li><p>위의 그림과 같은 실린더-피스톤 시스템을 생각하자. 실린더의 면적을 <span class="math inline">\(A\)</span> 라고 내부에서 압력 <span class="math inline">\(p\)</span> 가 작용한다고 하면 피스톤에 가해지는 힘은 <span class="math inline">\(pA\)</span> 이다. 피스톤이 <span class="math inline">\(dh\)</span> 만큼 들렸다면 이 시스템이 외부에 한 미소 일(infinitesimla work) <span class="math inline">\(dW = -pA\,dh\)</span> 이며 <span class="math inline">\(A\,dh\)</span> 는 부피의 변화 <span class="math inline">\(dV\)</span> 이므로 미소 일은 다음과 같다. <span id="eq-TD_infinitesimal_work_done_by_system"><span class="math display">\[
dW = -p\,dV
\tag{21.2}\]</span></span></p></li>
<li><p>유한한 과정에서 이 시스템이 한 일은 위 식을 적분한 것이다. <span id="eq-TD_finite_work_done_by_system"><span class="math display">\[
W = -\int_A^B  p \,dV
\tag{21.3}\]</span></span></p></li>
</ul>
<div class="no-row-height column-margin column-container"><span class="margin-aside"><span class="math inline">\(^1\)</span> 교재나 학자에 따라 일의 부호가 바뀐다. <span class="citation" data-cites="Fermi1956ThermodynamicsDover">Fermi (<a href="../ClassicalMechanics/00_index.html#ref-Fermi1956ThermodynamicsDover" role="doc-biblioref">1956</a>)</span> 는 계가 외부에 한 일을 양으로 놓았지만 <span class="citation" data-cites="feynman2010feynman">(<a href="../ClassicalMechanics/00_index.html#ref-feynman2010feynman" role="doc-biblioref"><strong>feynman2010feynman?</strong></a>)</span> 이나 <span class="citation" data-cites="Schroeder2000introduction">Schroeder (<a href="../ClassicalMechanics/00_index.html#ref-Schroeder2000introduction" role="doc-biblioref">2000</a>)</span> 는 여기에 쓰인대로 정의했으며 근래의 교재들도 이 표기법을 따른다.</span></div><div id="fig-TD_simple_system_work_done" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-TD_simple_system_work_done-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fermi/simple_system/work_pv.png" class="img-fluid figure-img" width="350">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-TD_simple_system_work_done-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;21.2: Work
</figcaption>
</figure>
</div>
</section>
<section id="sec-TD_cycle" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_cycle">사이클</h3>
<section id="싸이클" class="level4">
<h4 class="anchored" data-anchor-id="싸이클"><strong>싸이클</strong></h4>
<div id="fig-TD_simple_cycle" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-TD_simple_cycle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fermi/simple_system/cycle.png" class="img-fluid figure-img" width="350">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-TD_simple_cycle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;21.3: 순환
</figcaption>
</figure>
</div>
<ul>
<li>과정에서 초기상태와 최종상태가 동일할 때 이 과정을 <strong>순환 (cycle)</strong> 혹은 영어 그대로 <strong>사이클</strong> 이라고 한다. <span class="math inline">\((V,\,p)\)</span> 도식으로 보인다면 <a href="#fig-TD_simple_cycle" class="quarto-xref">그림&nbsp;<span>21.3</span></a> 와 같은 닫힌 곡선으로 표현된다.</li>
<li>이 계가 한 일은 <span class="math inline">\((V,\,p)\)</span> 도상에서의 닫힌 곡선의 면적이다.</li>
<li>과정이 그림에서와 같이 <span class="math inline">\(A\to B\to C\to D\)</span> 라면 이 순환에서 계는 외부에 일을 하게 된다.</li>
</ul>
</section>
<section id="중요한-과정-process" class="level4">
<h4 class="anchored" data-anchor-id="중요한-과정-process"><strong>중요한 과정 (process)</strong></h4>
<ul>
<li><p>외부에 일을 하거나 받지 않는 과정을 <strong>등적 과정(isochoric process)</strong> 이라고 한다. 등적 과정의 경우 과정 전체에 걸쳐 부피가 변하지 않는다.</p></li>
<li><p>과정 전체에서 압력이 변하지 않는 과정을 <strong>등압 과정(isobaric process)</strong> 라고 한다.</p></li>
<li><p>과정 전체에서 온도가 변하지 않는 과정을 <strong>등온 과정(isothermal process)</strong> 라고 한다.</p></li>
</ul>
</section>
</section>
</section>
<section id="sec_TD_perfect_gas_0" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="sec_TD_perfect_gas_0"><span class="header-section-number">21.3</span> 이상 기체</h2>
<section id="sec-TD_perfect_gas_fermi" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_perfect_gas_fermi">이상 기체</h3>
<ul>
<li>온도 <span class="math inline">\(T\)</span>, 압력 <span class="math inline">\(p\)</span>, 부피 <span class="math inline">\(T\)</span> 일 때의 기체의 상태 방정식은 근사적으로 아래의 간단한 식으로 나타 낼 수 있다. 여기서 <span class="math inline">\(T\)</span> 는 절대 온도이다. 기체의 질량이 <span class="math inline">\(m\)</span> 이고 분쟈량이 <span class="math inline">\(M\)</span> 일 때의 방정식은 아래와 같으며 이 식을 <strong>이상 기체 상태 방정식 (equation of state of an ideal gas or a perfect gas)</strong> 라고 한다.</li>
</ul>
<p><span id="eq-TD_equation_of_state_for_perfect_gas"><span class="math display">\[
pV = \dfrac{m}{M}RT = \nu RT = Nk_BT.
\tag{21.4}\]</span></span></p>
<ul>
<li><p>여기서 <span class="math inline">\(R\)</span> 은 <strong>기체 상수 (gas constant)</strong> 혹은 <strong>이상 기체 상수</strong> 혹은 <strong>기체상수 (gas constant)</strong> 라고 하며 그 값은 아래와 같다. <span class="math display">\[
R=8.314 \, \text{J}\cdot \text{mol}^{−1}\cdot \text{K}^{−1}
\]</span></p></li>
<li><p><span class="math inline">\(\nu = m/M\)</span> 은 기체의 몰수 이며 <span class="math inline">\(N\)</span> 은 기체 분자의 개수이다. <span class="math inline">\(k_B\)</span> 를 <strong>볼츠만 상수 (Boltzmann constant)</strong>라고 하며 그 값은 아래와 같다. <span class="math display">\[
k_B = 1.380649 \times 10^{-23}\, \text{J/K}.
\]</span></p></li>
<li><p>이상기체의 밀도 <span class="math inline">\(\rho\)</span> 는 아래와 같다. <span class="math display">\[
\rho = \dfrac{m}{V} = \dfrac{pM}{RT}
\]</span></p></li>
<li><p>등온과정에서 <span class="math inline">\(pV=\text{constant}\)</span> 이다. 또한 등온과정에서 부피가 <span class="math inline">\(V_1\)</span> 에서 <span class="math inline">\(V_2\)</span> 로 변할 때 계가 외부에 한 일은 다음과 같다. <span class="math display">\[
W = -\int_{V_1}^{V_2} p\,dV = -\dfrac{m}{M}RT\int_{V_1}^{V_2}\dfrac{dV}{V} = \dfrac{mRT}{M}\ln \left(\dfrac{V_1}{V_2}\right) = \dfrac{mRT}{M}\ln \left(\dfrac{p_2}{p_1}\right)
\]</span></p></li>
</ul>
</section>
<section id="sec-TD_partial_pressure_fermi" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_partial_pressure_fermi">부분압</h3>
<ul>
<li>여러 종류 기체의 혼합물은 화학적으로 동일한 종류의 그것과 비슷한 법칙의 지배를 받는다. 여러 기체의 혼합물이 있을 때 그중 한 종류의 혼합물이 같은 온도에서 같은 부피를 채우고 있을 때의 압력을 <strong>부분압 (partial pressure)</strong> 라고 한다. 돌텅의 법칙은 혼합기체의 경우 전체 얍력은 부분압의 합과 같다는 것을 말한다.</li>
</ul>
</section>
<section id="sec-TD_microscopic_model_of_ideal_gas" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_microscopic_model_of_ideal_gas">이상기체의 미시적 모델</h3>
<ul>
<li><a href="https://julia-kaeri.github.io/FeynmanLecturesOnPhysics/src/vol1/vol1_6.html#sec-FLP_1_39">파인만 물리학 강의 분자운동론</a> 을 참고하라.</li>
</ul>
</section>
<section id="sec-TD_ideal_gas_and_equipartition_theorem" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_ideal_gas_and_equipartition_theorem">이상기체와 등분배 정리</h3>
<ul>
<li><p>아래에 서술되는 <strong>등분배 정리 (equipartition theorem)</strong> 는 다음에 증명한다.</p></li>
<li><p><strong>온도 <span class="math inline">\(T\)</span> 에서 평행상태인 고전역학적 시스템의 에너지가 <span class="math inline">\(f\)</span> 개의 제곱항으로 기술되면, 이 시스템의 평균에너지는 <span class="math inline">\(\displaystyle \dfrac{fk_BT}{2}\)</span> 이다.</strong></p></li>
<li><p>단원자 분자의 경우 3차원 병진운동만 가능하므로 <span class="math inline">\(f=3\)</span> 이다. 이원자 분자 기체의 경우 두 원자 사이의 거리가 일정해야 하므로 <span class="math inline">\(300\,\text{K}\)</span> 근처에서 <span class="math inline">\(f=5\)</span> 이다.</p></li>
<li><p>1차원 용수철의 경우 <span class="math inline">\(E=\dfrac{1}{2}mv^2 + \dfrac{1}{2}kx^2\)</span> 이므로 <span class="math inline">\(n=2\)</span> 이다.</p></li>
</ul>
</section>
<section id="연습문제" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="연습문제">연습문제</h3>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">
<div id="exr-TD_schroeder_1_17" class="theorem exercise">
<p><span class="theorem-title"><strong>연습문제 21.1 (Schroeder 1.17)</strong></span> 낮은 밀도에서도 실제 기체는 이상기체와 다른 행동을 한다. 이 차이를 체계적으로 설명하기 위한 방법이 <strong>비리얼 전개 (virial expansion)</strong> 를 사용하는 방법으로 아래와 같다.</p>
<p><span class="math display">\[
pV = \nu RT \left(1 + \dfrac{B(T)}{(V/\nu)} + \dfrac{C(T)}{(V/\nu)^2} + \cdots \right),
\]</span></p>
<p>여기서 <span class="math inline">\(B(T),\,C(T), \ldots\)</span> 를 <strong>비리얼 계수 (virial coefficients)</strong> 라고 한다. 기체의 밀도가 낮다면 <span class="math inline">\((V/\nu)\)</span> 가 커서 뒤의 항이 앞의 항보다 작다. 많은 경우 두번째 항 까지만 사용해도 충분하다. 여기서 <span class="math inline">\(B(T)\)</span> 를 2차 비리얼 계수라고 하며 1차 비리얼 계수는 항상 1 이다. 질소 N<sub>2</sub> 의 2차 비리얼 계수는 다음과 같다.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(T\,(\text{K})\)</span></th>
<th style="text-align: center;"><span class="math inline">\(B\,(\text{cm}^3/\text{mol})\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">100</td>
<td style="text-align: center;">-160</td>
</tr>
<tr class="even">
<td style="text-align: center;">200</td>
<td style="text-align: center;">-35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">300</td>
<td style="text-align: center;">-4.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">400</td>
<td style="text-align: center;">9.0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">500</td>
<td style="text-align: center;">16.9</td>
</tr>
<tr class="even">
<td style="text-align: center;">600</td>
<td style="text-align: center;">21.3</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>(<span class="math inline">\(a\)</span>) 각각의 온도에서 이차 비리얼 항 <span class="math inline">\(B/(V/\nu)\)</span> 를 계산하라. 이 때 압력은 1기압이다.</p>
<p>(<span class="math inline">\(b\)</span>) 분자 사이의 힘을 고려하여 저온에서 <span class="math inline">\(B(T)&lt;0\)</span> 이며 높은 온도에서 <span class="math inline">\(B(T)&gt;0\)</span> 인 이유를 설명하라.</p>
<p>(<span class="math inline">\(c\)</span>) 이상기체와 같이 <span class="math inline">\(p,\,V,\,T\)</span> 의 관계가 주어졌을 때 이를 <strong>상태 방정식 (equation of state)</strong> 라고 한다. 밀도가 높은 유체에도 정성적으로 정확한 유명한 상태방정식에는 반데르 발스 방정식이 있다.</p>
<p><span class="math display">\[
\left(p + \dfrac{a\nu^2}{V^2}\right)\left(V-\nu b\right) = \nu RT.
\]</span></p>
<p>여기서 <span class="math inline">\(a,\,b\)</span> 는 기체에 따라 정해지는 상수이다. 이로부터 2차와 3차 비리얼 계수를 <span class="math inline">\(a,\,b\)</span> 로 표현하라.</p>
<p>(<span class="math inline">\(d\)</span>) <span class="math inline">\(a,\,b\)</span> 값을 질소의 경우에 맞추어 정하여 반데르 발스로부터 <span class="math inline">\(B(T)\)</span> 의 그래프를 그려라. 이 조건의 범위로부터 반데르 발스 상태방정식의 정확도에 대해 논하라.</p>
</div>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>(해답)</em>. </span>(<span class="math inline">\(a\)</span>) <span class="math inline">\(B(T)P/RT\)</span></p>
<p>(<span class="math inline">\(b\)</span>) 이상기체와 비교했을 때 <span class="math inline">\(B(T)&lt;0\)</span> 은 분자들 사이에 인력이, <span class="math inline">\(B(T)&gt;0\)</span> 은 분자들 사이에 척력이 작용하는 것이다. 낮은 온도에서는 분자들의 운동이 크지 않고 분자들 사이의 인력이 작용하지만 높은 온도에서는 분자들의 운동이 커 충돌을 자주 하기 때문에 척력이 작용하는 것처럼 느끼게 된다.</p>
<p>(<span class="math inline">\(c\)</span>) 주어진 식을 변형하면</p>
<p><span class="math display">\[
\begin{aligned}
\left(p + \dfrac{a\nu^2}{V^2}\right)V &amp;= \dfrac{\nu RT}{\left(1-\nu b/V\right)} \\[0.3em]
&amp;= \nu RT \left(1 + \dfrac{b}{V/\nu} + \dfrac{b^2}{(V/\nu)^2} + \cdots \right)
\end{aligned}
\]</span></p>
<p>이므로</p>
<p><span class="math display">\[
pV = \nu RT \left( 1 + \dfrac{b- {a/RT}}{V/\nu}  + \dfrac{b^2}{(V/\nu)^2} + \cdots \right)
\]</span></p>
<p>이다. 따라서 <span class="math inline">\(B(T) = b-a/RT,\, C(T) = b^2\)</span>.</p>
<p>(<span class="math inline">\(d\)</span>) Least square fit 을 통해 계산하면 <span class="math inline">\(b=6.42\times 10^{-5} (\text{m}^3/\text{mol})\)</span>, <span class="math inline">\(a=0.1823 \, \text{J}\cdot\text{m}^3\cdot \text{mol}^2\)</span></p>
<div id="fig-TD_schroeder_prob_1_17" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-TD_schroeder_prob_1_17-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/schroeder/chap1/schroeder_prob_1_17.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-TD_schroeder_prob_1_17-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;21.4: <span class="math inline">\(T-B(T)\)</span> 곡선
</figcaption>
</figure>
</div>
</div>
</section>
</section>
<section id="sec-TD_the_1st_law_of_thermodynamics_fermi" class="level2" data-number="21.4">
<h2 data-number="21.4" class="anchored" data-anchor-id="sec-TD_the_1st_law_of_thermodynamics_fermi"><span class="header-section-number">21.4</span> 열역학 제 1 법칙</h2>
<ul>
<li><p>열역학 제 1 법칙은 열역학 계에서의 에너지 보존 법칙이다. 계의 에너지의 변화량과 외부에서 받은 에너지의 합은 항상 <span class="math inline">\(0\)</span> 이다.</p></li>
<li><p>위의 서술에서 <em>계의 에너지</em> 와 <em>외부에서 받은 에너지</em> 에 대해 명확히 정의해야 한다.</p></li>
</ul>
<section id="sec-TD_energy_of_system_and_conservation_of_energy" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_energy_of_system_and_conservation_of_energy">계의 에너지와 에너지 보존</h3>
<ul>
<li><p>역학적 보존계에서 에너지는 포텐셜 에너지와 운동에너지의 합이며 따라서 계의 동력학 변수의 함수이다. 따라서 외부에서 힘이작용하지 않으면 이 계의 에너지는 일정하다. 즉 이 계가 고립계이고 <span class="math inline">\(A,\,B\)</span> 가 이 계의 연속적인 상태이며 <span class="math inline">\(U_A,\,U_B\)</span> 가 각각의 상태에서의 에너지라면 <span class="math inline">\(U_A=U_B\)</span> 이다.</p></li>
<li><p>이 계가 고립계가 아니며 외부에서 <span class="math inline">\(W\)</span> 만큼이 전달되었다면 (<span class="math inline">\(-W\)</span> 는 이 계가 외부에 한 일) 다음이 성립한다. <span id="eq-TD_work_and_internal_energy"><span class="math display">\[
U_B-U_A = W.
\tag{21.5}\]</span></span></p></li>
<li><p>이 계의 수많은 입자들 사이의 상호작용에 대해 우리가 알지 못한다면, 우리는 주어진 동역학적 상태의 에너지를 계산 할 수 없다. 그러나 <a href="#eq-TD_work_and_internal_energy" class="quarto-xref">식&nbsp;<span>21.5</span></a> 을 이용하여 계의 에너지에 대한 실험적 정의를 할 수 있다.</p></li>
<li><p>계의 임의의 상태 <span class="math inline">\(O\)</span> 를 정한 후 그 에너지를 <span class="math inline">\(0\)</span> 으로 놓는다. 즉 <span class="math inline">\(U_O=0\)</span>. 앞으로 이 상태를 <em>표준 상태(standard state)</em> 라고 한다. 이제 외부에서 힘을 가하여 상태를 <span class="math inline">\(A\)</span> 로 변환하였다고 하자. 이 때 외부에서 이 시스템에 해준 일을 <span class="math inline">\(W_A\)</span> 라고 하자. 그렇다면 <span class="math inline">\(A\)</span> 상태의 에너지 <span class="math inline">\(U_A = W_A\)</span> 이며 이 값이 <span class="math inline">\(A\)</span> 상태에 대한 실험적 정의값이라고 할 수 있다.</p></li>
<li><p>이제 두 상태 <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span> 를 생각하자. <span class="math inline">\(A\to B\)</span> 과정은 <span class="math inline">\(A\to O \to B\)</span> 과정으로 생각할 수 있으며 <span class="math inline">\(W=W_B - W_A\)</span> 이므로 <span class="math inline">\(U_B-U_A = W\)</span> 이다. 이제 우리는 <a href="#eq-TD_work_and_internal_energy" class="quarto-xref">식&nbsp;<span>21.5</span></a> 를 얻었다.</p></li>
<li><p>실험적으로 정의된 내부 에너지는 표준상태 <span class="math inline">\(O\)</span> 에 따라 다르다는 것은 자명하다.</p></li>
</ul>
</section>
<section id="sec-TD_heat_the_another_form_of_energy" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_heat_the_another_form_of_energy">에너지 보존과 열</h3>
<ul>
<li><p>위의 실험적 정의가 의미가 있으려면 <span class="math inline">\(W_A\)</span> 가 단지 상태 <span class="math inline">\(O\)</span> 와 상태 <span class="math inline">\(A\)</span> 에만 의존하며 <span class="math inline">\(O\to A\)</span> 변환의 경로에 의존하면 안된다. 경로에 의존하지 않는 성질은 <a href="#eq-TD_work_and_internal_energy" class="quarto-xref">식&nbsp;<span>21.5</span></a> 으로부터 온다. 즉 만약 이 경로 독립성이 성립하지 않는다면 우리 계에서는 (지금까지의) 에너지 보존이 성립하지 않는다는 의미이며, 에너지 보존을 포기하지 않으려면 역학적 일 이외의 에너지 전달 수단을 인정해야 한다는 의미이다.</p></li>
<li><p>예를 들면 (<span class="math inline">\(1\)</span>) 외부에서 열을 가한다면 계의 온도는 올라가지만 이 계가 일을 하거나 받지 않을 수 있다. (<span class="math inline">\(2\)</span>) <a href="https://en.wikipedia.org/wiki/Mechanical_equivalent_of_heat">줄의 실험</a> 은 명백히 역학적 일(<span class="math inline">\(V\)</span> 가 변하는) 없이도 내부의 온도를 상승시킬 수 있음을 보여준다.</p></li>
<li><p>이로부터 우리는 열(heat) 이라는 비 역학적인(non mechanical) 형태로 에너지가 전달되는 것을 인정 할 수 밖에 없다. 즉 열은 에너지이다.</p></li>
</ul>
</section>
<section id="sec-TD_the_first_law_of_thermodynamics" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_the_first_law_of_thermodynamics">열역학 제 1 법칙</h3>
<ul>
<li><p>계 와 환경이 열적으로 분리된 경우, 즉 계가 단열체로 둘러쌓인 경우를 생각해보자. 이 경우 계와 환경 사이에 열교환은 없으며 서로 역학적 일을 주고받을수 있을 뿐이다. 이 경우 계가 해준 혹은 받은 일은 초기상태와 최종상태에 의해 결정된다. 또한 계의 에너지 변화 역시 초기상태와 나중상태에 의해 결정된다.</p></li>
<li><p>계가 <span class="math inline">\(A\to B\)</span> 과정을 겪었을 때 에너지 변화 <span class="math inline">\(\Delta U = U_B-U_A\)</span> 라고 하자. 계가 단열되었으므로 <span class="math inline">\(\Delta U = W\)</span> 이다.</p></li>
<li><p>이제 계가 환경과 단열되지 않았다고 하자. 그렇다면 <span class="math inline">\(\Delta U \ne W\)</span> 이며 열의 형태로 에너지가 전달될 수 있다. 즉 더 일반적인 형태로 아래와 같이 쓸 수 있다. 이를 열역학 제 1 법칙 이라고 한다. <span id="eq-TD_energy_conservation_including_heat"><span class="math display">\[
\Delta U = Q + W.
\tag{21.6}\]</span></span></p></li>
<li><p>위 식에서 <span class="math inline">\(Q\)</span> 는 역학적 에너지(<span class="math inline">\(dV\ne 0\)</span>) 의 형태가 아닌 다른 형태로 전달되는 에너지 전체이다.</p></li>
<li><p>순환 과정일 경우 <span class="math inline">\(\Delta U = 0\)</span> 이므로 <span class="math inline">\(W=-Q\)</span> 이다.</p></li>
</ul>
</section>
</section>
<section id="sec-TD_ideal_gas_and_the_1st_law_of_thermodynamics" class="level2" data-number="21.5">
<h2 data-number="21.5" class="anchored" data-anchor-id="sec-TD_ideal_gas_and_the_1st_law_of_thermodynamics"><span class="header-section-number">21.5</span> 이상기체와 열역학 제 1 법칙</h2>
<section id="sec-TD_the_first_law_of_thermocynaics_in_Vp_diagram" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_the_first_law_of_thermocynaics_in_Vp_diagram">상태가 <span class="math inline">\((V,\,p)\)</span> 도식으로 표현되는 계에서의 열역학 제 1 법칙</h3>
<ul>
<li>동일한 유체로 이루어진 계와 같이 상태가 <span class="math inline">\(V,\,p,\,T\)</span> 가운데 두개로 정의 될 수 있는 계를 생각하자. 여기서 독립변수가 무엇인지를 정하기 위해 예를들어 아래와 같은 표기는 <span class="math inline">\(V\)</span> 가 일정한 상태에서의 <span class="math inline">\(\partial U/\partial T\)</span> 는 아래와 같이 표기한다.</li>
</ul>
<p><span class="math display">\[
\left(\dfrac{\partial U}{\partial T}\right)_V.
\]</span></p>
<ul>
<li>내부에너지 <span class="math inline">\(U\)</span>, 일 <span class="math inline">\(W\)</span>, 열 <span class="math inline">\(Q\)</span> 의 미소 변화를 보자. 여기서 주의할것은 <span class="math inline">\(U\)</span> 는 물질의 상태에만 의존하는 <strong>상태 함수(state function)</strong> 이지만 일이나 열은 상태에 도달하기까지의 과정에 의존하는 <strong>경로 함수(path function)</strong> 이라는 것이다. 이를 구분하기 위해 <span class="math inline">\(dU\)</span> 나 <span class="math inline">\(\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dW\)</span> 와 같이 다른 기호를 사용한다. 열역학 제 1 법칙에 의해 다음이 성립한다.</li>
</ul>
<p><span id="eq-TD_fermi_20"><span class="math display">\[
dU = \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ + \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dW .
\tag{21.7}\]</span></span></p>
<ul>
<li><p><span class="math inline">\(\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dW = -p\,dV\)</span> 이므로 다음과 같다.</p>
<p><span id="eq-TD_fermi_21"><span class="math display">\[
dU  = \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ - p\,dV
\tag{21.8}\]</span></span></p></li>
</ul>
</section>
<section id="sec-TD_heat_capapcity" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_heat_capapcity">열용량과 비열</h3>
<ul>
<li><p><span class="math inline">\(T,\,V\)</span> 를 독립변수로 정하면</p>
<p><span class="math display">\[
dU = \left(\dfrac{\partial U}{\partial T}\right)_V\,dT + \left(\dfrac{\partial U}{\partial V}\right)_T\, dV
\]</span></p>
<p>이며 <a href="#eq-TD_fermi_21" class="quarto-xref">식&nbsp;<span>21.8</span></a> 는 아래와 같이 쓸 수 있다. <span id="eq-TD_fermi_22"><span class="math display">\[
\left(\dfrac{\partial U}{\partial T}\right)_V\,dT + \left[p + \left(\dfrac{\partial U}{\partial V}\right)_T\right] \,dV = \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ.
\tag{21.9}\]</span></span></p></li>
<li><p><span class="math inline">\(T,\,p\)</span> 를 독립변수로 정하면 아래와 같은 식을 얻는다. <span id="eq-TD_fermi_23"><span class="math display">\[
\left[\left(\dfrac{\partial U}{\partial T}\right)_p + p\left(\dfrac{\partial V}{\partial T}\right)_V\right]\,dT + \left[\left(\dfrac{\partial U}{\partial p}\right)_T + p\left(\dfrac{\partial V}{\partial p}\right)_T\right]\,dp = \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ.
\tag{21.10}\]</span></span></p></li>
<li><p><span class="math inline">\(V,\,p\)</span> 를 독립변수로 정하면 아래와 같은 식을 얻는다. <span id="eq-TD_fermi_24"><span class="math display">\[
\left(\dfrac{\partial U}{\partial p}\right)_V\,dp + \left[p + \left(\dfrac{\partial U}{\partial V}\right)_p\right] \,dV = \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ.
\tag{21.11}\]</span></span></p></li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">노트</span><strong>정적열용량과 정압열용량</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<div id="def-CM_specific_heat" class="theorem definition">
<p><span class="theorem-title"><strong>정의 21.1</strong></span> 부피가 일정할 때 단위 온도만큼 온도를 올리기 위해 필요한 열량 <span class="math inline">\(C_V\)</span> 를 <strong>정적 열용량 (heat capacity at constant volumn)</strong> 이라고 하고 압력이 일정할 때 단위 온도만큼 온도를 올리기 위해 필요한 열량 <span class="math inline">\(C_p\)</span> 를 <strong>정압 열용량 (heat capacity at constant pressure)</strong> 이라고 한다. 즉</p>
<p><span id="eq-TD_fermi_25"><span class="math display">\[
C_V := \left(\dfrac{\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ}{dT}\right)_V,\qquad   C_p := \left(\dfrac{\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ}{dT}\right)_p
\tag{21.12}\]</span></span></p>
<p>이다.</p>
</div>
</div>
</div>
<ul>
<li><p><a href="#eq-TD_fermi_22" class="quarto-xref">식&nbsp;<span>21.9</span></a> 로부터 정적열용량과 정압열용량은 다음과 같다. <span class="math display">\[
\begin{aligned}
C_V &amp;= \left(\dfrac{\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ}{dT}\right)_V = \left(\dfrac{\partial U}{\partial T}\right)_V, \\[0.3em]
C_p &amp;= \left(\dfrac{\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ}{dT}\right)_p = \left(\dfrac{\partial U}{\partial T}\right)_p + p\left(\dfrac{\partial V}{\partial T}\right)_V,
\end{aligned}
\]</span></p></li>
<li><p>단위 질량당의 열용량을 <strong>비열 (specific heat capacity)</strong> 이라고 한다. 정적 비열 <span class="math inline">\(c_V\)</span> 와 정압 비열 <span class="math inline">\(c_p\)</span> 는 <span class="math inline">\(C_V,\,C_p\)</span> 를 각각 질량으로 나눈 값이다.</p></li>
</ul>
</section>
<section id="sec-TD_the_heat_capacity_of_ideal_gas" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_the_heat_capacity_of_ideal_gas">이상기체의 열용량</h3>
<p>독립변수로 <span class="math inline">\(T,\,V\)</span> 를 선택할 때 이상기체의 에너지 <span class="math inline">\(U=U(T)\)</span> 이며 <span class="math inline">\(V\)</span> 와는 독립적임이라는 것은 우선 Joule 에 의해 실험적으로 확인되었으며, 이론적으로는 열역학 제 2 법칙을 통해 보일 수 있다. Joule 의 실험은 아래와 같은 장치에서 이루어졌다.</p>
<div id="fig-TD_joule_exp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-TD_joule_exp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/joule_exp/joule_exp.png" class="img-fluid figure-img" width="300">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-TD_joule_exp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;21.5: 빨간색-밸브, 파란색-온도계
</figcaption>
</figure>
</div>
<p>두개의 챔버 <span class="math inline">\(A,\,B\)</span> 로 이루어진 콘테이너가 그림과 같이 열량계 속에 잠겨 있다. <span class="math inline">\(A,\,B\)</span> 는 벨브로 연결되어 있다. <span class="math inline">\(A\)</span> 는 가스로 차 있고 <span class="math inline">\(B\)</span> 는 진공상태에서 밸브는 잠겨 있다. 열평형 상태에 도달한 후 온도 <span class="math inline">\(T_1\)</span> 을 재고 밸브를 열고 나서 평형상태에 도달한 후 온도 <span class="math inline">\(T_2\)</span> 를 쟀을 때 Joule 은 <span class="math inline">\(T_1\)</span> 과 <span class="math inline">\(T_2\)</span> 가 거의 차이가 없음을 확인하였다. 이상기체의 경우 <span class="math inline">\(T_1=T_2\)</span> 일 것이다.</p>
<p><span class="math inline">\(T_1=T_2\)</span> 이므로 외부로부터의 열 전달이 없고 따라서 <span class="math inline">\(\Delta U = W\)</span> 인데 <span class="math inline">\(A\)</span> 와 <span class="math inline">\(B\)</span> 로 이루어진 계의 부피는 변화가 없으므로 <span class="math inline">\(W=0\)</span> 이다. 따라서 <span class="math inline">\(\Delta U=0\)</span> 이다. 즉 <span class="math inline">\(U_A = U_{A+B}\)</span> 이므로 우리는 이상기체의 에너지가 온도에만 관계가 있으며 부피와는 무관하다는 것을 알 수 있다. 즉 이상기체의 에너지 <span class="math inline">\(U=U(T)\)</span> 이다.</p>
<p>이제 이 함수를 알아보자. 우리는 실험적으로 이상기체의 정적 열용량 <span class="math inline">\(C_V\)</span> 는 온도에만 약간 의존한다는 것을 안다. 여기서는 이상기체의 정적 열용량이 우리가 관심있는 온도 영역에서 상수라고 가정하자. <span class="math inline">\(U= U(T)\)</span> 이므로</p>
<p><span id="eq-TD_heat_capacity_at_constant_volume_for_ideal_gas"><span class="math display">\[
C_V = \dfrac{dU}{dT}
\tag{21.13}\]</span></span></p>
<p>이며, 따라서</p>
<p><span id="eq-TD_integration_of_heat_capacity_at_constant_volume_for_ideal_gas"><span class="math display">\[
U = C_V T + U_0
\tag{21.14}\]</span></span></p>
<p>이다. 여기서 <span class="math inline">\(U_0\)</span> 는 <span class="math inline">\(0\,K\)</span> 에서의 이상기체의 에너지이다. <a href="#eq-TD_fermi_21" class="quarto-xref">식&nbsp;<span>21.8</span></a> 로부터</p>
<p><span id="eq-TD_fermi_30"><span class="math display">\[
C_V\,dT + p\,dV = \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ
\tag{21.15}\]</span></span></p>
<p>임을 안다. 이상기체 상태 방정식 <a href="#eq-TD_equation_of_state_for_perfect_gas" class="quarto-xref">식&nbsp;<span>21.4</span></a> 에서 <span class="math inline">\(\nu = m/M\)</span> 라 놓으면 (<span class="math inline">\(\nu\)</span> 는 기체의 몰수가 된다)</p>
<p><span class="math display">\[
p\,dV + v\,dp = \nu R\,dT
\]</span></p>
<p>을 얻는다. 이로부터</p>
<p><span class="math display">\[
(C_V + \nu R)dT  - v\,dp= \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ
\]</span></p>
<p>이므로 이상기체의 정압 열용량을 아래와 같이 얻을 수 있다.</p>
<p><span id="eq-TD_heat_capacity_at_constant_pressure_for_ideal_gas"><span class="math display">\[
C_p = \left(\dfrac{\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ}{dT}\right)_p = C_V + \nu R.
\tag{21.16}\]</span></span></p>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">
<div id="exm-TD_properties_of_ideal_gas" class="theorem example">
<p><span class="theorem-title"><strong>예제 21.1</strong></span> 우리는 이상기체에 대해 다음이 성립함을 보일 수 있다. <span id="eq-TD_partial_U_partial_T_at_constant_p"><span class="math display">\[
\left(\dfrac{\partial U}{\partial T}\right)_p = \dfrac{dU}{dT} = C_V, \qquad \left(\dfrac{\partial V}{\partial T}\right)_p = \dfrac{\nu R}{p}
\tag{21.17}\]</span></span></p>
<p><a href="#eq-TD_integration_of_heat_capacity_at_constant_volume_for_ideal_gas" class="quarto-xref">식&nbsp;<span>21.14</span></a> 으로부터</p>
<p><span class="math display">\[
\left(\dfrac{\partial U}{\partial T}\right)_p = C_V + \left(\dfrac{\partial U_0}{\partial T}\right)_p = C_V = \dfrac{dU}{dT}
\]</span></p>
<p>임을 안다. 또한 이상기체 상태방정식 <a href="#eq-TD_equation_of_state_for_perfect_gas" class="quarto-xref">식&nbsp;<span>21.4</span></a> 으로부터 <span class="math inline">\(V=\nu RT/p\)</span> 이므로</p>
<p><span class="math display">\[
\left(\dfrac{\partial V}{\partial T}\right)_p = \left(\dfrac{\partial (\nu RT/p)}{\partial T}\right)_p = \dfrac{\nu R}{p}.
\]</span></p>
</div>
</div>
<p>이후에 계산하겠지만 하나의 원자로 이루어진 기체 분자의 경우 <span class="math inline">\(C_V=\frac{3}{2}R\)</span>, <span class="math inline">\(C_p = \frac{5}{2}R\)</span> 이며 두개의 원자로 이루어진 기체 분자의 경우 <span class="math inline">\(C_V=\frac{5}{2}R\)</span>, <span class="math inline">\(C_p = \frac{7}{2}R\)</span> 이다.</p>
<p>여기서</p>
<p><span id="eq-TD_definition_of_specific_heat_ratio"><span class="math display">\[
\gamma := \dfrac{C_p}{C_V}
\tag{21.18}\]</span></span></p>
<p>를 <strong>비열비 (specific heat ratio)</strong> 혹은 <strong>adiabatic index</strong> 라고 한다. 이상기체의 경우 아래와 같다.</p>
<p><span class="math display">\[
\gamma = \dfrac{C_p}{C_V}=1+ \dfrac{\nu R}{C_V}.
\]</span></p>
<p>단원자 분자 이상기체는 <span class="math inline">\(\gamma=5/3\)</span>, 이원자 분자 이상기체는 <span class="math inline">\(7/5\)</span> 이다.</p>
</section>
<section id="sec-TD_adiabatic_reversible_process_of_ideal_gas" class="level3">
<h3 class="anchored" data-anchor-id="sec-TD_adiabatic_reversible_process_of_ideal_gas">이상기체의 단열 가역 과정</h3>
<p><strong>단열과정 (adiabatic process)</strong> 는 <span class="math inline">\(\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ=0\)</span> 인 과정을 말한다. <a href="#fig-TD_simple_system" class="quarto-xref">그림&nbsp;<span>21.1</span></a> 에서 실린더 벽과 피스톤이 모두 열을 전달하지 않는 재질로 되어 있으며 피스톤이 매우 느리게 움직이는 경우가 해당된다. 피스톤이 위로(혹은 실린더 바깥쪽으로) 움직이면 <span class="math inline">\(\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dW &lt; 0\)</span> 이며 아래로(혹은 실린더 안쪽으로) 움직이면 <span class="math inline">\(\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dW&gt;0\)</span> 이다. <span class="math inline">\(\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ=0\)</span> 이므로 <span class="math inline">\(dU=\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dW\)</span> 이다.</p>
<p><span class="math display">\[
C_V\,dT =- p\,dV \implies C_V\,dT = - \dfrac{\nu RT}{V}\,dV
\]</span></p>
<p>이므로</p>
<p><span class="math display">\[
\dfrac{dT}{T} = -  \dfrac{\nu R}{C_V}\dfrac{dV}{V}
\]</span></p>
<p>이며, 이로부터 다음 관계를 얻는다.</p>
<p><span id="eq-TD_relations_1_in_adiabatic_revirsible_process_of_ideal_gas"><span class="math display">\[
TV^{\nu R/C_V}= TV^{\gamma -1} =\text{constant.}
\tag{21.19}\]</span></span></p>
<p>또한 이상기체 상태방정식을 통해 아래 관계를 얻을 수 있다.</p>
<p><span id="eq-TD_relations_2_in_adiabatic_revirsible_process_of_ideal_gas"><span class="math display">\[
pV^\gamma= \text{constant.},\qquad Tp^{(1-\gamma)/\gamma}=\text{constant.}
\tag{21.20}\]</span></span></p>
<p>단열 가역과정이 아닌 등온과정에서는 <span class="math inline">\(pV=\text{constant}\)</span> 가 성립한다는 것을 안다.</p>
<div id="fig-TD_adiabatic_and_isothermal_process" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-TD_adiabatic_and_isothermal_process-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/adiabatic_process/adiabatic.png" class="img-fluid figure-img" width="350">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-TD_adiabatic_and_isothermal_process-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;21.6: 단열과정과 등온과정
</figcaption>
</figure>
</div>
</section>
<section id="잠열" class="level3">
<h3 class="anchored" data-anchor-id="잠열">잠열</h3>
<p>특별한 경우 열을 가해도 온도가 올라가지 않는 경우가 있다. 보통 물의 끓음이나 녹음 같은 상전이가 발생할 때 이며 이 경우 비열은 무한대가 된다. 단위 질량당 상전이에 필요한 열을 <strong>잠열 (latent heat)</strong> 이라고 한다. 하지만 이 정의는 모호한데 상전이 과정에서 어떤 일을 할수도 있기 때문이다. 일반적으로 압력이 일정한 상태를 가정하고, 등압 팽창 혹은 수축 과정 이외에 필요한 열을 잠열이라고 한다.</p>
</section>
<section id="연습문제-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="연습문제-1">연습문제</h3>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">
<div id="exr-TD_blundell_12_2" class="theorem exercise">
<p><span class="theorem-title"><strong>연습문제 21.2 (Blundell 12.2)</strong></span> 이상기체의 경우 <span class="math inline">\(pV=\phi(T)\)</span> 로 주어진다. 이것은 다음을 의미함을 보여라.</p>
<p><span id="eq-exr-TD_blundell_12_2_1"><span class="math display">\[
\left(\dfrac{\partial p}{\partial T}\right)_V = \dfrac{1}{V}\dfrac{d\phi}{dT},\qquad \left(\dfrac{\partial V}{\partial T}\right)_p = \dfrac{1}{p}\dfrac{d\phi}{dT}.
\tag{21.21}\]</span></span></p>
<p>또한 다음이 성립함을 보여라.</p>
<p><span id="eq-exr-TD_blundell_12_2_2"><span class="math display">\[
\left(\dfrac{\partial Q}{\partial V}\right)_p = C_p \left(\dfrac{\partial T}{\partial V}\right)_p,\qquad \left(\dfrac{\partial Q}{\partial p}\right)_V = C_V \left(\dfrac{\partial T}{\partial p}\right)_V.
\tag{21.22}\]</span></span></p>
<p>단열 과정에서 다음이 성립함한다.</p>
<p><span id="eq-exr-TD_blundell_12_2_3"><span class="math display">\[
\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ = \left(\dfrac{\partial Q}{\partial p}\right)_V \, dp + \left(\dfrac{\partial Q}{\partial V}\right)_p \, dV = 0.
\tag{21.23}\]</span></span></p>
<p>이 때 <span class="math inline">\(pV^\gamma\)</span> 가 상수임을 보여라.</p>
</div>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>(해답)</em>. </span><a href="#eq-exr-TD_blundell_12_2_1" class="quarto-xref">식&nbsp;<span>21.21</span></a> 는 자명하다. Blundell 에서는 일단 <span class="math inline">\(U=U(T,\,V)\)</span> 임을 가정한다.</p>
<p><span id="eq-exr-TD_blundell_12_2_4"><span class="math display">\[
dU = \left(\dfrac{\partial U}{\partial T}\right)_V dT + \left(\dfrac{\partial U}{\partial V}\right)_T \, dV
\tag{21.24}\]</span></span></p>
<p>이므로</p>
<p><span class="math display">\[
\begin{aligned}
dQ &amp;= dU + p\,dV = \left(\dfrac{\partial U}{\partial T}\right)_V \,dT + \left[\left(\dfrac{\partial U}{\partial V}\right)_T + p \right] \, dV
\end{aligned}
\]</span></p>
<p>이다. 이로부터,</p>
<p><span class="math display">\[
\begin{aligned}
C_p &amp;= \left(\dfrac{\partial Q}{\partial T}\right)_p = \left(\dfrac{\partial U}{\partial T}\right)_V +  \left[\left(\dfrac{\partial U}{\partial V}\right)_T + p \right] \, \left(\dfrac{\partial V}{\partial T}\right)_p, \\[0.3em]
\left(\dfrac{\partial Q}{\partial V}\right)_p &amp;= \left(\dfrac{\partial U}{\partial T}\right)_V \left(\dfrac{\partial T}{\partial V}\right)_p + \left(\dfrac{\partial U}{\partial V}\right)_T + p
\end{aligned}
\]</span></p>
<p><a href="0A_mathematics.html#cor-TD_reciprocity_relation_of_partial_derivative" class="quarto-xref">따름정리&nbsp;<span>25.1</span></a> 에 따라</p>
<p><span class="math display">\[
\left(\dfrac{\partial V}{\partial T}\right)_p \left(\dfrac{\partial T}{\partial V}\right)_p =1
\]</span></p>
<p>이므로</p>
<p><span class="math display">\[
\left(\dfrac{\partial Q}{\partial V}\right)_p = C_p\left(\dfrac{\partial T}{\partial V}\right)_p
\]</span></p>
<p>이다. 또한 <a href="#eq-exr-TD_blundell_12_2_4" class="quarto-xref">식&nbsp;<span>21.24</span></a> 로부터</p>
<p><span class="math display">\[
\left(\dfrac{\partial Q}{\partial p}\right)_V = \left(\dfrac{\partial U}{\partial T}\right)_V \left(\dfrac{\partial T}{\partial p}\right)_V
\]</span></p>
<p>이며</p>
<p><span class="math display">\[
C_V = \left(\dfrac{\partial Q}{\partial T}\right)_V= \left(\dfrac{\partial U}{\partial T}\right)_V
\]</span></p>
<p>이므로</p>
<p><span class="math display">\[
\left(\dfrac{\partial Q}{\partial p}\right)_V = C_V \left(\dfrac{\partial T}{\partial p}\right)_V
\]</span></p>
<p>이다. 단열 과정에서 <a href="#eq-exr-TD_blundell_12_2_3" class="quarto-xref">식&nbsp;<span>21.23</span></a> 이 성림하므로</p>
<p><span class="math display">\[
\begin{aligned}
0 = \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ &amp;= C_V \left(\dfrac{\partial T}{\partial p}\right)_V dp + C_p \left(\dfrac{\partial T}{\partial V}\right)_p dV
\end{aligned}
\]</span></p>
<p>이다. <a href="0A_mathematics.html#cor-TD_reciprocity_relation_of_partial_derivative" class="quarto-xref">따름정리&nbsp;<span>25.1</span></a> 와 <a href="#eq-exr-TD_blundell_12_2_1" class="quarto-xref">식&nbsp;<span>21.21</span></a> 로부터</p>
<p><span class="math display">\[
\left(\dfrac{\partial T}{\partial p}\right)_V =\dfrac{V}{df/dT}, \quad \left(\dfrac{\partial T}{\partial V}\right)_p = \dfrac{p}{df/dT}
\]</span></p>
<p>임을 안다. 또한 <span class="math inline">\(C_p = \gamma C_V\)</span> 이므로</p>
<p><span class="math display">\[
\begin{aligned}
&amp;0 = \dfrac{V}{df/dT} dp + \dfrac{\gamma p}{df/dT} dV \\[0.3em]
\implies &amp;\gamma \dfrac{dV}{V} + \dfrac{dp}{p} = 0 \\[0.3em]
\implies &amp; pV^\gamma = \text{constant.}
\end{aligned}
\]</span></p>
</div>
<br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">
<div id="exr-TD_blundell_12_3" class="theorem exercise">
<p><span class="theorem-title"><strong>연습문제 21.3 (Blundell 12.3)</strong></span> 상수 <span class="math inline">\(A,\,B\)</span> 에 대해 다음과 같이 쓸 수 있는 이유를 설명하라.</p>
<p><span id="eq-exr-TD_blundell_12_3_1"><span class="math display">\[
\begin{aligned}
\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ &amp;= C_p dT + A\,dp \\[0.3em]
\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ &amp;= C_V dT + B\,dV.
\end{aligned}
\tag{21.25}\]</span></span></p>
<p>위 두식을 빼서 다음이 성립함을 보여라.</p>
<p><span id="eq-exr-TD_blundell_12_3_2"><span class="math display">\[
(C_p-C_V)\,dT = B dV - Adp.
\tag{21.26}\]</span></span></p>
<p>또한 온도가 일정할 때 다음이 성립함을 보여라.</p>
<p><span id="eq-exr-TD_blundell_12_3_3"><span class="math display">\[
\left(\dfrac{\partial p}{\partial V}\right)_T = \dfrac{B}{A}.
\tag{21.27}\]</span></span></p>
<p>단열 과정에서 다음이 성립함을 보여라.</p>
<p><span id="eq-exr-TD_blundell_12_3_4"><span class="math display">\[
\begin{aligned}
dp &amp;= -(C_p/A)\,dT,\\[0.3em]
dV &amp;= -(C_V/B) \,dT.
\end{aligned}
\tag{21.28}\]</span></span></p>
<p>이로부터 단열 과정에서 다음이 성립함을 보여라.</p>
<p><span id="eq-exr-TD_blundell_12_3_5"><span class="math display">\[
\begin{aligned}
\left(\dfrac{\partial p}{\partial V}\right)_\text{adiabatic} &amp;= \gamma \left(\dfrac{\partial p}{\partial V}\right)_T, \\[0.3em]
\left(\dfrac{\partial V}{\partial T}\right)_\text{adiabatic} &amp;= \dfrac{1}{1-\gamma} \left(\dfrac{\partial V}{\partial T}\right)_p,\\[0.3em]
\left(\dfrac{\partial p}{\partial T}\right)_\text{adiabatic} &amp;= \dfrac{\gamma}{\gamma -1}\left(\dfrac{\partial p}{\partial T}\right)_V.
\end{aligned}
\tag{21.29}\]</span></span></p>
</div>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>(해답)</em>. </span>이상기체에서 <span class="math inline">\(p,\,T,\,V\)</span> 가운데 두 변수로 <span class="math inline">\(dU,\, \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ,\, \rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dW\)</span> 를 기술 할 수 있다는 것을 안다. <a href="#eq-exr-TD_blundell_12_3_1" class="quarto-xref">식&nbsp;<span>21.25</span></a> 에서 첫번째 식은 <span class="math inline">\((T,\,p)\)</span>, 두번째 식은 <span class="math inline">\((T,\,V)\)</span> 로 기술한 것이다. 두 식을 빼면 <a href="#eq-exr-TD_blundell_12_3_2" class="quarto-xref">식&nbsp;<span>21.26</span></a> 를 얻으며 <span class="math inline">\(dT=0\)</span> 에 대해 <a href="#eq-exr-TD_blundell_12_3_3" class="quarto-xref">식&nbsp;<span>21.27</span></a> 을 얻는다. 단열과정은 <span class="math inline">\(\rlap{\raise{0.8ex}{\hspace{0.12em}\scriptstyle -}}dQ=0\)</span> 이므로 <a href="#eq-exr-TD_blundell_12_3_4" class="quarto-xref">식&nbsp;<span>21.28</span></a> 를 얻는다.</p>
<p><a href="#eq-exr-TD_blundell_12_3_4" class="quarto-xref">식&nbsp;<span>21.28</span></a> 으로부터</p>
<p><span class="math display">\[
dp = -\left(\dfrac{C_p}{A}\right)dT = \left(\dfrac{C_p}{A}\right)\left(\dfrac{B}{C_V}\right)dV
\]</span></p>
<p>이므로</p>
<p><span class="math display">\[
\left(\dfrac{\partial p}{\partial V}\right)_\text{adiabatic} = \dfrac{C_p}{C_V}\dfrac{B}{A} = \gamma \left(\dfrac{\partial p}{\partial V}\right)_T
\]</span></p>
<p>이며, <a href="#eq-exr-TD_blundell_12_3_2" class="quarto-xref">식&nbsp;<span>21.26</span></a> 에서 <span class="math inline">\(dp=0\)</span> 일 때 <span class="math inline">\(\dfrac{1}{B} = \dfrac{1}{C_p-C_V}\left(\dfrac{\partial V}{\partial T} \right)_p\)</span> 이므로</p>
<p><span class="math display">\[
\left(\dfrac{\partial V}{\partial T}\right)_\text{adiabatic} = - \dfrac{C_V}{B} = - \dfrac{C_V}{C_p-C_V}\left(\dfrac{dV}{dT}\right)_p = \dfrac{1}{1-\gamma}\left(\dfrac{dV}{dT}\right)_p
\]</span></p>
<p>이다. 또한 <a href="#eq-exr-TD_blundell_12_3_2" class="quarto-xref">식&nbsp;<span>21.26</span></a> 에서 <span class="math inline">\(dV=0\)</span> 일 때 <span class="math inline">\(\dfrac{1}{A} = - \dfrac{1}{C_p-C_V} \left(\dfrac{\partial p}{\partial T}\right)_V\)</span> 이므로</p>
<p><span class="math display">\[
\left(\dfrac{\partial p}{\partial T}\right)_\text{adiabatic} = - \dfrac{C_p}{A} = \dfrac{C_p}{C_p-C_V} \left(\dfrac{\partial p}{\partial T}\right)_V = \dfrac{\gamma}{\gamma-1} \left(\dfrac{\partial p}{\partial T}\right)_V
\]</span></p>
<p>이다.</p>
</div>
<br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">
<div id="exr-TD_schroeder_1_36" class="theorem exercise">
<p><span class="theorem-title"><strong>연습문제 21.4 (Schroeder 1.36)</strong></span> 자전거 타이어에 공기를 주입할 1기압에서 1 리터의 공기를 단열 압축하여 7 기압으로 압축하였다. 공기는 대부분 질소와 산소 같은 이원자 분자이다.</p>
<p>(<span class="math inline">\(a\)</span>) 압축 후 최종 부피는 얼마인가?</p>
<p>(<span class="math inline">\(b\)</span>) 공기를 압축하며 수행한 일은 얼마인가?</p>
<p>(<span class="math inline">\(c\)</span>) 최초의 온도가 <span class="math inline">\(300\,\text{K}\)</span> 였다면 압축 후 온도는 얼마인가?</p>
</div>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>(해답)</em>. </span>(<span class="math inline">\(a\)</span>) 이원자 분자 이상기체의 경우 <span class="math inline">\(\gamma=7/5\)</span> 이다. <a href="#eq-TD_relations_2_in_adiabatic_revirsible_process_of_ideal_gas" class="quarto-xref">식&nbsp;<span>21.20</span></a> 의 첫번째 식으로부터 <span class="math inline">\(1=7V^{7/5}\)</span> 이므로 <span class="math inline">\(V=0.25\,\text{liter}\)</span>.</p>
<p>(<span class="math inline">\(b\)</span>) <span class="math inline">\(pV^\gamma=pV^{7/5}=1\,\text{liter}\cdot\text{atm}^{7/5}\)</span> 이므로</p>
<p><span class="math display">\[
W = -\int_1^{0.25} p\,dV = -\int_1^{0.25} \dfrac{dV}{V^{7/5}} = 1.85\, \text{atm}\cdot \text{liter} = 188\, \text{J}
\]</span></p>
<p>(<span class="math inline">\(c\)</span>) <a href="#eq-TD_relations_2_in_adiabatic_revirsible_process_of_ideal_gas" class="quarto-xref">식&nbsp;<span>21.20</span></a> 의 두번째 식으로부터 <span class="math inline">\(523\,\text{K}\)</span> 임을 알 수 있다.</p>
</div>
<br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">
<div id="exr-TD_schroeder_1_39" class="theorem exercise">
<p><span class="theorem-title"><strong>연습문제 21.5 (Schroeder 1.39)</strong></span> 연속적인 매질의 진동에 뉴턴의 법칙을 적용하여 소기의 속도 <span class="math inline">\(c_s\)</span> 가 다음과 같다는 것을 보일 수 있다.</p>
<p><span class="math display">\[
c_s = \sqrt{B/\rho}.
\]</span></p>
<p>여기서 <span class="math inline">\(\rho\)</span> 는 매질의 밀도이고 <span class="math inline">\(B\)</span> 는 물질의 강도의 척도인 부피탄성계수(bulk modulus) 이다. 정확히는 다음과 같이 정의된다.</p>
<p><span class="math display">\[
B := - V \dfrac{dp}{dV}
\]</span></p>
<p>이 압축이 등온인지 단연일지 혹은 다른 방법에 의한건지 아직 정하지 않았으므로 위의 정의는 아직 모호하다.</p>
<p>(<span class="math inline">\(a\)</span>) 이상기체의 부피탄성계수를 등온과 단열 압축에 대해 각각 계산하라.</p>
<p>(<span class="math inline">\(b\)</span>) 음파의 속도를 계산하는데 있어 단열 압축을 하용하여야 하는 이유를 논하라.</p>
<p>(<span class="math inline">\(c\)</span>) 주어진 온도와 평균 분자 질량에 대해 이상기체에서의 음속을 계산하라. 이 결과를 기체에서의 분자의평균제곱근 속도 식과 비교하라.</p>
<p>(<span class="math inline">\(d\)</span>) 스코틀랜드의 배틀필드 밴드가 유타에서 연주할 때 한 연주가가 고도로 인해 백파이프의 음정이 나갔다는 것을 발견했다. 고도가 음속에 미치는 영향, 즉 파이프에서의 정상파의 진동수에 미치는 영향을 예상 할 수 있는가? 그렇다면 어느 방향으로? 그렇지 않다면 왜?</p>
</div>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>(해답)</em>. </span>(<span class="math inline">\(a\)</span>) 등온 압축이라면 <span class="math inline">\(pV=A=\text{constant}\)</span> 이므로 <span class="math inline">\(B = p\)</span>. 단열 압축시 <span class="math inline">\(pV^\gamma = \text{constant}=C\)</span> 로부터 <span class="math inline">\(B = \gamma p\)</span>.</p>
<p>(<span class="math inline">\(b\)</span>)</p>
<p>(<span class="math inline">\(c\)</span>) 공기분자의 경우 이원자 분자가 지배적이므로 <span class="math inline">\(\gamma = 7/5\)</span> 로 놓을 수 있다. <span class="math inline">\(p=1\,\text{atm} = 101,325 \text{N/m}^2\)</span>, <span class="math inline">\(\rho = 1.225\,\text{kg/m}^3\)</span> 이므로 <span class="math inline">\(c_s = \sqrt{B/\rho}=340.3\,\text{m/sec}\)</span></p>
<p>(<span class="math inline">\(d\)</span>) <span class="math inline">\(B\propto p\)</span> 이며 <span class="math inline">\(\rho \propto p\)</span> 이므로 <span class="math inline">\(c_s\)</span> 는 온도가 일정할 때 차이가 없다. 그렇다면 아마 온도차이일 것이다.</p>
</div>
<br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">
<div id="exr-TD_schroeder_1_46" class="theorem exercise">
<p><span class="theorem-title"><strong>연습문제 21.6 (Schroeder 1.46)</strong></span> 고체나 액체의 열용량은 대부분 일정한 압력 상태에서 측정된다. 왜인지 보이기 위해 여기서는 <span class="math inline">\(T\)</span> 의 변화에 따른 <span class="math inline">\(V\)</span> 의 변화를 없에기 위한 압력값을 구해보자.</p>
<p>(<span class="math inline">\(a\)</span>) 물질의 <strong>열팽창 계수 (thermal expansion coefficient)</strong> <span class="math inline">\(\beta\)</span> 는 다음과 같이 정의된다.</p>
<p><span id="eq-TD_definition_of_thermal_expansion_coefficient"><span class="math display">\[
\beta := \dfrac {1}{V}\left(\dfrac{\partial V}{\partial T}\right)_p.
\tag{21.30}\]</span></span></p>
<p>압력을 일정하게 유지하면서 물질을 압축시킬 때 물질의 부피의 변화 <span class="math inline">\(dV_1\)</span> 을 <span class="math inline">\(dT\)</span> 와 <span class="math inline">\(\beta\)</span> 를 이용하여 기술하라.</p>
<p>(<span class="math inline">\(b\)</span>) <strong>등온 압축률 (isothermal compressibility)</strong> <span class="math inline">\(\kappa_T\)</span> 는 다음과 같이 정의된다.</p>
<p><span id="eq-TD_definition_of_isothermal_compressibility"><span class="math display">\[
\kappa_T = - \dfrac{1}{V}\left(\dfrac{\partial V}{\partial p}\right)_T.
\tag{21.31}\]</span></span></p>
<p>온도를 일정하게 유지하면서 물질을 약간 압축시킬 때의 부피 변화 <span class="math inline">\(V_2\)</span> 를 <span class="math inline">\(dp\)</span> 에 대해 표현하라.</p>
<p>(<span class="math inline">\(c\)</span>) (<span class="math inline">\(b\)</span>) 에 의한 압축에 의해 <span class="math inline">\((a)\)</span> 에 의한 팽창이 상쇄되도록 합축했다고 하자. 그렇다면 이 경우 <span class="math inline">\((dp)/(dT)=\left(\partial p/\partial T\right)_V\)</span> 이다. 이 편미분을 <span class="math inline">\(\beta,\,\kappa_T\)</span> 로 표현하라. 이 경우</p>
<p><span id="eq-TD_cyclic_relation_of_partial_derivatives"><span class="math display">\[
\left(\dfrac{\partial p}{\partial T}\right)_V = - \dfrac{\left(\partial V/\partial T\right)_p}{\left(\partial V/\partial p\right)_T}
\tag{21.32}\]</span></span></p>
<p>를 얻어야 한다(편미분의 삼중곱 규칙 혹은 순환 규칙이라고 한다). 위 관계는 순전히 수학적인 관계이다.</p>
<p>(<span class="math inline">\(d\)</span>) 이상기체에 대해 <span class="math inline">\(\beta,\,\kappa_T,\,(\partial p/\partial T)_V\)</span> 를 얻고 <a href="#eq-TD_cyclic_relation_of_partial_derivatives" class="quarto-xref">식&nbsp;<span>21.32</span></a> 가 성립하는지 비교하라.</p>
</div>
</div>
<div class="proof solution">
<p><span class="proof-title"><em>(해답)</em>. </span><span class="math inline">\(T,\,p\)</span> 를 독립변수로 할 때 <span class="math display">\[
dV = \left(\dfrac{\partial V}{\partial T}\right)_p\,\,dT + \left(\dfrac{\partial V}{\partial p}\right)_T\,dp
\]</span></p>
<p>임을 이용한다.</p>
<p>(<span class="math inline">\(a\)</span>) <span class="math inline">\(dV_1 = \beta V\,dT\)</span></p>
<p>(<span class="math inline">\(b\)</span>) <span class="math inline">\(dV_2 = -\kappa_T V dp\)</span></p>
<p>(<span class="math inline">\(c\)</span>) <span class="math inline">\(\left(\dfrac{\partial p}{\partial T}\right)_V = \dfrac{\beta}{\kappa_T} = - \dfrac{\left(\partial V/\partial T\right)_p}{\left(\partial V\partial p\right)_T}.\)</span></p>
<p>(<span class="math inline">\(d\)</span>) 이상기체의 경우 이상기체 상태방정식 <span class="math inline">\(pV=\nu k_BT\)</span> 로부터,</p>
<p><span class="math display">\[
\begin{aligned}
\beta &amp;=\dfrac{1}{V}\left(\dfrac{\partial V}{\partial T}\right)_p = \dfrac{1}{T}, \\[0.3em]
\kappa_T &amp;= - \dfrac{1}{V}\left(\dfrac{\partial V}{\partial p}\right)_T = \dfrac{1}{p}, \\[0.3em]
\left(\dfrac{\partial p}{\partial T}\right)_V &amp;= \dfrac{p}{T}= \dfrac{\beta}{\kappa_T}.
\end{aligned}
\]</span></p>
</div>
<p><br></p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Fermi1956ThermodynamicsDover" class="csl-entry" role="listitem">
Fermi, Enrico. 1956. <em>Thermodynamics</em>. New ed. Dover Publications.
</div>
<div id="ref-Schroeder2000introduction" class="csl-entry" role="listitem">
Schroeder, D. V. 2000. <em>An Introduction to Thermal Physics</em>. Addison Wesley. <a href="https://books.google.co.kr/books?id=1gosQgAACAAJ">https://books.google.co.kr/books?id=1gosQgAACAAJ</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../src/ThermalPhysics/00_index.html" class="pagination-link" aria-label="열역학">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">열역학</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../src/ThermalPhysics/02_entropy.html" class="pagination-link" aria-label="열역학 제 2 법칙-열역학적 접근">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">열역학 제 2 법칙-열역학적 접근</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>