---
title: "해밀턴 동역학"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

</br>

우리는 라그랑지안이 운동방정식을 세우고 그로부터 역학계를 기술하는데 아주 유용하다는 것을 안다. 이제 소위 해밀토니안(Hamintonian) 을 통해 운동을 기술하는 방법을 소개하고자 한다. 실제의 운동방정식을 세우고 푸는데 해밀토니안 방법이 라그랑지안 방법보다 유리한 경우는 거의 없다. 그러나 해밀토니안 방법은 고전역학 이후에 발전한 통계역학과 양자역학의 이론적 발전에 지대한 영향을 끼쳤으며, 고전역학을 새로운 관점을 보는데도 매우 유용하다.

여기서는 모든 시스템이 holonomic 이며(즉 역학적 제한조건이 좌표에만 의존한다), 힘이 monogenic 이거나 (즉 위치만의 함수인 포텐셜에 의해 힘이 주어진다) 속도에 의존적인 일반화된 포텐셜의 미분으로 주어지는 경우만을 생각하기로 하자.

</br>

## 르장드르 변환과 해밀턴 운동방정식

### 라그랑지안 역학과 해밀토니안 역학 {#sec-CM_lagrangian_and_hamiltonian_mechanics_intro}

$n$-자유도 시스템의 라그랑지안 역학은 $n$ 개의 2차 미분방정식(라그랑쥬 방정식) 으로 기술된다.

$$
\dfrac{d}{dt}\left(\dfrac{\partial L}{\partial \dot{q}_j}\right) - \dfrac{\partial L}{\partial q_j} = 0.
$$

이 방정식의 해를 구하기 위해서는 $2n$ 개의 초기값이 필요하며 ($1$) 특정 시간 $t$ 에 대해 $n$ 개의 $q_i(t)$ 와 역시 $n$ 개의 $\dot{q}(t_i)$ 이거나 ($2$) 두 시간 $t_1,\,t_2$ 에 대해 $n$ 개의 $q_i(t_1)$ 과 $q_i(t_2)$ 이다. 즉 $n$ 개의 독립 변수 $\{q_i\}$ 와 시간에 대한 미분 $\{\dot{q}_i\}$ 에 관한 문제이다. 라그랑지안은  각각의 일반화된 좌표로 이루어진 $n$ 차원 짜임새 공간에서 표현된다.

이에 반해 $n$-자유도 시스템의 해밀토니안 역학은 $2n$ 개의 독립변수에 대한 $2n$ 개의 1차 이분방정식으로 기술된다. 필요한 초기조건은 라그랑지안과 동일한 $2n$ 개이며, $2n$ 차원의 위상 공간에서 표현된다. 이 $2n$ 개의 독립변수는 $n$ 개의 일반화된 변수 $\{q_i\}$ 와 $n$ 개의 정준 운동량 $\{p_i\}$ 이며 $(\bf{q},\, \bf{p})$ 를 **정준 변수 (canonical variables)** 라고 한다. 

$$
\boxed{\bf{p} := \dfrac{\partial L(\bf{q},\, \dot{\bf{q}},\,t)}{\partial \dot{\bf{q}}},\qquad \text{or}\qquad  p_i = \dfrac{\partial L(\bf{q},\, \dot{\bf{q}},\,t)}{\partial \dot{q}_i}. }
$$ {#eq-CM_canonical_momentum}

</br>

::: {.callout-caution icon="false"}

#### 표기법에 대해

특별한 언급이 없는 한 이 장에서 $p_i$ 는 일반화된 좌표 $q_i$ 에 대한 정준운동량을 의미하며 질량에 속도를 곱한 선형 운동량과는 다르다. 일반화된 좌표를 $Q$ 나 $Q_i$ 와 같이 쓸 때의 정준운동량은 $P$ 나 $P_i$ 로 표기하기로 한다. 

또한 다변수 함수의 편미분에 대해 @def-MS_derivative_to_vector 의 표기법을 사용한다.

:::

</br>

### 르장드르 변환 {#sec-CM_legendre_transformation}

- 참고자료 : @Zia2009

$\bf{x},\, \bf{y}\in \R^n$ 이며 $F:\R^{2n} \to \R$ 이라고 하자. $F$ 가 미분가능하다면

$$
dF = \sum_{i=1}^n \dfrac{\partial F}{\partial x_i} dx_i + \sum_{i=1}^n \dfrac{\partial F}{\partial y_j}dy_j = \dfrac{\partial F}{\partial \bf{x}}\bf{\cdot} d\bf{x} + \dfrac{\partial F}{\partial \bf{y}} \bf{\cdot} d\bf{y}
$$

이며, $\bf{u}=\dfrac{\partial F}{\partial \bf{x}}$ 에 대해

$$
G =  \bf{ u\cdot x} - F
$$

라고 하면

$$
dG = \bf{x \cdot} d\bf{u}  + \bf{u \cdot} d\bf{x}  - dF =  \bf{x \cdot}d\bf{u} - \dfrac{\partial F}{\partial \bf{y}} \bf{\cdot} d\bf{y}
$$

이다. 그렇다면 $G=G(\bf{u},\, \bf{y})$ 이며, $\dfrac{\partial G}{\partial \bf{u}} = \bf{x},\, \dfrac{\partial G}{\partial \bf{y}} = - \dfrac{\partial F}{\partial \bf{y}}$ 이다. 

</br>

### 해밀토니안 {#sec-CM_hamiltonian}

::: {.callout-note appearance="minimal" icon="false"}

::: {#def-CM_hamiltonian}

#### 해밀토니안
라그랑지안 $L(\bf{q},\, \dot{\bf{q}},\,t)$ 에 대해 아래와 같은 르장드르 변환을 수행하여 얻은 $H(\bf{q},\, \bf{p},\,t)$ 를 **해밀토니안(Hamiltonian)** 이라고 한다. 

$$
H\left(\bf{q}, \bf{p}, t\right) = \sum_{i} \dot{q}_i p_i - L(\bf{q}, \dot{\bf{q}}, t)
$$ {#eq-CM_hamiltonian}

:::

:::

</br>

해밀토니안은 $\bf{q},\, \bf{p},\, t$ 에 대한 함수이므로 그 미분형식은 다음과 같다.

$$
dH = \sum_i \left(\dfrac{\partial H}{\partial q_i}\right) dq_i + \sum_i \left(\dfrac{\partial H}{\partial p_i}\right) dp_i + \dfrac{\partial H}{\partial t}\, dt
$$ {#eq-CM_differential_form_of_hamiltonian}

또한 @eq-CM_hamiltonian 으로 부터, 

$$
dH = \sum_i\left(-\dfrac{\partial L}{\partial q_i}\right)dq_i + \sum_i \left(\dot{q}_i\right)\, dp_i + \left(p_i - \sum_i \dfrac{\partial L}{\partial \dot{q}_i}\right) d\dot{q}_i - \dfrac{\partial L}{\partial t}\,dt
$$

을 얻는다. 여기서 $d\dot{q}_i$ 앞의 항은 $p_i$ 의 정의에 의해 $0$ 이다. 또한 오일러 라그랑쥬 방정식에 의해

$$
0 = \dfrac{d}{dt}\left( \dfrac{\partial L}{\partial \dot{q}_i}\right) - \dfrac{\partial L}{\partial q_i} = \dot{p}_i - \dfrac{\partial L}{\partial q_i} 
$$

이므로, 

$$
dH = -\sum_i (\dot{p}_i dq_i + \dot{q}_i dp_i ) - \dfrac{\partial L}{\partial t} dt
$$

이며 이로부터

$$
\dot{q}_i = \dfrac{\partial H}{\partial p_i},\qquad \dot{p}_i =- \dfrac{\partial H}{\partial q_i}, 
$$ {#eq-CM_canonical_equation_of_hamiltonian}

$$
\dfrac{\partial H}{\partial t} = -\dfrac{\partial L}{\partial t}
$$ {#eq-CM_time_dependence_of_hamiltonian} 

를 얻는다. @eq-CM_canonical_equation_of_hamiltonian 을 **해밀턴 정준 방정식(canonical equations of Haminton)** 이라고 부른다. 우리는 이를 통해 $n$ 개의 2차 미분방정식(라그랑쥬 방정식) 을 $2n$ 개의 1차 미분방정식(해밀턴의 정준 방정식) 으로 바꿨다. 차이는 (이것은 매우 중요하다) 라그랑지안이 일반화된 좌표계에서 $\bf{q},\, \dot{\bf{q}},\,t$ 의 함수라면 해밀토니안은 $\bf{q},\, \bf{p},\,t$ 의 함수라는 것이다. 해밀턴 정준방정식을 따르는 좌표 $\bf{q},\, \bf{p}$ 를 **정준 좌표 (canonical coordinate)** 라고 한다.(운동량 변수도 정준 좌표에 포함된다.)

</br>

### 해밀토니안을 직접 구할 수 있는 경우

해밀토니안은 라그랑지안에 대한 르장드르 변환으로 정의된다. 따라서 다음과 같은 순서로 해밀토니안을 구한다.

&emsp;($1$) 적절한 일반화된 좌표계에서 라그랑지안 $L(\bf{q},\, \dot{\bf{q}},\,t)$ 를 구한다.

&emsp;($2$) 각각의 일반화된 좌표 $q_i$ 에 대한 정준 운동량 $p_i = \dfrac{\partial L}{\partial \dot{q}_i}$ 를 구한다.

&emsp;($3$) @eq-CM_hamiltonian 로 해밀토니안을 구한다.


이것은 진짜로 일반화된 좌표계에서는 쉽지 않은 일이다. $\bf{p}$ 를 구한 후 모든 $\dot{q}_j$ 를 $\bf{q},\, \bf{p},\,t$ 에 대한 함수로 다시 기술해야 하기 때문이다. 하지만 물리적으로 중요한 많은 문제에 대해서는 지름길이 존재한다.

우선 라그랑지안 $L$ 이 $\{\dot{q}_i\}$ 에 대해 $0$, $1$, $2$ 차 로 homogeneous 한 함수의 합으로 표현 할 수 있을 때이다. 어떤 함수$f(x_1,\ldots,\,x_n)$ 이 $k$ 차로 homogeneous 하다는 것은 

$$
f(tx_1,\ldots,\,t x_n) = t^k f(x_1,\ldots,\,x_n)
$$ {#eq-CM_homogeneous_function}

이 성립한다는 의미다. 이 경우,

$$
k f(x_1,\ldots,\,x_n) = \sum_{i=1}^n x_i \dfrac{\partial f}{\partial x_i}
$$ {#eq-CM_differential_of_homogeneous_function}

가 성립한다. $L_0,\,L_1,\,L_2$ 를 각각 $\{\dot{q}_i\}$ 에 대한 $0,\,1,\,2$ 차 동차함수(homogeneous function) 이며 $L=L_0 + L_1 + L_2$ 라면, 

$$
H = \sum \dot{q}_i p_i - L_0 - L_1 - L_2 = \sum \dot{q}_i \dfrac{\partial L}{\partial \dot{q}_i} - L_0 - L_1 - L_2 = L_2-L_0
$$

이다. 이것을 $\bf{q}$ 에 대해 표현하면 $L_2$ 는 $\dot{\bf{q}}$ 에 대한 이차함수이며, $L_1$ 은 $\dot{\bf{q}}$ 에 대해 일차함수이다. 따라서, 적당한 상수벡터 $\bf{a}$ 와 행렬 $\bf{T}$ 에 대해 

$$
L_0 = L_0 (\bf{q}),\quad L_1 = \bf{a}^T \dot{\bf{q}},\quad L_2 =\dfrac{1}{2}\dot{\bf{q}}^T \bf{T}\dot{\bf{q}}, 
$$

이다. 이 때 정준운동량 $\bf{p}$ 는

$$
\bf{p}= \bf{T}\dot{\bf{q}} + \bf{a}
$$

이다. 일반적으로 $\bf{T}$ 는 positive definite 행렬(이므로 당연히 symmetric)이므로 가역행렬이며, 따라서 [positive definite 행렬에 대해서는 선형대수학을 참고하라]{.aside}

$$
\dot{\bf{q}} = \bf{T}^{-1}(\bf{p}-\bf{a})
$$

이다. 따라서 해밀토니안 $H$ 는

$$
H = \dfrac{1}{2} (\bf{p}-\bf{a})^T \bf{T}^{-1} (\bf{p}-\bf{a}) - L_0(\bf{q})
$$


이다. 이제 이것을 전자기장에서의 라그랑지안에 대해 생각해보자. @eq-CM_generalized_force 으로 주어진 일반화된 포텐셜에 대해 

$$
L = T-U = \dfrac{1}{2}mv^2 -q\phi + q \bf{A\cdot v}
$$

이다. 따라서 정준운동량 $\bf{p}$ 는

$$
\bf{p} = \dfrac{\partial L}{\partial \bf{v}} = m\bf{v} + q\bf{A}
$$

이므로, 

$$
H = \dfrac{\|\bf{p}- q\bf{A}\|^2}{2m} + q\phi
$$ {#eq-CM_hamiltonian_of_charged_particle}

이다. 

</br>

### 심플렉틱 표기법 {#sec-CM_symplectic_notation}

$n$-자유도 시스템에 대해 $2n$ 개의 성분을 갖는 벡터 $\bf{\eta}$ 를 $\eta_i = q_i,\, \eta_{n+i} = p_i$ 로 정의하자. 즉
$$
\bf{\eta} = \begin{bmatrix} \bf{q} \\ \bf{p}\end{bmatrix}.
$$ {#eq-CM_vctor_in_simplectic_notation}

이다. 또한 $n\times n$ 영행렬 $\bf{0}_n$ 와 항등행렬 $\bf{1}_n$ 에 대해 $2n \times 2n$ 행렬 $\bf{J}$ 를 다음과 같이 정의하자.

$$
\bf{J} = \begin{bmatrix} \bf{0}_n & \bf{1}_n\\ -\bf{1}_n & \bf{0}_n \end{bmatrix}
$$

그렇다면 해밀턴의 정준방정식 @eq-CM_canonical_equation_of_hamiltonian 은 다음과 같이 쓸 수 있다.

$$
\dot{\bf{\eta}} =  \bf{J} \left(\nabla_\bf{\eta} H\right).
$$ {#eq-CM_simplectic_notation_of_hamilton_equation_of_motion}

해밀턴 운동방정식을 위와 같이 표기하는 것을 **심플렉틱 표기법(symplectic notation)** 이라고 한다. 

$\bf{J}$ 를 많이 사용하므로 여기서 $\bf{J}$ 의 기본 성질에 대해 정리하자. 

$$
\bf{J}^2 = \bf{1}_{2n}.
$$ {#eq-CM_symplectic_J_square}

$$
\bf{J}^T\bf{J} = \bf{JJ}^T = \bf{1}_{2n}.
$${#eq-CM_symplectic_J_orthogonality}

$$
\det(\bf{J}) = 1.
$$ {#eq-CM_symplectic_determinant_of_J}

</br>

### 순환좌표 와 보존 정리 {#sec-cyclic_coordinate_hamiltonian}

[정준운동량과 위상공간](#sec-CM_variational_phase_space) 에서 다루었던 순환 좌표를 다시 생각해보자. 라그랑지안과 해밀토니안의 관계 즉 $H = \sum_i \dot{q}_i p_i -L$ 을 생각해보면

$$
\dfrac{\partial L}{\partial q_i}=0 \iff \dfrac{\partial H}{\partial q_i}=0
$$

이 성립한다. $\dot{p}_i = - \dfrac{\partial H}{\partial q_i}$ 이므로 $H$ 에 명시적인 $q_i$ 의존성이 없다면 $p_i$ 는 운동상수이다. 


또한 해밀턴 운동방정식 @eq-CM_canonical_equation_of_hamiltonian 과 @eq-CM_time_dependence_of_hamiltonian 으로부터
$$
\begin{aligned}
\dfrac{dH}{dt} &= \sum_i \left[\dfrac{\partial H}{\partial q_i} \dot{q_i} + \dfrac{\partial H}{\partial p_i} \dot{p}_i\right] + \dfrac{\partial H}{\partial t} \\[0.3em]
&= \sum_i \left[-\dot{p}_i \dot{q}_i  + \dot{q}_i \dot{p}_i\right] + \dfrac{\partial H}{\partial t} = \dfrac{\partial H}{\partial t} = -\dfrac{\partial L}{\partial t}
\end{aligned}
$$

을 얻는다. 즉 라그랑지안이 명시적으로 시간에 의존적이지 않으면 해밀토니안 값은 운동상수이다. 

</br>

## 라우스 과정

해밀토니안 운동방정식으로 역학 문제를 푸는 것은 많은 경우 라그랑지안 방법에 비해 큰 장점이 없다. $2n$ 개의 1차 미분방정식을 풀다보면 결국은 라그랑지안 운동방정식으로 돌아가는 경우도 많다. 여기서는 그 예외를 살펴보겠다. 해밀토니안 운동방정식은 순환 좌표에 대해 관련된 문제를 풀 때 큰 도움이 된다. $\bf{q}\in \R^n$ 에서 $q_n$ 이 순환좌표인 경우를 살펴보자. 이 경우 라그랑지안은 다음과 같다.

$$
L = L(q_1,\ldots,\,q_{n-1}; \dot{q}_1, \ldots,\, \dot{q}_n;t)
$$

일반화된 속도 $\dot{q}_n$ 이 라그랑지안에 나타난다. 비록 순환좌표가 있더라도 일반적인 $n$-자유도 시스템을 풀 때와 크게 다르지 않다. 그러나 해밀토니안의 경우 경우 $p_n$ 이 상수이므로 $p_n=\alpha$ 라고 놓으면

$$
H = H(q_1,\ldots,\,q_{n-1};p_1,\ldots,\,p_{n-1};\alpha;t)
$$

이 된다. 즉 $n-1$-자유도 문제가 되며 $q_n$ 의 변화는

$$
q_n = \dfrac{\partial H}{\partial \alpha}
$$

를 통해 얻을 수 있다. 

순환좌표가 있을 경우 해밀토니안과 라그랑지안을 섞어 쓸 수 있는 데 이것은 라우스(Routh) 에 의해 고안되었다.$^{\dagger}$[$^\dagger$ Edward John Routh 는 캐나다 퀘벡 출신이므로 프랑스식으로 라우스 라고 읽는다.]{.aside} $n$-자유도 시스템에서 $q_{s+1},\ldots,\,q_n$ 이 순환좌표일 때 라우시안 $R$ 을 아래와 같이 정의한다.

$$
R(q_1,\ldots,\,q_n;\dot{q}_1,\ldots,\,\dot{q}_{s};p_{s+1},\ldots,\,p_n;t) := \sum_{i=s+1}^n p_i\dot{q}_i-L.
$$ {#eq-CM_definition_of_routhian}

$R$ 에 대한 미분은 다음과 같다.

$$
dR = \sum_{i=s+1}^n \dot{q}_i dp_i - \sum_{i=1}^s \dfrac{\partial L}{\partial \dot{q}_i}d\dot{q}_i - \sum_{i=1}^n \dfrac{\partial L}{\partial q_i}dq_i - \dfrac{\partial L}{\partial t}dt.
$$

이로부터,

$$
\begin{aligned}
\dfrac{\partial R}{\partial q_i} &= - \dfrac{\partial L}{\partial q_i},\qquad &\dfrac{\partial R}{\partial \dot{q}_i} &= - \dfrac{\partial L}{\partial \dot{q}_i}, \qquad \qquad& i=1,\ldots,\,s,\\[0.3em]
\dfrac{\partial R}{\partial q_i}&=-\dot{p}_i, &\dfrac{\partial R}{\partial p_i} &= \dot{q}_i, & i=s+1,\ldots,\,n
\end{aligned}
$$ {#eq-CM_equation_of_motion_of_routhian}


</br>

## 변분법으로부터 해밀턴 운동 방정식으로 

### 변형된 해밀턴의 원리 {#sec-CM_modified_hamilton_principle}

- [StackExchange 의 관련 논의](https://physics.stackexchange.com/questions/560216/modified-hamiltons-principle-overconstraining-a-system-by-imposing-too-many-bou)

[해밀턴의 원리](02_variational_principle.qmd#sec-CM_least_action_theorem) 를 상기하자. 라그랑쥬 방정식은 해밀턴의 원리로부터의 자연스러운 결론이다. 이제 해밀턴의 원리로부터 해밀턴의 운동방정식이 자연스럽게 유도됨을 보이고자 한다. 라그랑지안 $L$ 에 대한 action $S_L$ 은 다음과 같다.

$$
S_L = \int_{t_1}^{t_2} L(\bf{q},\, \bf{\dot{q}},\,t)\, dt .
$$

$L(\bf{q},\,\dot{\bf{q}},\,t) = \sum_i \dot{q}_i p_i - H(\bf{q},\, \bf{p},\,t)$ 이므로 라그랑지안이 아닌 해밀토니안을 사용하는 action $S_H$ 를 아래와 같이 정할 수 있다.

$$
S_H = \int_{t_1}^{t_2} \left[\sum_{i} \dot{q}_i p_i - H(\bf{p},\, \bf{q},\,t)\right] \, dt
$$ {#eq-CM_action_in_phase_space}

이다. 여기서 라그랑지안에 대한 $S_L$ 는 짜임새 공간에서의 경로에 대한 적분이지만 해밀토니안에 대한 $S_H$ 는 위상공간에서의 경로에 대한 적분이 이 되며, 해밀토니안 형식에 따라 $\bf{q}$ 와 $\bf{p}$ 는 각각 독립변수로 간주된다. 따라서 @eq-CM_action_in_phase_space 에서 적분되는 함수는 $\bf{q},\, \dot{\bf{q}},\, \bf{p},\, \dot{\bf{p}}$ 의 함수로 표현되어야 한다. 따라서 어떤 경로의 변형 역시 위상공간에서의 경로의 변형 이다. 해밀턴의 원리는 짜임새 공간에서의 action $S_L$ 에 대해 다루는데 **변형된 해밀턴의 원리 (modified Hamilton's principle)** 는 위상공간에서의 action $S_H$ 에 대해 $\delta S_H=0$ 이 되는 위상공간 상의 경로를 따른는 것을 주장한다. 즉

$$
\delta S_H = \delta \int_{t_1}^{t_2} \left[\sum_{i} \dot{q}_i p_i - H(\bf{p},\, \bf{q},\,t)\right] \, dt = 0
$$ {#eq-CM_modified_hamilton_principle}

이다. 이 변형된 해밀턴의 원리가 가장 많이 사용되는 곳은 다음 장에 다룰 변환 이론이지만 여기서 중요한 것은 이 변형된 해밀턴의 원리를 통해 해밀턴의 정준 운동방정식을 유도할 수 있다는 것이다. @eq-CM_modified_hamilton_principle $[\;\cdots\;]$ 안의 함수를 $F$ 라고 임시로 붙이면 $F$ 는 $\bf{q},\, \dot{\bf{q}},\, \bf{p}$ 의 함수이며 $\dot{\bf{p}}$ 에 명시적인 의존성은 없다. 변형된 해밀턴의 원리는

$$
\delta S = \delta\int_{t_1}^{t_2} \left[\sum_i \dot{q}_i p_i - H(\bf{q},\, \bf{p},\,t)\right] \, dt = \delta \int_{t_1}^{t_2}F(\bf{q},\, \dot{\bf{q}},\,\bf{p}, t)\, dt =0
$$

이 된다. 그리고 이에 대한 오일러-라그랑쥬 방정식은, 

$$
\begin{aligned}
\dfrac{d}{dt}\left(\dfrac{\partial F}{\partial \dot{q}_i}\right) - \dfrac{\partial F}{\partial q_i} &= 0, \qquad  i = 1,\ldots,\,n \\
\dfrac{d}{dt}\left(\dfrac{\partial F}{\partial \dot{p}_i}\right) - \dfrac{\partial F}{\partial p_i} &= 0, \qquad  i = 1,\ldots,\,n \\
\end{aligned}
$$ {#eq-CM_euler_lagrange_equation_from_action_using_hamiltonian}

이다. 첫번째 식으로부터 

$$
\dot{p}_i = - \dfrac{\partial H}{\partial q_i}
$$

를 얻을 수 있으며, $F$ 는 명시적인 $\dot{p}_i$ 의존성이 없으므로 두번째 식으로부터

$$
\dot{q}_i = \dfrac{\partial H}{\partial q_i}
$$

를 얻는다. 즉 우리는 변형된 해밀턴의 원리로부터 해밀턴의 운동방정식을 얻었다. 여기서 몇가지를 정리해 보기로 하자.


($1$) 변형된 해밀톤의 원리는 해밀턴의 원리와 동일한지 아니면 다른 추가적인 물리적인 의미를 가지고 있는지에 대해 의문을 가질 수 있다. Goldstein 에 의하면 이 질문은 irrelevant 하다(@Goldstein1980Mechanics pp. 363, 3판의 경우는 pp. 354-355). 해밀턴의 원리가 정당한 것은 해밀턴의 원리의 결과가 라그랑쥬 방정식이기 때문이다. 변형된 해밀턴의 원리가 정당한 것은 그 결과가 해밀턴 운동방정식이기 때문이다. 

($2$) 해밀턴의 원리와 변분원리에서는 양 끝점에서의 변화가 $0$ 임을 가정하였으나 변형된 해밀토니안의 원리에 이를 적용한다면 운동량에 대해서도 $\delta p_i(t_1)= \delta p_i(t_2)=0$ 임을 가정해야 할 것 같다. 그런데 이 가정은 필요가 없는 것이, @exr-CM_variational_devivation_of_euler_lagrange_eq 에서 보았듯이 $\delta p_i = 0$ 이 필요한 것은 부분적분에서 

$$
\left.\dfrac{\partial F}{\partial \dot{p}_i} \dfrac{\partial p_i}{\partial \alpha} \right|_{t_1}^{t_2}
$$

인 부분이다. 그런데 $F$ 는 $\bf{\dot{p}}$ 에 명시적인 의존성이 없기 때문에 위의 항은 항상 $0$ 이다. 즉 변형된 해밀톤의 원리에로부터 해밀턴 운동방정식을 유도할 때 $\delta \bf{p}=0$ 의 조건은 필요하지 않다. <u>즉 해밀턴의 원리와 변형된 해밀턴의 원리는 동일한 경계조건을 사용한다.</u>




</br>

## 연습문제 {.unnumbered}




