---
title: "그림들-테스트"
number-sections: true
number-depth: 2
crossref:
  chapters: true
---

```{r, engine = 'tikz'}
#| label: fig-refrence_frame_in_relativity
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-align: center
#| fig-cap: "두 좌표계"

\usetikzlibrary {3d} 
\begin{tikzpicture}[z={(10:10mm)},x={(-45:5mm)}]
  \def\wave{
    \draw[fill,thick,fill opacity=.2]
     (0,0) sin (1,1) cos (2,0) sin (3,-1) cos (4,0)
           sin (5,1) cos (6,0) sin (7,-1) cos (8,0)
           sin (9,1) cos (10,0)sin (11,-1)cos (12,0);
    \foreach \shift in {0,4,8}
    {
      \begin{scope}[xshift=\shift cm,thin]
        \draw (.5,0)  -- (0.5,0 |- 45:1cm);
        \draw (1,0)   -- (1,1);
        \draw (1.5,0) -- (1.5,0 |- 45:1cm);
        \draw (2.5,0) -- (2.5,0 |- -45:1cm);
        \draw (3,0)   -- (3,-1);
        \draw (3.5,0) -- (3.5,0 |- -45:1cm);
      \end{scope}
    }
  }
  \begin{scope}[canvas is zy plane at x=0,fill=blue]
    \wave
    \node at (6,-1.5) [transform shape] {magnetic field};
  \end{scope}
  \begin{scope}[canvas is zx plane at y=0,fill=red]
    \draw[help lines] (0,-2) grid (12,2);
    \wave
    \node at (6,1.5) [rotate=180,xscale=-1,transform shape] {electric field};
  \end{scope}
\end{tikzpicture}
```


```{r, engine = 'tikz'}
#| label: fig-area_swept_by_radius_vector
#| code-fold: true
#| fig-width: 3
#| output: asis
#| fig-align: center
#| fig-cap: "두 좌표계"

\usetikzlibrary {3d} 
\usetikzlibrary {arrows}
\usetikzlibrary{shapes.geometric}
\begin{tikzpicture}[=>stealth, scale=3]
\draw [black, thick] plot [smooth, tension=1] coordinates { (0,1.5) (1.5,1.0) (2, 0)};
\draw [black, very thick, -{stealth}] (0, 0) node[left, scale =1.2] {$O$}-- (1.19, 1.19);
\draw [black, very thick, -{stealth}] (0, 0) -- (1.5, 0.99); 
\draw [thick] (0.6,0.6) arc (45:29:0.6);
\node [right, scale=1.2] at (0.6, 0.6) {$d\theta$};
\node [above, scale=1.2] at (0.8, 0.8) {$\boldsymbol{r}$};
\draw [thick, dashed] (1.19, 1.19) -- (1.35, 0.9);
\node [above, scale = 1.2] at (1.35, 1.3) {$r d\theta$ };
\draw [black, thick, -{stealth}] plot [smooth, tension=1] coordinates { (1.35,1.3) (1.29, 1.0)};
\end{tikzpicture}
```


```{r, engine = 'tikz'}
#| label: fig-effective_potential_for_kepler_problem
#| code-fold: true
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "케플러 문제"

\usetikzlibrary{arrows}
\usetikzlibrary{positioning}
\usetikzlibrary{calc}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations.pathreplacing}

\begin{tikzpicture}[domain=0.26:6, samples = 100, scale=1]

\draw[-{stealth}] (-0.5, 0) -- (6.5,0) node[right, scale=0.6] {$r$};
\draw[-{stealth}] (0,-1.5) -- (0,2.2) node[right, scale=0.6] {$V_{\textrm{eff}}(r)$};

\draw[color=black]   plot[id=veff] (\x, {  (\x^-2 -  2.8* \x^-1)/2} ) ;
%\draw[dashed, red] (0.9, 0.15) node[left, scale=0.6] {$E_1$}-- (6.0, 0.15) ;
%\draw[dashed, blue] (0.9, 0.5) node[left, scale=0.6] {$E_2$}-- (6.0, 0.5) ;
%\draw[dashed, violet] (0.9, 1.0) node[left, scale=0.6] {$E_3$}-- (6.0, 1.0) ;
%\draw[dashdotted] (1.3, 1.0) node[above, scale=0.6] {$$} -- (1.3, -0.18) node[below, scale=0.6] {$x_1$};
%\draw[dashdotted] (1.49, 0.55) -- (1.49, -0.05) node [below, scale=0.6] %{$x_2$};
\draw[dashed] (0.71, -0.95) -- (0.71, 0.05) node [above, scale=0.6] {$r_\textrm{min}$};

%\draw[dotted] (1.94, 0.15) -- (1.94, -0.05) node [below, scale=0.6] {$x_0$};

\end{tikzpicture}
```


```{r, engine = 'tikz'}
#| label: fig-central_field_orbit
#| code-fold: true
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "중심장의 궤도"

\usetikzlibrary {arrows.meta}
\begin{tikzpicture}[line cap=round]
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=0:0.93*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=0.93*pi:3.1*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=3.1*pi:5.25*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=5.25*pi:7.40*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=7.40*pi:9.55*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=9.55*pi:11.70*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=11.70*pi:13.84*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=13.84*pi:15.98*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=15.98*pi:18.12*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=18.12*pi:20.26*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});
\draw[red, thick, -{Stealth[length=2mm]}] plot[variable=\t,domain=20.26*pi:20.53*pi, samples=100, smooth,thick] ({cos(\t r)/(1 + 0.8*cos(0.9331 * \t r))},{sin(\t r)/(1 + 0.8*cos(0.9331 * \t r))});

\draw[fill=none, dashed, blue, thick](0,0) circle (5);
\draw[fill=none, ](0,0) circle (0.05);
\draw[thick,  -{Stealth[length=2mm]}] (0, 0) -- (-2.5, 4.33);
\draw[thick,  -{Stealth[length=2mm]}] (0, 0) -- (0.556, 0);
\node[black, left] at (-1.25, 2.17) {$r_{\textrm{max}}$};
\node[black, below] at (0.278, 0) {$r_{\textrm{min}}$};

\draw[thick] (-4.776, -1.094) -- (-5.166, -1.184);
\draw[thick] (-3.823, -3.065) -- (-4.135, -3.315);

\draw [thick, {Stealth[length=2mm]}-{Stealth[length=2mm]}] (-5.069,-1.161) arc (192.9:218.716:5.2);
\node[left] at (-4.7, -2.2) {$\Delta \theta$};
\end{tikzpicture}
```


```{r, engine = 'tikz'}
#| label: fig-kepler_orbit_1
#| code-fold: true
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "$\varepislon$ 에 따른 궤도"

\usetikzlibrary {arrows.meta}
\begin{tikzpicture}[line cap=round, scale=3]

\filldraw[](0,0) circle (0.02);
\node[left, scale = 1.5] at (0, 0) {$O$};

\draw[black, thick] plot[variable=\t,domain=0:2*pi, samples=100, smooth,thick] ({cos(\t r)},{sin(\t r)});
\node[right, scale=1.5] at (0.707, 0.707) {$\varepsilon =0$};

\draw[blue, thick] plot[variable=\t,domain=0:2*pi, samples=100, smooth,thick] ({cos(\t r)/(1+0.7 * cos(\t r))},{sin(\t r)/(1+0.7 * cos(\t r))});
\node[blue, scale = 1.5] at (-1.5, 1.2) {$\varepsilon = 0.7$};

\draw[red, thick] plot[variable=\t,domain=-2*pi/3:2*pi/3, samples=100, smooth,thick] ({cos(\t r)/(1+  cos(\t r))},{sin(\t r)/(1 +  cos(\t r))});
\node[red, scale = 1.5] at (-1.3, 1.7) {$\varepsilon = 1$};

\draw[teal, thick] plot[variable=\t,domain=-2*pi/3:2*pi/3, samples=100, smooth,thick] ({cos(\t r)/(1.0+ 1.2* cos(\t r))},{sin(\t r)/(1.0 + 1.2* cos(\t r))});
\node[teal, scale = 1.5] at (-0.4, 1.8) {$\varepsilon = 1.2$};
\end{tikzpicture}
```