---
title: "그림들"
number-sections: true
number-depth: 2
crossref:
  chapters: true
---

```{r, engine = 'tikz'}
#| label: fig-radius_vector_in_two_frame
#| code-fold: true
#| echo: fenced
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "두 좌표계"

\usetikzlibrary {3d} 
\usetikzlibrary {arrows}
\usetikzlibrary{shapes.geometric}
\begin{tikzpicture} %[=>stealth]
  
  \coordinate (O) at (0,0);
  \coordinate (O1) at (2.5, -0.5);

  \draw [->] (O) -- (xyz cs:x=3);
  \draw [->] (O) -- (xyz cs:y=3);
  \draw [->] (O) -- (xyz cs:z=3); 
  \draw [->] (O1) -- (xyz cs:x=5.5, y=-0.5);
  \draw [->] (2.5,-0.5) -- (xyz cs:x=2.5, y=2.5);
  \draw [->] (2.5,-0.5) -- (xyz cs:x=2.5, y=-0.5, z=3); 

  \node[below, scale=.7] at (O) {$\mathcal{O}$};
  \node[below, scale=.7] at (O1) {$\mathcal{O^\prime}$};
  \draw [thick, -{stealth}] (0, 0) -- (xyz cs:x=2,y=2, z=1);
  \node[below right, scale=.7] at  (xyz cs:x=1,y=1, z=0.5) {$\boldsymbol{r}$};
  \draw [thick, -{stealth}] (2.5, -0.5) --(xyz cs:x=2, y=2, z = 1);
  \node[left, scale=.7] at (xyz cs:x=2.25, y=0.75, z = 0.5) {$\boldsymbol{r}^\prime$};

  
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-refrence_frame
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 6
#| fig-align: center
#| fig-cap: "두 좌표계"

\begin{tikzpicture}[x=0.5cm,y=0.5cm,z=0.3cm,>=stealth]
\draw[->] (xyz cs:x=-1) -- (xyz cs:x=6) node[above] {$x$};
\draw[->] (xyz cs:y=-1) -- (xyz cs:y=6) node[right] {$z$};
\draw[->] (xyz cs:z=-1) -- (xyz cs:z=6) node[above] {$y$};
\node[anchor= north west] at (xyz cs:x=0) {$\mathcal{O}$};

\draw[->] (xyz cs:x=9) -- (xyz cs:x=16) node[above] {$x'$};
\draw[->] (xyz cs:x=10, y=-1) -- (xyz cs:x=10, y=6) node[right] {$z'$};
\draw[->] (xyz cs:x=10, z=-1) -- (xyz cs:x=10, z=6) node[above] {$y'$};
\node[anchor= north west] at (xyz cs:x=10) {$\mathcal{O}'$};
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-double_pendulum
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 2
#| fig-height: 5
#| fig-align: center
#| fig-cap: "쌍진자"
\usetikzlibrary{calc}
\usetikzlibrary{arrows}
\begin{tikzpicture}[scale=1, rotate=0]
\coordinate(O) at (0, 0);
\coordinate(A) at (3,-3);
\coordinate(B) at (1,-5.2);
\coordinate(D1) at ([shift=({0,-3})]O);;
\coordinate(D2) at ([shift=({0,-3})]A);
\draw[dashed] (O) -- (D1);
\draw[dashed] (A) -- (D2);
\draw[thick] (0, 0) -- (A) -- (B) ;
\filldraw[red] (A) circle(3px);
\filldraw[blue] (B) circle(3px);
\draw[->, >=stealth ,semithick] (0,-1) arc(-90:-45:1);
\draw[->, >=stealth, semithick] ([shift=({0, -1})]A) arc(270:230:1);
\node[anchor= north] at (0.4, -0.9) {$\theta$};
\node[anchor= north] at (2.6, -3.9) {$\phi$};
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-brahistochrone
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 4
#| fig-align: center
#| fig-cap: "Brachistochrone"
\begin{tikzpicture}[scale=1.4, rotate=0]
  \coordinate (O) at (0,0);
  \coordinate (A) at (4,0);
  \coordinate (B) at (0,-4);
  \coordinate (P1) at (1,0);
  \coordinate (R2) at (4,-3.5);
  \draw[-stealth, thick] (-0.5,0) -- (A);
  \node [anchor=south east] at (A) {$x$};
  \draw[-stealth, thick] (0,0.5) -- (B);
  \node [anchor=south east] at (B) {$y$};
  \draw node[fill,circle, scale=0.3] at (0.7,0) {};
  \draw node[anchor=south] at (0.7,0) {$1$};
  \draw node[fill,circle, scale=0.3] at (R2) {};
  \draw node[anchor=north] at (R2) {$2$};
  \draw [blue, ultra thick] plot [smooth, tension=0.7] coordinates {(0.7,0) (1.5,-0.5) (2,-1.7) (2.5, -2.3) (3.4,-2.9) (4,-3.5)};
  \draw [-stealth, thick] (2.2,-1.7)--(2.7, -2.15);
  \draw node[anchor=south] at (2.2, -1.7) {$\boldsymbol{v}$};
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-translational_symmeetry
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 4
#| fig-align: center
#| fig-cap: "Translational Symmeetry"
  \begin{tikzpicture}[scale=1.2, rotate=0]
    \coordinate (O) at (0,0);
    \coordinate (A) at (4,0);
    \coordinate (B) at (0,4);
    \coordinate (R1) at (2.5,3);
    \coordinate (R2) at (4,3);
    \draw[thick] (-1,0) -- (A);
    \draw[thick] (0,-1) -- (B);
    \draw[-stealth, ultra thick] (O) -- (R1);
    \draw[-stealth, ultra thick] (O) -- (R2);
    \draw[-stealth, ultra thick, blue] (R1) -- (R2);
    \node [anchor=south east] at (1.25,1.5) {$\boldsymbol{r}_i(q_j)$};
    \node [anchor=north west] at (2,1.5) {$\boldsymbol{r}_i(q_j+dq_j)$};
    \node [anchor=south ] at (3.25,3) {$dq_j\hat{\boldsymbol{n}}$};
  \end{tikzpicture}
``` 

```{r, engine = 'tikz'}
#| label: fig-rotation_of_vector
#| code-fold: true
#| echo: fenced
#| fig-width: 6
#| output: asis
#| fig-align: center
#| fig-cap: "두 좌표계"

\usetikzlibrary {3d} 
\usetikzlibrary {arrows}
\usetikzlibrary{shapes.geometric}
\begin{tikzpicture} %[=>stealth]
\tikzset{
    partial ellipse/.style args={#1:#2:#3}{
        insert path={+ (#1:#3) arc (#1:#2:#3)}
    }
}
  \draw [->] (0,0) -- (xyz cs:x=3);
  \draw [->] (0,0) -- (xyz cs:y=4.5);
  \draw [->] (0,0) -- (xyz cs:z=3); 
  \draw [dashed] (0.0,3.0) ellipse (1.5 and 0.5);
  \draw [thick, -{stealth}] (0, 0) -- (xyz cs:x=0.7,y=2.55);
  \node[below, scale=.6] at (0.3, 2.3) {$\boldsymbol{r}_i (q_j)$};
  \draw [thick, -{stealth}] (0, 0) --(xyz cs:x=1.4,y=2.8);
  \node[scale=.6] at (1.5, 1.7) {$\boldsymbol{r}_i (q_j+dq_j)$};
  \draw [red, thick, -{stealth}] (0.7, 2.55) -- (1.4, 2.8);
  \node[red, scale=.6] at (1.0, 2.5) {$d\boldsymbol{r}_i$};
  \draw [thick, -{stealth}] (0, 3) -- (0, 3.7) node[right, scale=0.6] {$\;\hat{\boldsymbol{n}}$};

  \draw [teal] (0, 3) -- (0.7, 2.55);
  \draw [teal] (0, 3) -- (1.4, 2.8);
  \draw[teal, ->] (0, 3.0) [partial ellipse=297:340:0.6 and 0.2] node[above, scale=0.6] {$dq_j$} ;
  \draw[purple, ->] (0, 0) [partial ellipse=90:75:1 and 1] node[above left, scale=0.6] {$\theta$} ;
\end{tikzpicture}
```