---
title: "고전 장론 입문"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---

## 스칼라장

$n$ 차원 공간과 $1$ 차원의 시간을 합친 시공간에 대해 $\phi : \mathbb{R} \otimes \mathbb{R}^n \to \mathbb{R}$ 을 **스칼라장(scalar field)**이라고 하며 $\boldsymbol{A}: \mathbb{R} \otimes \mathbb{R}^n \to \mathbb{R}^n$ 을 $n$ 차원 **벡터장(vector field)**이라고 한다. 

입자에 대한 이론에서 자유도는 위치, 즉 좌표였다. 장론에서의 자유도는 장(field) 이다. 즉 물리 현상은 장에 의해 기술된다. 


</br>

### 비상대론적 입자를 기술하는 입장에서

$x$ 축을 따라 움직이는 입자의 움직임을 기술한다고 생각해 보자. 우리는 이 입자의 운동을 $x(t)$ 가 아닌 $\phi(t)$ 로 기술해 보자. $\phi(t)$ 는 $0$ 차원 공간과 $1$ 차원 시간에 대한 스칼라장이라고 볼 수 있다. 

이제 action $S$ 를 생각하자 비상대론적 입자에 대해서는 장론에서는 라그랑지안을 $\mathcal{L}$ 로 기술한다. 

$$
S = \int_a^b \mathcal{L}\, dt
$$

이며 운동에너지는 $\dfrac{m\dot{\phi}^2}{2}$ 이다. $m=1$ 로 놓아 식을 단순화시켜보자. 포텐셜 에너지는 위치만의 함수이므로 $V(\phi)$ 로 쓸 수 있다. 즉

$$
\mathcal{L}= \dfrac{1}{2}\left(\dfrac{d\phi}{dt}\right)^2 + V(\phi)
$$

이며, 

$$
S = \int_a^b \left[ \dfrac{1}{2}\left(\dfrac{d\phi}{dt}\right)^2 + V(\phi)\right]\, dt
$$

이고, $S$ 를 최소화 하는 오일러-라그랑쥬 방정식은

$$
\dfrac{d}{dt}\left(\dfrac{\partial\mathcal{L}}{\partial \dot{\phi}}\right) - \dfrac{\partial\mathcal{L}}{\partial\phi}=0
$$

이 된다. 이를 통해 우리는 운동방정식

$$
\dfrac{d^2\phi}{dt^2} = -\dfrac{\partial V(\phi)}{\partial \phi}
$$

를 얻는다. 

</br>

### 장론의 원리

#### 작용 원리

이제 3차원 공간에 대해 생각해보자. 아직 정해지지 않은 장에 대한 함수인 라그랑지안 $\mathcal{L}$ 에 대해 action $S$ 가 다음과 같이 정의된다.

$$
S=\int \mathcal{L}\, dtd^3\boldsymbol{r}.
$$

우리가 관심있는 민코프스키 공간에 대해서는 작용이 

$$
S=\int \mathcal{L}\,d^4x
$$

로 정의된다. 여기서 $\mathcal{L}$ 은 공간에 대해서도 적분하기 때문에 단순히 라그랑지안이 아닌 **라그랑지안 밀도(Lagrangian density)** 라고 불린다. 

</br>

#### 정지 작용 원리 (Stationary action principle)

우리가 이미 알고 있는 입자에 대한 라그랑지안 $L$ 은 입자의 좌표와 속도에 의존한다. 라그랑지안 밀도 $\mathcal{L}$ 는 장에 대해 정의된다. 앞서 말했다시피 장론의 자유도는 장(field) 이다. 만약 $\mathcal{L}$ 의 자유도가 $\phi$ 뿐이라면 $\mathcal{L}$ 은 $\phi$ 와 $X^\mu$ 그리고 $\partial_\mu \phi= \dfrac{\partial \phi}{\partial X^\mu}$ 에 의존한다고 생각 할 수 있다. 즉, 

$$
S = \int \mathcal{L} (\phi,\, X^\mu,\, \partial_\mu \phi)\, d^4x
$$

이다. 고전역학에서의 라그랑지안 $L$ 을 생각해보자. $L$ 이 $t$ 에 대한 명시적인 의존성이 없을 경우 보존계, 즉 에너지가 보존되는 시스템이었다. 마찬가지로 장에 대해 $X^\mu$ 에 대해 명시적인 의존성이 없을 경우 에너지와 운동량이 보존되는 보존계이다. 즉 많은 경우 $\mathcal{L}= \mathcal{L}(\phi,\, \partial_\mu \phi)$ 이다. 

장에 대한 오일러 라그랑주 방정식은 다음과 같은 형태가 된다.

$$
\sum_\mu \dfrac{\partial}{\partial X^\mu} \dfrac{\partial \mathcal{L}}{\partial \left(\dfrac{\partial \phi}{\partial X^\mu}\right)} - \dfrac{\partial \mathcal{L}}{\partial \phi} = 0.
$$ {#eq-classical_field_euler_lagrange_eq_for_field}

만약 어떤 시스템에 2개의 스칼라장 $\phi,\, \chi$ 이 존재한다면 @eq-classical_field_euler_lagrange_eq_for_field 이외에 $\chi$ 에 대한 오일러-라그랑쥬 방정식

$$
\sum_\mu \dfrac{\partial}{\partial X^\mu} \dfrac{\partial \mathcal{L}}{\partial \left(\dfrac{\partial \chi}{\partial X^\mu}\right)} - \dfrac{\partial \mathcal{L}}{\partial \chi} = 0.
$$

도 존재해야 할 것이다. 


</br>

### 라그랑지안 밀도의 형태

라그랑지안의 운동에너지 항을 생각하면 라그랑지안 밀도에 $\partial_\mu \phi$ 의 제곱의 합이 들어가야 할 것 같다. 그러나 $\sum_\mu (\partial_\mu \phi)^2$ 는 너무 대칭적이다. 우리는 나중에 

$$
(\partial_0 \phi)^2 - (\partial_1 \phi)^2 - (\partial_2 \phi)^2 - (\partial_3 \phi)^2
$$

가 로런츠 불변량을 정의한다는 것을 보게 될 것이다. 이를 이용하여 수정된 라그랑지안 밀도

$$
\mathcal{L} = \dfrac{1}{2} \left[(\partial_0 \phi)^2 - (\partial_1 \phi)^2 - (\partial_2 \phi)^2 - (\partial_3 \phi)^2\right] - V(\phi)
$$ {#eq-classical_field_lagrangian_density}

를 우리의 장론에 대한 라그랑지안 밀도로 취급하려 한다. 이 때 $V(\phi)$ 를 **장 포텐셜(field potential)** 이라고 한다. 이제 @eq-classical_field_lagrangian_density 에 대한 오일러-라그랑쥬 방정식은 다음과 같다.

$$
\dfrac{1}{c^2}\dfrac{\partial^2 \phi}{\partial t^2} - \dfrac{\partial^2 \phi}{\partial x^2} - \dfrac{\partial^2 \phi}{\partial y^2} - \dfrac{\partial^2 \phi}{\partial z^2} + \dfrac{\partial V}{\partial \phi}=0.
$$ {#eq-classical_field_euler_lagrange_eq_for_lagrangian_density}

</br>

#### 파동방정식

자유로운 상태 즉 $V(\phi)=0$ 인 경우를 생각하자. @eq-classical_field_euler_lagrange_eq_for_lagrangian_density 에서 무엇이 생각나는가? 바로 파동방정식이다. 이 방정식의 일반해는 다음과 같다.

$$
\phi (t,\,\boldsymbol{r}) = A \sin (\boldsymbol{k \cdot r}+kct) + B \sin \sin (\boldsymbol{k \cdot r}-kct),\qquad \text{where }k=\|\boldsymbol{k}\|
$$


</br>

### 상대론에서의 장

여기서는 장론에서의 로런츠 불변성에 대해 다룬다.

두 관성좌표계 $\Sigma,\, \Sigma'$ 에 대해 어떤 장 $\phi$ 가 로런츠 변환 $X'^{\mu'} = \Lambda_\mu^{\mu'}X^\mu$ 에 대해 

$$
\phi (X^\mu) = \phi'(X'^{\mu'})
$$

일 때 $\phi$ 를 스칼라장이라고 한다. 이 때 $\phi$ 는 $\Sigma$ 좌표계에서, $\phi'$ 은 $\Sigma'$ 좌표계에서 측정한 장의 양이다. 이제 4-벡터장을 정의 할 수 있다. 역시 로런츠 변환 $X'^{\mu'} = \Lambda_\mu^{\mu'}X^\mu$ 에 대해 4-벡터값 $U^\nu$ 가

$$
U'^{\nu'} (X^{\mu'}) = \Lambda_{\nu}^{\nu'}U^\nu(\Lambda_\mu^{\mu'}X^\mu)
$$

일 때 $U^\mu$ 를 4-벡터장이라고 한다.

자 여기서 더 나가기 전에 수학적으로 좀 더 알야야 할 것이 있다.

</br>

### 공변벡터와 반변벡터

두 좌표계 $X^\mu$ 와 $X'^\mu$ 에 의해 표현되는 공간을 생각하자. 또 $dX^\mu$ 와 $d(X')^\mu$ 에 의해 표현되는 무한소 간격을 생각하자. 여기에 다음과 같은 관계가 성립한다. (아인슈타인 합규칙에 따라 $\sum_\nu$ 를 제외한다.)

$$
d(X')^\mu = \dfrac{\partial (X')^\mu}{\partial X^\nu} dX^\nu
$$

$X^\mu$ 와 $X'^\mu$ 의 관계가 로런츠 변환이라면 $\dfrac{\partial (X')^\mu}{\partial X^\nu} = \Lambda^\mu_\nu$ 일 것이다. 4-벡터의 경우

$$
A'^\mu = \dfrac{\partial (X')^\mu}{\partial X^\nu}A^\nu
$$ {#eq-classical_field_transform_of_contravariant_vector}

와 같이 변환된다. 

이제 어떤 좌표 $X$ 에 대한 함수 $\phi (X)$ 를 생각하자. $X'$ 에 대한 $\phi$ 의 도함수는 미적분학의 연쇄규칙에 따라

$$
\partial'_\nu \phi := \dfrac{\partial \phi}{\partial (X')^\nu} = \dfrac{\partial X^\mu}{\partial (X')^\nu}\dfrac{\partial \phi}{\partial X^\mu} = \dfrac{\partial X^\mu}{\partial (X')^\nu}\partial_\mu \phi
$$

임을 안다. 이제 $A_\nu = \partial'\phi$ 라고 하면

$$
A'_{\nu} = \dfrac{\partial X^\mu}{\partial (X')^\nu}A_\mu
$$ {#eq-classical_field_transform_of_covariant_vector}

이다. @eq-classical_field_transform_of_contravariant_vector 와 비교해보면 두 벡터의 차이가 나타난다.

$$
A'^\mu = \dfrac{\partial (X')^\mu}{\partial X^\nu}A^\nu, \qquad A'_{\nu} = \dfrac{\partial X^\mu}{\partial (X')^\nu}A_\mu
$$

$A^\nu \to A'^\mu$ 변환에서는 $X$ 에 대한 $X'$ 의 도함수가 사용되었으며 $A_\mu \to A'_\nu$ 변환에서는 $X'$ 에 대한 $X$ 의 도함수가 사용되었다. 이는 $A^\nu$ 로 표현되는 벡터와 $A_\mu$ 로 표현되는 벡터가 다른 벡터라는 것을 의미한다. @eq-classical_field_transform_of_contravariant_vector 와 같이 변화하는 윗첨자료 표현되는 벡터를 **반변 벡터(contravariant vector)**, @eq-classical_field_transform_of_covariant_vector 와 같이 변화하는 아래첨자로 표현되는 벡터를 **공변 벡터(covariant vector)** 라고 한다. 

만약 이 변환이 로렌츠 변환이라면 @eq-classical_field_transform_of_contravariant_vector 와 @eq-classical_field_transform_of_covariant_vector 의 차이는 두 관성계의 상대속도가 서로 $\boldsymbol{V}$ 와 $-\boldsymbol{V}$ 인 것 뿐이라는 것을 쉽게 알 수 있다. $\Sigma$ 에 대해 $\Sigma'$ 이 $\boldsymbol{V}$ 로 움직인다면 $\Sigma'$ 에 대해서 $\Sigma$ 는 $-\boldsymbol{V}$ 로 움직이는게 당연하다.

4-벡터, 즉 로렌츠 변환으로 변환되는 벡터에 대해 $A_\mu A^\mu$ 는 스칼라이다. @eq-classical_field_transform_of_contravariant_vector 와 @eq-classical_field_transform_of_covariant_vector 로 부터

$$
(A')_\nu(A')^\nu = \dfrac{\partial X^\mu}{\partial (X')^\nu} A_\mu \dfrac{\partial (X')^\nu}{\partial X^\mu}A^\mu = \left(\dfrac{\partial X^\mu}{\partial (X')^\nu} \dfrac{\partial (X')^\nu}{\partial X^\mu}\right)A_\mu A^\mu = A_\mu A^\mu
$$

임을 안다. 

자 우리는 앞서 @sec-special_relativity_4_vectors_and_lorentz_invariants 에서 메트릭 텐서를 알아보았다. 반변벡터 $A^\mu$ 에 대해 공변벡터 $A_\nu$ 는 

$$
A_\nu = \eta_{\nu \mu}A^\mu
$$

와 같다. 즉 $X^\mu = (ct,\,x,\,y,\,z)$ 에 대해 $X_\mu = (ct,\, -x,\,-y,\,-z)$ 이다. 

</br>

## 입자와 장

양자역학에서는 장과 입자가 동일하지만 고전 장론에서는 장과 입자는 구별된다. 지금까지는 고전 장론에서 장과 장이 가져야할 성질에 대해 알아보았다. 고전 장론에서는 장과 입자가 모두 라그랑지안에 포함되어야 하며, 이 라그랑지안은 로렌츠 불변이어야 한다. 

우리는 입자에 대한 라그랑지안이 $-m\sqrt{1-v^2/c^2}$ 임을 안다. 이것을 $\mathcal{L}_\textrm{ptl}=-m\sqrt{1-v^2}$ 로 표기하자. 그러

